### ISSUE TITLE
Only cosmetic filtering with no domain blocking

### ISSUE THREAD

**Issue by specter78** [uBlockOrigin/uBlock-issues#1104]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since I am using pi-hole, domains are getting blocked anyway. Only allowing cosmetic filtering would further reduce resource usage and improve performance.

### A specific URL where the issue occurs

NA

### Steps to Reproduce

NA

### Expected behavior:

NA

### Actual behavior:

NA

### Your environment

* uBlock Origin version: NA
* Browser Name and version: NA
* Operating System and version: NA

**Comment by gwarser** [comment]
Use this https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except but keep cosmetic filtering enabled.

**Comment by gorhill** [comment]
I am going to decline this because blocking with pi-hole is not the same as blocking with uBO.

I [commented about this in the past](https://www.reddit.com/r/uBlockOrigin/comments/epjlpw/can_anybody_explain_to_me_why_ublockorigin_works/fejujjn/), which I will transcribe here:

---

Off the top of my head:

- Pattern-based filtering on whole URL
    - example: `&act=ads_`
- Context information
    - example: `$script,third-party,domain=imgbox.com`
    - point-and-click to enable/disable blocking behavior on a per-site basis:
        - JavaScript
        - Large media elements
        - Remote fonts
        - Etc.
    - you can see what specific network requests are made by what specific page, i.e. you can fully inform yourself of what specific pages/sites are causing your browser to do
        - example: <https://twitter.com/gorhill/status/934474012377444352>
- Ability to redirect to neutered version of a resource
    - example: `||google-analytics.com/ga.js$script,redirect=google-analytics.com/ga.js`
- Cosmetic filtering, i.e. the manipulation of DOM elements in the browser
    - example: `##.AdHeader`
- Scriptlet injection filtering, i.e. the injection of JS scriptlets to modify the behavior of a page -- useful to defuse anti-content blockers
    - example: `wallstreet-online.de##+js(nostif, userHasAdblocker)`
- HTML filtering, i.e. the removal of DOM elements from a document before it is parsed by the browser
    - example: `wetteronline.de##^script:has-text(runCount)`
- Ability to deal with unwanted popups
    - example: `&link_type=offer$popup,third-party`
- You can easily (narrowly/broadly) override any filter from the filter lists through simple point-and-click operations to customize your own filtering or to quickly fix sites broken as a result of overzealous filters

Main advantage of Pi-Hole is that it filters network traffic from all devices on your network, but filtering is blunt compared to what you can do through a browser extension.

---

Additionally, uBO prevents the network request from being made at all, so if we are going to argue performance without evidence, I can as well argue that blocking with uBO is more performant since the browser does not have to fire the network request and wait an answer from the remote blocker.
