### ISSUE TITLE
Shortcuts pane appearing out of nowhere after extension update

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#1142]
### Description

Shortcuts pane appears in the dashboard as discussed in https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/218

### A specific URL where the issue occurs

moz-extension://extension-id/dashboard.html#settings.html

### Steps to Reproduce

- Set `extensionUpdateForceReload` to `true` in advanced settings.

- Manually update dev build via `Check for updates` button located in `*` button at `about:addons` from whatever build version exists before `1.28.1b2`  to `1.28.1b2`

- After successful update message as per Firefox in `about:addons`, open uBO dashboard and the Shortcuts pane appears.

![Capture](https://user-images.githubusercontent.com/21290713/85219719-d0b8fb80-b3c3-11ea-856e-0fba86982242.PNG)

### Expected behavior:

Shortcuts pane to never appear.

### Actual behavior:

Shortcuts pane appearing out of nowhere after an extension update.

### Notes

Disable uBO and then enable it again via `about:addons` and it goes away.

### Your environment

* uBlock Origin version: uBO dev build
* Browser Name and version: Firefox 78/80
* Operating System and version: Win 10

**Comment by gorhill** [comment]
Best is you investigate the code on your side with the debugger, I have never reproduced such issue, so I can't do anything about it.

**Comment by uBlock-user** [comment]
@gwarser You reproduced it, can you add some information or some new repro ?

**Comment by gwarser** [comment]
This is Nightly-only issue. It happens because they changed how tab "context" in Firefox is preserved (if page is trusted - system one like about:newtab, or untrusted - any www). This only happens when this "context preserving" is enabled by `fission.preserve_browsing_contexts` set to `true` in `about:config`. For now it's `true` only in Nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1649125

This is other issue (filled by me) which manifests itself after session restore, and which will also caused by `fission.preserve_browsing_contexts` toggle: https://bugzilla.mozilla.org/show_bug.cgi?id=1647205

Also another one - user cannot navigate away from `file:///` URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1647109

**Comment by uBlock-user** [comment]
> This is Nightly-only issue.

I reproduced already on Stable version 78 once. So I doubt that to the case.

**Comment by gwarser** [comment]
@uBlock-user can you check in latest Nightly (20200709093347)? It's fixed for me.

**Comment by uBlock-user** [comment]
It's never been reproducable at will, so can't say for sure.
