### ISSUE TITLE
uBlock disable fixes a problem that whitelisting site will not -- why?

### ISSUE THREAD

**Issue by lakrsrool** [uBlockOrigin/uBlock-issues#119]
Please refer to this forum topic for questions I have in regards to issue title: 
https://forum.palemoon.org/viewtopic.php?f=46&t=19615
Thanks

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
Keep such questions on reddit.

**Comment by gorhill** [comment]
I read the issue and nowhere does it mention consulting the logger -- a required step to rule out filter issues.

**Comment by gorhill** [comment]
Volunteers can't help people un-willing to be helped and contribute back to help solve issues for all: [long unproductive post](https://forum.palemoon.org/viewtopic.php?f=46&t=19615#p145229) with no sign of following the advice to look at the logger as first step.

> I have disabled ALL FILTERS on UblockOrigin and still get the same issue

"Filter issues" implicitly include custom filters and _rules_.

Anyway, from this point on I will consider only information provided here, the posts on Pale contain nothing actionable.

**Comment by uBlock-user** [comment]
> I personally consider the required conventions to post on github irrelevant in this specific situation and as such places an undue and unnecessary burden on the user posting the issue imho.

First he files a bug without filling required info,  asks us to answer him on his choice of 3rd party forum as if we offer such service for him, when asked here to fill in bug report, ignores that purposefully and responds to that on that 3rd party forum. These are the kind of posters who I feel are don't deserve any help from this tracker. He posted it there, so expect any help there itself.

**Comment by mattatobin** [comment]
PMR is likely frustrated. Don't be too hard on him. Fact is he shouldn't be requesting or requiring an answer from you about support from your extension on the forums. However, marking his issue invalid out of course before a dialog has commenced didn't help matters for him.

Indeed, I know uBlock isn't a very good _Pale Moon_ extension because it isn't being considered or worked on as a _Pale Moon_ extension merely a dead end legacy Firefox extension. Only been saying it for three years now. Still, I know the effect dismissive "support" has on a user and I been trying to improve on it. Shame @gorhill hasn't been doing the same.

**Comment by gorhill** [comment]
> uBlock isn't a very good Pale Moon extension because it isn't being considered or worked on as a Pale Moon extension merely a dead end legacy Firefox extension.

And yet that firefox-legacy branch (which point is to keep supporting more than just Pale Moon, i.e. Sea Monkey et al.) has more activity than [ABPrime](https://github.com/binoc-central/abprime/commits/TRUNK), and support modern filtering capabilities such as `csp=`, `abp-contains`, etc.

As I [already said regarding the firefox-legacy branch](https://github.com/gorhill/uBlock/issues/3666#issuecomment-384944826), pull requests crafted with care are welcomed, so are positive contributions ([example](https://github.com/uBlockOrigin/uBlock-issues/issues/63#issuecomment-397901987)). Stating "isn't a very good Pale Moon extension" isn't a positive contribution, it's un-actionable.

>  I know the effect dismissive "support" has on a user and I been trying to improve on it. Shame @gorhill hasn't been doing the same.

@lakrsrool checked the _"This is not a support issue or a question"_ item. The issue tracker is for actual issues with uBO. The idea is to not over-burden volunteers, and the rules in place are to protect the project from being run in the ground by over-burdening volunteers -- there is no "staff" here, just volunteers.

Consider the [amount of invalid issues being opened](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+is%3Aclosed+label%3Ainvalid) despite these rules, so relaxing them is not going to help, the rules just force people to be more thorough on their side before opening issues, and as a result spread the workload of validating real issues to more people.

Thousands of issues have been dealt with since the project was first released, and this is your [presence](https://github.com/gorhill/uBlock/issues?q=is%3Aissue+commenter%3Amattatobin) in the issue tracker, so for you to lecture how things should work here is a bit much.
