### ISSUE TITLE
uBO badge counter doesn't work when network requests originate from service-workers 

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uBlock-issues#1204]
### URL(s) where the issue occurs

`https://www.fotocasa.es/`

### Describe the issue

the uBO counter not working for me in this site. in the logs i can see blocked content.. but the counter in the uBO icon, no appears numbers. 

no problem, in any other website.

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/89948575-a72f8a00-dc26-11ea-807a-14ee41b88d64.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.28.4]

### Settings

- Filter list: https://i.imgur.com/E6aesAu.png

**Comment by gorhill** [comment]
@llacb47 is right.

> i just test with ABP and appears the numbers

From what I gather, ABP will try to find from which page the requests originate -- it's a guest. As a result, if you open two or more pages to the site `https://www.fotocasa.es/` in different tabs, reloading one page will cause the count on all other pages to also go up, despite no changes on these pages, because ABP will attribute the tab-less requests to originates from all tabs which matches the context.

**Comment by gwarser** [comment]
Tested on Slack with `woff*$xmlhttprequest,domain=app.slack.com`.
