### ISSUE TITLE
Ability to remove disable strict blocking buttons from filter block page

### ISSUE THREAD

**Issue by Stolarskis** [uBlockOrigin/uBlock-issues#1243]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Upon attempting to access a site that is on the filter list, I get taken to a page that allows me to unblock that page. Its not possible to disable these buttons via ublock element picker or set custom page to redirect to.

Background:

I'm trying to use ublock origin as a productivity tool as well as an ad blocker. I know that this isn't the main use case for ublock but other options that accomplish this are [considered unsafe](https://adguard.com/en/blog/big-star-labs-spyware.html). (ex: blocksite)

One workaround I tried was to use the element picker mode to disable the button elements. But on ublock pages those settings are disabled.

![ublock issue](https://user-images.githubusercontent.com/31296227/93021871-61fad100-f5b3-11ea-8142-7cbfdd7d4314.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Add site to filter list
2. Attempt to access that site
3. Taken to ublock page that allows temporary unblock where settings to remove elements are disabled.

### Expected behavior:

Ability to disable the unblock buttons or set a page to redirect to.

### Actual behavior:

Take to page that allows to unblock site with one click.

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Chrome  84.0.4147.89 (Official Build) (64-bit)
* Operating System and version: Ubuntu 18.04

**Comment by gorhill** [comment]
I prefer to decline this, I consider this to be [feature creep](https://en.wikipedia.org/wiki/Feature_creep).

**Comment by JayAndCatchFire** [comment]
@gorhill Is there maybe a way to at least remove the "Permanently" button from the page for certain entries? Or maybe an "are you sure" dialog for that option?

My particular use case is that I'm using the strict blocking feature to help me avoid doom scrolling. So websites that trigger me are on my personal filter list. Sometimes I'll look, but I like having that temporary reminder stop me every so often so I can check in with myself and make sure I want to keep browsing that site.

Problem is, I'm on mobile where the buttons are stacked. It's very easy to fat finger it and accidentally hit the "Permanently" button when I wanted the "Temporarily" button. And then it's even more annoying to have to try to remove the newly added rule since that interface isn't the most mobile friendly for portrait screens.

**Comment by pc00per** [comment]
I donno why this isn't a default, since you're blocking sites on your own consent (because of some reasons such as social media addiction or a dangerous site). Those unblock buttons literally doesn't help the owner at all. If he intends to open such pages, then he wouldn't be blocking those sites in the first place.
I quite not found this filter blocking & then unblocking buttons useful at all. We'd rather depend on some private DNS, or systemwide blockers.

**Comment by pc00per** [comment]
> That's not the purpose of strict blocking

It's funny that we call it "strict blocking", which is not the case at all, where you can literally open with a single mouse click.
The purpose of uBO gorhill, is that you developed it to block unwanted stuff on the Internet, which psychologically infers that uBO helps those people, who need those bloat to go away. Same goes to manual filter too.
