### ISSUE TITLE
1.29.3rc0 - the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1246]
In version 1.29.3rc0, the click-to-follow feature does not work with the `easylist-downloads.adblockplus.org` domain, which makes it impossible to connect RU AdList filters, such as: [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin), [RU AdList: BitBlock](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/bitblock.txt&title=RU%20AdList:%20BitBlock), [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters).

**Comment by gorhill** [comment]
When I go to `https://easylist-downloads.adblockplus.org/`, I get a blank page. At what URL are those subscription links?

**Comment by dimisa-RUAdList** [comment]
RUS: RU AdList - `https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt`
BitBlock - `https://easylist-downloads.adblockplus.org/bitblock.txt`
Counters - `https://easylist-downloads.adblockplus.org/cntblock.txt`

**Comment by gorhill** [comment]
Well these are the lists themselves. I can subscribe using the links you posted in your opening comments.

**Comment by dimisa-RUAdList** [comment]
This works for github, but for some reason it doesn't work here:
`https://forums.lanik.us/viewtopic.php?f=102&t=22512`
`http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1`

[GIF](https://imgur.com/QZmr4Vm)

**Comment by gorhill** [comment]
Where the links are hosted is what matters. I will add `forums.lanik.us` as a valid place from which subscription links can be activated.

**Comment by dimisa-RUAdList** [comment]
Ruadlist-topic at forum.ru-board.com is much more popular among uBO-users.

**Comment by gorhill** [comment]
I understand that `forum.ru-board.com` is not a site dedicated to filter lists, so in that case it's best to link to `filterlists.com` to post subscription links, for example <https://filterlists.com/lists/ru-adlist-bitblock>.

**Comment by gorhill** [comment]
Do you have a URL on `forum.ru-board.com` with subscription links?

**Comment by krystian3w** [comment]
> https://filterlists.com/lists/ru-adlist-bitblock 

Added on the table as records, need filter on 2-nd column by "RU" and you should have 22 filter list found.

The sliding sidebar I suppose is no projected to promotion other records filter lists.

**Comment by dimisa-RUAdList** [comment]
At the moment, the url Ruadlist-topic at `forum.ru-board.com`: `http://forum.ru-board.com/topic.cgi?forum=5&topic=50474`

But as soon as the topic reaches the limit of 200 pages, it will receive a new address (with the postscript "part two"). Therefore, the binding to the current address of the topic will lose relevance all the time.

It is not very convenient to link to `filterlists.com`, since there is no filter view in a separate page, and in versions before 1.29.3, connecting filters does not work at all.

It is a pity that the `easylist-downloads.adblockplus.org` domain cannot be made a verification condition.

Probably, after the release of the stable version 1.29.3, I will create a separate topic on `forums.lanik.us`, where links for connecting RU AdList filters will be posted.

**Comment by gorhill** [comment]
I can't find any click-to-subscribe links in there

> there is no filter view in a separate page

Not sure I understand what you are saying. Once you click "Subscribe", you are presented with a view of the filter list content.

> It is a pity that the `easylist-downloads.adblockplus.org` domain cannot be made a verification condition.

The idea is to avoid having to inject the `subscriber.js` content script unconditionally in every page loaded in the browser.

In any case I am experimenting with using the context menu to be able to subscribe to a list when the link matches filter list subscription pattern, and I wanted to test this with `forum.ru-board.com`, but as said I can't find click-to-subscribe links in there.

**Comment by gorhill** [comment]
Ok, I followed the uBlock Origin link and I find click-to-subscribe links in there: <http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1>.

I can subscribe to the lists through the context menu, so I think this could be the netter approach rather than injecting `subscriber.js` in all visited pages.

**Comment by dimisa-RUAdList** [comment]
In the links from the topic header:
`http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1`
`http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=4#1`

In posts:
`http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=2140#17`

**Comment by krystian3w** [comment]
`##a[href^="https://subscribe.adblockplus.org/"]:style(border: 10px solid yellow !important; display: inline-block!important;)`

IMO any link no have `#ffff00` border on phpBB forum.

**Comment by Tabby-cell** [comment]
> In version 1.29.3rc0, the click-to-follow feature does not work with the `easylist-downloads.adblockplus.org` domain, which makes it impossible to connect RU AdList filters, such as: [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin), [RU AdList: BitBlock](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/bitblock.txt&title=RU%20AdList:%20BitBlock), [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters).

**Comment by Tabby-cell** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1246#issue-701352314

**Comment by krystian3w** [comment]
IMO right click menu generate fail block links if somebody try click "subscribe to the list as an emergency" by click `block this element`.

**Comment by gorhill** [comment]
> can generate fail block links

Click-to-subscribe links are rather rare, the context menu entry is present only for when the link is a valid click-to-subscribe link. Anyways, I haven't made a decision for that one solution, but I can tell I am not going back to inject `subscriber.js` in all pages by default.

**Comment by gorhill** [comment]
Another solution is to redirect navigation to `https://subscribe.adblockplus.org/?location=*&title=*` to uBO's subscribe page, maybe even with a warning when the link is not hosted on one of the trusted subscription sites.

**Comment by gwarser** [comment]
`subscribe.adblockplus.org` intentionally does not resolve (`;; ANSWER SECTION:` is empty):

```
[rdk@on ~]$ drill subscribe.adblockplus.org
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 12492
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; subscribe.adblockplus.org.   IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
adblockplus.org.        1800    IN      SOA     ns1.p14.dynect.net. hostmaster.adblockplus.org. 4663 3600 600 604800 1800

;; ADDITIONAL SECTION:

;; Query time: 155 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:30 2020
;; MSG SIZE  rcvd: 108
```

`ublockorigin.github.io`:

```
[rdk@on ~]$ drill ublockorigin.github.io
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 47625
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ublockorigin.github.io.      IN      A

;; ANSWER SECTION:
ublockorigin.github.io. 3600    IN      A       185.199.108.153
ublockorigin.github.io. 3600    IN      A       185.199.111.153
ublockorigin.github.io. 3600    IN      A       185.199.109.153
ublockorigin.github.io. 3600    IN      A       185.199.110.153

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 76 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:57 2020
;; MSG SIZE  rcvd: 104
[rdk@on ~]$ 
```

**Comment by gorhill** [comment]
> `subscribe.adblockplus.org` intentionally does not resolve

Sure, but we have no control over this, this may change in the future.

**Comment by Tabby-cell** [comment]
Skip to content

uBlockOrigin /
uBlock-issues

    Code
    Issues 99
    Pull requests
    Actions
    Wiki
    Security
    Insights

Jump to bottom
1.29.3rc0 - the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain #1246
Open
dimisa-RUAdList opened this issue 2 days ago · 20 comments
Open
1.29.3rc0 - the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain
#1246
dimisa-RUAdList opened this issue 2 days ago · 20 comments
Labels
something to address
Comments
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

In version 1.29.3rc0, the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain, which makes it impossible to connect RU AdList filters, such as: RUS: RU AdList, RU AdList: BitBlock, RU AdList: Counters.
@gorhill gorhill commented 2 days ago

When I go to https://easylist-downloads.adblockplus.org/, I get a blank page. At what URL are those subscription links?
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

RUS: RU AdList - https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt
BitBlock - https://easylist-downloads.adblockplus.org/bitblock.txt
Counters - https://easylist-downloads.adblockplus.org/cntblock.txt
@gorhill gorhill commented 2 days ago •

Well these are the lists themselves. I can subscribe using the links you posted in your opening comment.
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

This works for github, but for some reason it doesn't work here:
https://forums.lanik.us/viewtopic.php?f=102&t=22512
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1

GIF
@gorhill gorhill commented 2 days ago

Where the links are hosted is what matters. I will add forums.lanik.us as a valid place from which subscription links can be activated.
gorhill added a commit to gorhill/uBlock that referenced this issue 2 days ago
@gorhill
Add `forums.lanik.us` as a valid location for subscription links
bd949ca
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

Ruadlist-topic at forum.ru-board.com is much more popular among uBO-users.
@gorhill gorhill commented yesterday

I understand that forum.ru-board.com is not a site dedicated to filter lists, so in that case it's best to link to filterlists.com to post subscription links, for example https://filterlists.com/lists/ru-adlist-bitblock.
@gorhill gorhill commented yesterday

Do you have a URL on forum.ru-board.com with subscription links?
@dimisa-RUAdList dimisa-RUAdList commented yesterday

At the moment, the url Ruadlist-topic at forum.ru-board.com: http://forum.ru-board.com/topic.cgi?forum=5&topic=50474

But as soon as the topic reaches the limit of 200 pages, it will receive a new address (with the postscript "part two"). Therefore, the binding to the current address of the topic will lose relevance all the time.

It is not very convenient to link to filterlists.com, since there is no filter view in a separate page, and in versions before 1.29.3, connecting filters does not work at all.

It is a pity that the easylist-downloads.adblockplus.org domain cannot be made a verification condition.

Probably, after the release of the stable version 1.29.3, I will create a separate topic on forums.lanik.us, where links for connecting RU AdList filters will be posted.
@uBlock-user uBlock-user added the something to address label yesterday
@gorhill gorhill commented yesterday

I can't find any click-to-subscribe links in there

    there is no filter view in a separate page

Not sure I understand what you are saying. Once you click "Subscribe", you are presented with a view of the filter list content.

    It is a pity that the easylist-downloads.adblockplus.org domain cannot be made a verification condition.

The idea is to avoid having to inject the subscriber.js content script unconditionally in every page loaded in the browser.

In any case I am experimenting with using the context menu to be able to subscribe to a list when the link matches filter list subscription pattern, and I wanted to test this with forum.ru-board.com, but as said I can't find click-to-subscribe links in there.
@gorhill gorhill commented yesterday

Ok, I followed the uBlock Origin link and I find click-to-subscribe links in there: http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1.

I can subscribe to the lists through the context menu, so I think this could be the netter approach rather than injecting subscriber.js in all visited pages.
@dimisa-RUAdList dimisa-RUAdList commented yesterday

In the links from the topic header:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=4#1

In posts:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=2140#17
@krystian3w krystian3w commented yesterday

##a[href^="https://subscribe.adblockplus.org/"]:style(border: 10px solid yellow !important; display: inline-block!important;)

IMO any link no have #ffff00 border on phpBB forum.
This comment was marked as disruptive content.
Show comment
This comment was marked as disruptive content.
Show comment
@krystian3w krystian3w commented yesterday •

IMO right click menu can generate fail block links - if somebody try click "subscribe to the list as an emergency" by click block this element.

Addons can make a horizontal line, so it would have to be able to generate one in the uBO right click menu do generate less misclicks.
@gorhill gorhill commented yesterday

    can generate fail block links

Click-to-subscribe links are rather rare, the context menu entry is present only for when the link is a valid click-to-subscribe link. Anyways, I haven't made a decision for that one solution, but I can tell I am not going back to inject subscriber.js in all pages by default.
@gorhill gorhill commented yesterday •

Another solution is to redirect navigation to https://subscribe.adblockplus.org/?location=*&title=* to uBO's subscribe page, maybe even with a warning when the link is not hosted on one of the trusted subscription sites.

Edit: Actually, if I am going to go that route, probably best to use a domain which is under uBO's control, such as https://ublockorigin.github.io/subscribe/?....
@gwarser gwarser commented yesterday

subscribe.adblockplus.org intentionally does not resolve (;; ANSWER SECTION: is empty):

[rdk@on ~]$ drill subscribe.adblockplus.org
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 12492
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; subscribe.adblockplus.org.   IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
adblockplus.org.        1800    IN      SOA     ns1.p14.dynect.net. hostmaster.adblockplus.org. 4663 3600 600 604800 1800

;; ADDITIONAL SECTION:

;; Query time: 155 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:30 2020
;; MSG SIZE  rcvd: 108

ublockorigin.github.io:

[rdk@on ~]$ drill ublockorigin.github.io
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 47625
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ublockorigin.github.io.      IN      A

;; ANSWER SECTION:
ublockorigin.github.io. 3600    IN      A       185.199.108.153
ublockorigin.github.io. 3600    IN      A       185.199.111.153
ublockorigin.github.io. 3600    IN      A       185.199.109.153
ublockorigin.github.io. 3600    IN      A       185.199.110.153

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 76 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:57 2020
;; MSG SIZE  rcvd: 104
[rdk@on ~]$ 

@gorhill gorhill commented yesterday

    subscribe.adblockplus.org intentionally does not resolve

Sure, but we have no control over this, this may change in the future.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one assigned
Labels
something to address
Projects
None yet
Milestone
No milestone
Linked pull requests

Successfully merging a pull request may close this issue.
None yet
Notifications
Customize

You’re receiving notifications because you commented.
6 participants
@gorhill
@gwarser
@dimisa-RUAdList
@uBlock-user
@krystian3w
@Tabby-cell

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

    Contact GitHub
    Pricing
    API
    
https://www.linkedin.com/profinder/projects/15195193370?trk=push

Skip to content

uBlockOrigin /
uBlock-issues

    Code
    Issues 99
    Pull requests
    Actions
    Wiki
    Security
    Insights

Jump to bottom
1.29.3rc0 - the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain #1246
Open
dimisa-RUAdList opened this issue 2 days ago · 20 comments
Open
1.29.3rc0 - the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain
#1246
dimisa-RUAdList opened this issue 2 days ago · 20 comments
Labels
something to address
Comments
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

In version 1.29.3rc0, the click-to-follow feature does not work with the easylist-downloads.adblockplus.org domain, which makes it impossible to connect RU AdList filters, such as: RUS: RU AdList, RU AdList: BitBlock, RU AdList: Counters.
@gorhill gorhill commented 2 days ago

When I go to https://easylist-downloads.adblockplus.org/, I get a blank page. At what URL are those subscription links?
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

RUS: RU AdList - https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt
BitBlock - https://easylist-downloads.adblockplus.org/bitblock.txt
Counters - https://easylist-downloads.adblockplus.org/cntblock.txt
@gorhill gorhill commented 2 days ago •

Well these are the lists themselves. I can subscribe using the links you posted in your opening comment.
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

This works for github, but for some reason it doesn't work here:
https://forums.lanik.us/viewtopic.php?f=102&t=22512
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1

GIF
@gorhill gorhill commented 2 days ago

Where the links are hosted is what matters. I will add forums.lanik.us as a valid place from which subscription links can be activated.
gorhill added a commit to gorhill/uBlock that referenced this issue 2 days ago
@gorhill
Add `forums.lanik.us` as a valid location for subscription links
bd949ca
@dimisa-RUAdList dimisa-RUAdList commented 2 days ago

Ruadlist-topic at forum.ru-board.com is much more popular among uBO-users.
@gorhill gorhill commented yesterday

I understand that forum.ru-board.com is not a site dedicated to filter lists, so in that case it's best to link to filterlists.com to post subscription links, for example https://filterlists.com/lists/ru-adlist-bitblock.
@gorhill gorhill commented yesterday

Do you have a URL on forum.ru-board.com with subscription links?
@dimisa-RUAdList dimisa-RUAdList commented yesterday

At the moment, the url Ruadlist-topic at forum.ru-board.com: http://forum.ru-board.com/topic.cgi?forum=5&topic=50474

But as soon as the topic reaches the limit of 200 pages, it will receive a new address (with the postscript "part two"). Therefore, the binding to the current address of the topic will lose relevance all the time.

It is not very convenient to link to filterlists.com, since there is no filter view in a separate page, and in versions before 1.29.3, connecting filters does not work at all.

It is a pity that the easylist-downloads.adblockplus.org domain cannot be made a verification condition.

Probably, after the release of the stable version 1.29.3, I will create a separate topic on forums.lanik.us, where links for connecting RU AdList filters will be posted.
@uBlock-user uBlock-user added the something to address label yesterday
@gorhill gorhill commented yesterday

I can't find any click-to-subscribe links in there

    there is no filter view in a separate page

Not sure I understand what you are saying. Once you click "Subscribe", you are presented with a view of the filter list content.

    It is a pity that the easylist-downloads.adblockplus.org domain cannot be made a verification condition.

The idea is to avoid having to inject the subscriber.js content script unconditionally in every page loaded in the browser.

In any case I am experimenting with using the context menu to be able to subscribe to a list when the link matches filter list subscription pattern, and I wanted to test this with forum.ru-board.com, but as said I can't find click-to-subscribe links in there.
@gorhill gorhill commented yesterday

Ok, I followed the uBlock Origin link and I find click-to-subscribe links in there: http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1.

I can subscribe to the lists through the context menu, so I think this could be the netter approach rather than injecting subscriber.js in all visited pages.
@dimisa-RUAdList dimisa-RUAdList commented yesterday

In the links from the topic header:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=4#1

In posts:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=2140#17
@krystian3w krystian3w commented yesterday

##a[href^="https://subscribe.adblockplus.org/"]:style(border: 10px solid yellow !important; display: inline-block!important;)

IMO any link no have #ffff00 border on phpBB forum.
This comment was marked as disruptive content.
Show comment
This comment was marked as disruptive content.
Show comment
@krystian3w krystian3w commented yesterday •

IMO right click menu can generate fail block links - if somebody try click "subscribe to the list as an emergency" by click block this element.

Addons can make a horizontal line, so it would have to be able to generate one in the uBO right click menu do generate less misclicks.
@gorhill gorhill commented yesterday

    can generate fail block links

Click-to-subscribe links are rather rare, the context menu entry is present only for when the link is a valid click-to-subscribe link. Anyways, I haven't made a decision for that one solution, but I can tell I am not going back to inject subscriber.js in all pages by default.
@gorhill gorhill commented yesterday •

Another solution is to redirect navigation to https://subscribe.adblockplus.org/?location=*&title=* to uBO's subscribe page, maybe even with a warning when the link is not hosted on one of the trusted subscription sites.

Edit: Actually, if I am going to go that route, probably best to use a domain which is under uBO's control, such as https://ublockorigin.github.io/subscribe/?....
@gwarser gwarser commented yesterday

subscribe.adblockplus.org intentionally does not resolve (;; ANSWER SECTION: is empty):

[rdk@on ~]$ drill subscribe.adblockplus.org
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 12492
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; subscribe.adblockplus.org.   IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
adblockplus.org.        1800    IN      SOA     ns1.p14.dynect.net. hostmaster.adblockplus.org. 4663 3600 600 604800 1800

;; ADDITIONAL SECTION:

;; Query time: 155 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:30 2020
;; MSG SIZE  rcvd: 108

ublockorigin.github.io:

[rdk@on ~]$ drill ublockorigin.github.io
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 47625
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ublockorigin.github.io.      IN      A

;; ANSWER SECTION:
ublockorigin.github.io. 3600    IN      A       185.199.108.153
ublockorigin.github.io. 3600    IN      A       185.199.111.153
ublockorigin.github.io. 3600    IN      A       185.199.109.153
ublockorigin.github.io. 3600    IN      A       185.199.110.153

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 76 msec
;; SERVER: 192.168.8.1
;; WHEN: Tue Sep 15 17:48:57 2020
;; MSG SIZE  rcvd: 104
[rdk@on ~]$ 

@gorhill gorhill commented yesterday

    subscribe.adblockplus.org intentionally does not resolve

Sure, but we have no control over this, this may change in the future.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one assigned
Labels
something to address
Projects
None yet
Milestone
No milestone
Linked pull requests

Successfully merging a pull request may close this issue.
None yet
Notifications
Customize

You’re receiving notifications because you commented.
6 participants
@gorhill
@gwarser
@dimisa-RUAdList
@uBlock-user
@krystian3w
@Tabby-cell

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

**Comment by dimisa-RUAdList** [comment]
uBlock Origin development build 1.30.1.0
Google Chrome 85.0.4183.121
https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

Disappears "+"
As a result, the filter is not activated.
[Gif](https://imgur.com/wMvkzkp)

**Comment by krystian3w** [comment]
`%2B`

<a href="https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&amp;title=RU%20AdList%20for%20uBlock%20Origin" rel="nofollow">RU AdList for uBlock Origin</a>

`[RU AdList for uBlock Origin](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&amp;title=RU%20AdList%20for%20uBlock%20Origin)`

**Comment by dimisa-RUAdList** [comment]
Ok, changed.

**Comment by krystian3w** [comment]
At least until the decoding is improved.

**Comment by gorhill** [comment]
> At least until the decoding is improved.

What's there to improve?

The `+` character *must* be percent-encoded in that context.

**Comment by krystian3w** [comment]
But any browser  convert `+` to `%2B`, also on wiki nobody recommend convert url to or built own link uBO factory:

```js
https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fadvblock%252Bcssfixes.txt
```

`https://adblockplus.org/abp_linkfactory`

**Comment by gorhill** [comment]
The link is parsed using the [browser's own URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), so if the browser's own API has an issue parsing the link, the best explanation is that the URL is not properly crafted.

**Comment by krystian3w** [comment]
Apache like `+` in names.

**Comment by gorhill** [comment]
`+` in path is fine, `+` in query value is converted to space, that was the issue, query value must be encoded using [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).
