### ISSUE TITLE
Improper support of IPv6 addresses in static filter `domain=` option

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1249]
### Description

Originally report as comment at <https://github.com/uBlockOrigin/uBlock-issues/issues/1134#issuecomment-693152352>:

>It looks like IPv6 addresses are marked as invalid inside `$domain` option, is this intended? The rule is compiled, but I haven't tested whether it actually works. 
> ![image](https://user-images.githubusercontent.com/7283682/93289474-ab0d7980-f79b-11ea-937a-73649a98823d.png)

Test case: `||example.com^$domain=::1`

The syntax highlighter reports the `domain=` option value `::1` as invalid, though uBO internally stores the value as a valid hostname to match against the current context. Essentially, this causes the creation of a filter which will never match.

### To do

Support IPv6 addresses in `domain=` option in syntax highlighter.

IPv6 addresses must be surrounded by square bracket, i.e. `[::1]`, as this is how the browser reports them through its API; hence the valid filter would be `||example.com^$domain=[::1]`.

**Comment by jspenguin2017** [comment]
It appears that `||example.com^$domain=[::1]` is completely rejected and does not create a filter rule internally. I initially thought that it should be `::1` (since that created a filter rule internally) but I guess I was wrong. Issue was first raised by Ryan on Slack: 
![image](https://user-images.githubusercontent.com/7283682/93403601-37c04200-f845-11ea-80ca-9b90bd92621c.png)

**Comment by sn260591** [comment]
What about a fix for dynamic filter syntax highlighting?

![_](https://user-images.githubusercontent.com/10724977/93706131-f6bd7b80-fb2b-11ea-9061-9b6764a52fe7.png)
