### ISSUE TITLE
Cosmetic Exception filter disabling?

### ISSUE THREAD

**Issue by nl-n** [uBlockOrigin/uBlock-issues#1322]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I am aware of important/badfilter etc for static filters, however none of that seems to apply to cosmetic filters. 

As an example: a 3rd party filters list adds an exception rule of the form '<domain>#@##<some-element>'
Now there seems to be nothing i can do on my side to disable/override that, adding the same rule without '@' has no effect.
Obviously dynamic filtering is not an option.

I believe anything in "My Filters" should trump EVERYTHING else, otherwise its purpose is somewhat...limited.

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

n/a

### Expected behavior:

Exception in 3rd party list is ignored/overriden by locally defined filter.

### Actual behavior:

Locally defined filter is overriden by 3rd party.

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox ESR 78.4.0
* Operating System and version: Winblows 10

**Comment by uBlock-user** [comment]
then append a invalid element token such as `important` after the element. eg `##[selector],important`

**Comment by nl-n** [comment]
> 
> 
> then append a invalid element token such as `important` after the element. eg `##[selector],important`

Could you please clarify what you mean? i have already tried adding ,important after the element, and it changed nothing.

**Comment by uBlock-user** [comment]
> Locally defined filter is overriden by 3rd party.

Post a specific example

**Comment by uBlock-user** [comment]
> Exception in 3rd party list is ignored/overriden by locally defined filter.

Post a specific example, the vague description does not help.

**Comment by nl-n** [comment]
Ok, so:

say a 3rd party filterlist (adguard/easylist for example) have a filter such as:
`somewebsite.com#@##subscribe-button`
in their list.

But i want to actually see that element, so i go to my filters, and i add: `somewebsite.com###subscribe-button`

Nothing changes, and the log shows it's still being filtered, i tried: `somewebsite.com###subscribe-button,important`
but that also did nothing.

I hope that's clear enough :)
I would really prefer not to have to disable a whole list (and a pretty important one to me) just for 1 line...

**Comment by uBlock-user** [comment]
> i tried: somewebsite.com###subscribe-button,important
but that also did nothing.

What did the logger show this time ? and post the filter which was shown here.

**Comment by nl-n** [comment]
Not sure what i should copy/paste so i'll just stick a couple screenshots here:

![screen1](https://user-images.githubusercontent.com/37713974/98080581-8cf3f980-1e6d-11eb-8739-848fe591e100.png)
![screen2](https://user-images.githubusercontent.com/37713974/98080585-8ebdbd00-1e6d-11eb-832f-a5411af61af2.png)

**Comment by uBlock-user** [comment]
As per the **second** screenshot, your filter is getting applied and I just tested this on my setup with Fanboy Annoyance/Social activated on a youtube channel and it works as expected.

`youtube.com###subscribe-button,important` helps bypass the exception(`#@##`) filter and successfully hides the **Subscribe** button for e.g `https://www.youtube.com/channel/UCPD_bxCRGpmmeQcbe2kpPaA`

Make sure all other extensions are disabled when you're testing.

**Comment by nl-n** [comment]
You're right, 
not sure what was causing the button to stay (it does seem to be working after refreshing firefox).
I just saw the yellow-highlighted entry in the log and assumed the local filter was being ignored, my bad.

Thank you for the help though, very much appreciated.

**Comment by uBlock-user** [comment]
> not sure what was causing the button to stay 

This doesn't happen if you added `###subscribe-button,importan`t via Picker. Anyways, next time provide full Steps To Reproduce and if you can't do that, then post the issue on reddit, which is the dedicated help section, while GitHub is only provable issues with details Steps To Reproduce along with filling the entire template as asked.

**Comment by krystian3w** [comment]
Try `youtube.com###subscribe-button#subscribe-button` - based on https://github.com/uBlockOrigin/uBlock-issues/issues/388#issuecomment-456046037

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/388

**Comment by felix-22** [comment]
Also a partial duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/79 (of https://github.com/uBlockOrigin/uBlock-issues/issues/79#issuecomment-397890891 + all the subsequent ones)

<hr>

I've encountered a similiar issue, I've found and added a third-party filter list which has turned out to contain several bad/unwanted cosmetic filters which break some sites: `##.ads`, `##div[class*="ads"]`. Now, there seems to be no way to disable `##.ads` without disabling similiar filters on other filter lists (for example EasyList):
-  `#@#.ads` will disable EasyList's:
`1sale.com,7billionworld.com,9jaflaver.com,achieveronline.co.za,canstarblue.co.nz,chordfrenzy.com,climatechangenews.com,cryptonomist.ch,dallasobserver.com,energyforecastonline.co.za,esports.com,eventcinemas.co.nz,flashx.tv,furaffinity.net,geo.tv,govtrack.us,gramfeed.com,houstonpress.com,idiva.com,indiatimes.com,inspirock.com,knowyourmeme.com,marinetraffic.com,mb.com.ph,mehrnews.com,meta-calculator.com,mini-ielts.com,miningprospectus.co.za,mugshots.com,myfitnesspal.com,nativeplanet.com,nbc.na,news.nom.co,nsfwyoutube.com,roadaheadonline.co.za,russia-insider.com,russian-faith.com,savevideo.me,sddt.com,servicepublication.co.za,sgcarmart.com,shipyearonline.co.za,stars-portraits.com,straitstimes.com,strawpoll.me,tcm.com,tech2.com,tehrantimes.com,tellerreport.com,thecatholicuniverse.com,thejakartapost.com,thelakewoodscoop.com,themalaysianinsider.com,thenews.com.pk,theprojectmanager.co.za,thestar.com.my,viamichelin.com,viamichelin.ie,vidstreaming.io,wallpaper.com,y8.com,yummy.ph##.ads`

- `~brokensite.com##.ads` - adding every particular broken site is not sufficient in the long run, as EasyList' filter clearly shows and proves that the filter should be "specific, with domains added" and not "generic, with domains excluded", otherwise an user will have to spend the rest of life adding exceptions every X days...

**Comment by u-RraaLL** [comment]
> I've encountered a similiar issue, I've found and added a third-party filter list which has turned out to contain several bad/unwanted cosmetic generic filters which break some sites: `##.ads`, `##div[class*="ads"]`. Now, there seems to be no way to disable `##.ads` without disabling similiar filters on other filter lists (for example EasyList)

Isn't that what `ghide` is for?

**Comment by felix-22** [comment]
I forgot about `ghide` in my previous comment, but how is it supposed to be better than `#@#.ads` as a generic exception? Even worse because `@@*$ghide`:
  - will disable **all** generic cosmetic filters on all sites, which is not what an user needs in this case
  - there is "Ignore generic cosmetic filters" already if one ever wants to disable all generic cosmetic filters on all sites...
  - causes side-effects [multiple big ad placeholders caused by generichide]:
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+generichide+author%3Afelix-22+
  - "isn't that what `ghide` is for?" Doesn't seem so, it's to be used as anti-adblock solution for particular specific sites, not as an generic exception filter applied to all sites...
  `https://blog.adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock`

Also `brokensite.com*$ghide` worse even as a specific solution, than `~brokensite.com##.ads`, as the `ghide` will disable **all** generic cosmetic filters...not mentioning an user is not interested in specific solutions in this case, for the reasons already provided in the previous comment.

**Comment by gorhill** [comment]
Well if a list contains "several bad/unwanted cosmetic generic filters" causing you issue, then it's a low quality list which you should not subscribe to -- that's the solution.

**Comment by felix-22** [comment]
Yeah, I am aware:
- I already removed many third-party filter lists in the past due to low quality and breaking many sites
- however I still use several other lists and decided to keep them, as they turned out to be reasonable, after fixing/fine-tuning them 
- anyway I'll just choose to host temporarily a fixed version of the list on a local server with bad generic cosmetic filters removed to give the list a try/chance and see whether it will deserve to stay after fine-tuning/fixing in a long run, as some other parts of the list might turn out to be useful

In any case I've rather wanted to share experiences, as as a power user I use many filter lists, this is not necessarily to be considered a feature request, you do what you want with it.
