### ISSUE TITLE
badfilter for scriptlet

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#1339]
Some of the sheets that I use have disabled scriptlets that are inappropriate for me, like this

`example.com#@#+js(nobab)`

I searched and found a thread about CSS https://github.com/uBlockOrigin/uBlock-issues/issues/1322 but the exception of the already excluded scriptlet I did not find.

So how about adding a badfilter flag. Something like `example.com##+js(nobab),important`

**Comment by gorhill** [comment]
I don't undestand what you are asking. What is wrong with using an exception?

**Comment by gwarser** [comment]
Some list already has exception and he want this filter to be active.

**Comment by bogachenko** [comment]
The fact that it does not suit me. I want to cancel the exception because I don't think the exception is appropriate for this site. And in order not to write to the developer/s of this/these filters, I just want to add the `important` flag and forget about it.

**Comment by gorhill** [comment]
> it does not suit me

I don't work for personal requests, I work toward to add feature that benefits all, when someone makes a convincing case. You provide not even actual cases.

**Comment by bogachenko** [comment]
Well, if someone needed to add an important flag for CSS, then and someone will need to add an important flag for scriptlets. After all, this is logical, you add a rule, someone adds an exception for it, you don't like it and you cancel it. You take control of your filters.

You don’t want to add / you don’t need it, oke.

**Comment by krystian3w** [comment]
`aopr` also support this?

like:

`money.pl#@#(aopr, wp_color_consent)`
`money.pl##(aopr, wp_color_consent, _)`

**Comment by gorhill** [comment]
It should, it's not a per-scriptlet behavior, it's a generic way to work around exceptions -- if the scriptlet's string inside `+js(...)` is not literally equal to one being excepted, than it won't be excepted.

**Comment by krystian3w** [comment]
OK, because there is a problem with the operation of this filter as AdGuard will do with its script conversions to:

```css
money.pl#%#//scriptlet('abort-on-property-read', 'wp_color_consent')
```

or


```js
money.pl#%#AG_abortOnPropertyRead('wp_consent_color'); 
```

**Comment by gorhill** [comment]
My comment is valid for how uBO works, I don't know how AdGuard works so whatever I said above shouldn't be assumed to work with AdGuard.

**Comment by keczuppp** [comment]
As here https://github.com/AdguardTeam/AdguardFilters/issues/67537#issuecomment-727549743

- unlike uBO's `abort-on-property-read`, which supports only [SINGLE ARGUMENT](https://github.com/gorhill/uBlock/wiki/Resources-Library#aoprjs-)
AG equivalent does support [2 ARGUMENTS](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-abort-on-property-read), the second one is `stack` 
- that's why `money.pl##+js(abort-on-property-read, wp_consent_color, _)` won't work as expected in AG, it will run correctly but won't have desired effect - will not hide the cookie message, because there is no `_` in the property's `stack`
- so you have to skip `stack` by leaving it empty, and add `_` as a another (3rd) parameter, this will bypass the exception filter and hide the cookie message: `money.pl##+js(abort-on-property-read, wp_consent_color, ,_)`

**Comment by Yuki2718** [comment]
Doesn't matter, you can use `!#if` directive _intelligently_ - the fact AG doesn't support the directive except for browser extension is also not really an issue.
