### ISSUE TITLE
HTML filter is treated as legit filter on the picker (even on Chromium)

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1363]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

IIRC HTML filters have been invalid on the picker, but in the current version it's accepted and you can actually create HTML filters via picker (even on Chromium if it matters).

<details>
<summary>Screenshot</summary>

![html-filter](https://user-images.githubusercontent.com/58900598/100463537-58432d00-310f-11eb-8a88-f54ec90f3e47.png)

</details>

### A specific URL where the issue occurs

Anywhere, but ex. `https://github.com/`.

### Steps to Reproduce

1. Choose any elements on the picker
2. Insert `^` after `##`
3. The filter is valid, and you can create the filter.

### Expected behavior:

HTML filter should be invalid (or at least valid only if all the condition are met for the filter to be valid, but checking that won't be the job of the picker).

### Actual behavior:

Described

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Chrome 87.0.4280.66
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
> IIRC HTML filters have been invalid on the picker

It's valid in 1.30.6. I don't remember minding HTML filters being created from the picker. Why do you want them to be invalid?

**Comment by Yuki2718** [comment]
@gorhill It doesn't work on Chromium, and even on Firefox it doesn't work if encoding is not supported or if the chosen element was dynamically generated (not in the response). But sure it requires user to manually add `^`.

**Comment by keczuppp** [comment]
- I noticed a similiar thing, not sure whether is should be considered an issue / a bug  / or an enhancement... 
- also perhaps it is not worth creating a separate issue, so I'll just post it here:

In uBO Element Picker, if the user wants to use uBO Element Picker to create a filter compatible also with ABP:
- this filter is treated as valid: `##span:-abp-contains(Insights)` wherein it should be treated as invalid, because:
a) such filters work only in uBO, but not in ABP, because ABP cosmetic extended filters require `?` after first `#`
b) not so good idea to create filters with wrong / nonexistent syntax, syntax of such filters is some kind of a hybrid / a mix of uBO and ABP syntax, and just because uBO can technically support it, does not necessarily mean it should be supported
- this filter is treated as invalid: `#?#span:-abp-contains(Insights)` wherein it should be treated as valid,
furthermore logically if the Picker allows already `:-abp-contains` and `:-abp-has` as valid it should treat `#?` as valid as well

Additionaly, to achieve the above changes, there can be additional easy parsing added to the Element Picker:
- if the filter contains `:-abp-contains` or `:-abp-has`, 
automatically insert `?` after first `#`,
or mark filter as invalid until the user adds missing `?`
- if the user's filter begins with `#?`, 
mark the filter as invalid until the user adds either `:-abp-contains` or `:-abp-has` into the filter

<details not-open>
<summary>screenshoots</summary>



![](https://user-images.githubusercontent.com/74409207/100477663-4189df80-30e9-11eb-85c6-5a0db1d64b6a.png)

![](https://user-images.githubusercontent.com/74409207/100476250-5feddc00-30e5-11eb-9f81-50cbe812360d.png)
</details>

Well, the same issue / bug / enhancement can be with AdGuard syntax filters.. @bug-rules WDYT

**Comment by bug-rules** [comment]
AdGuard no recommend use `#?#` for 3-party aproved lists, Own technology add needed `?` by `FiltersRegistry` project.

**Comment by gwarser** [comment]
@keczuppp WTH? For `{}` syntax for style, uBO requires `#$#`. https://www.reddit.com/r/uBlockOrigin/comments/juv6fg/is_black_bar_at_the_bottom_of_the_screen_while/gcg050x/ (I checked). Some inconsistency.

**Comment by gorhill** [comment]
@gwarser `#?#` is used by both AdGuard and ABP and means different things for each. Easier to just drop the `?` then to try to be too smart by overcomplicating of code with all the consequences of doing so. People using uBO to create ABP filters is not an unlikely  case which I am interested to invest time to solve.

**Comment by krystian3w** [comment]
> HTML filters have been invalid 

this need view page from `view-source:` so few elements maybe are added dynamic by js, when html filtering may no help (as long you abort these dynamic changes on page).

**Comment by garry-ut99** [comment]
Another similiar case, this time there is a difference, as:
- this is not about uBO Element Picker, the element picker doesn't allow such filter `#@?#` nor generally any other exeption filter like `#@#` and it's OK
- this is not about uBO Logger neither, as the logger creates `#@#` exception for `#?#` filter instead of `#@?#` and it's OK
- however still if an user adds such exception filter to My Filters or if the filter is present on any filter list, uBO will accept it as a valid filter, the example exception filter: 
`goodie.pl#@?#body > div[class]:not(id):last-of-type:-abp-has(a[href="/ochrona-danych"])`
but such filter won't work in ABP because it's invalid in ABP, because for some weird reasons (simplicity or compatibility with AG?) ABP forces removal of `?` when making exceptions for `#?#`: bad `#@?#`, good `#@#`
- there has been a case when someone manually created the above filter exception with `?` and it was working in uBO so he was assuming it will work for ABP as well, so he put it in his comment https://github.com/MajkiIT/polish-ads-filter/issues/18146#issuecomment-742489581 as a solution for other people
- other people have started to copy & pase the "invalid" filter and these who using ABP have begin to complaining it's not working in ABP https://github.com/MajkiIT/polish-ads-filter/issues/18146#issuecomment-742536892
- what I want to point is that when uBO accepts an invalid ABP filter `#@?#` as a valid filter, it might cause the "invalid" filter to be copy & pasted by other users and spread over the internet and then people complaining the filter is not working (in ABP) which doesn't seem good
- personally if I would be a ABP developer I would stay at `#@?#` exception for `#?#`, just like `#@#` for `##`, just simply add `@` after first `#`, but for some unknown reason ABP devs went `#@#` route even for `#?#` filters (simplicity or compatibility with AG?), so perhaps uBO should adapt to it completely, and not only when creating an exception for `#?#` in the logger, I mean uBO should dicard such filter `#@?#` as invalid

**Comment by bug-rules** [comment]
> reasons (simplicity or compatibility with AG?)
> filters (simplicity or compatibility with AG?)

AdGuard need this variant to disable cosmetic procedural filter:
```
example.org##div > h1:first-child:contains(Domain)
example.org#@?#div > h1:first-child:contains(Domain)
```

Addon no support translation `#@#` if found ExtendedCSS selector - I can't test how it works for FiltersRegistry compiler or in app for Windows/macOS/Android.

**Comment by gorhill** [comment]
> HTML filter should be invalid

I disagree with this, if the filter has valid syntax, it should not be reported as invalid. There is no really good reason to create an obstacle to prevent people from creating HTML filters -- the picker is a tool, and whoever is advanced enough to feed it HTML filter syntax should be assumed to know enough about whether the filter they create will be enforced or not ultimately.

**Comment by krystian3w** [comment]
uBo Dev may no longer allow drop "?" for `:-abp-has()` (reddish background).

**Comment by krystian3w** [comment]
I think picker no longer allow html filtering.
