### ISSUE TITLE
Can't load the images

### ISSUE THREAD

**Issue by dikiaap** [uBlockOrigin/uBlock-issues#1365]
### URL(s) where the issue occurs

`https://news.ycombinator.com/`

### Describe the issue

 
I'm currently using v1.31.0 and can't load the images on all websites probably due this filter: `|https://*:$image,domain=centrum-dramy.pl|hentai-online.pl`
I have updated all the filter lists but still no luck.

### Screenshot(s)

![1](https://user-images.githubusercontent.com/8542502/100491999-eabcee00-315a-11eb-8503-9c5a6c1dbd66.png)
![2](https://user-images.githubusercontent.com/8542502/100492001-edb7de80-315a-11eb-973d-9542db2126ef.png)
![3](https://user-images.githubusercontent.com/8542502/100492003-ef81a200-315a-11eb-8986-25d248cfa474.png)

### Versions

- Browser/version: Chrome
- uBlock Origin version: 1.31.0

**Comment by gorhill** [comment]
As far as I can tell, it seems uBO was still using the old compiled data of one or more lists.

When the magic version numbers for compiled and selfie data changes, uBO remove all the entries for compiled and selfie data, so when it tries to load the list later on, it won't find these entries and consequently is forced to re-compiled all the lists.

I am looking at the launch code, and I believe it's possible there is a small time window in which the removal of the no-longer-valid compiled and selfie entries is undone. I will add code to work around this, and also to report an error to the console if ever this happens. With Chromium-based browser, errors are registered in a permanent manner until cleared by the user. So if ever we sport the error reported at the console, this will confirm that there was a timing issue.

I did try to reproduce by changing compiled/selfie magic numbers, but no error were reported at the console on my side. Please report here if ever you stumble onto such error. Installing 1.31.0 then post 1.31.1b6 test this, and maybe leaving the time for 1.31.0 to create a selfie might help reproduce the issue if ever there is indeed a timing issue.

**Comment by gorhill** [comment]
I will post here instances similar to the issue here:
- https://twitter.com/codingcatgirl/status/1332641187648446464

**Comment by uBlock-user** [comment]
Another incident at https://github.com/uBlockOrigin/uAssets/issues/8260#issuecomment-736023369

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1371

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/101042380-2258db00-354b-11eb-92f9-237d60492f0c.png)

The filter which matches the closest what I see in the screenshots of those who suffered the issue is found in EasyList:

    |https://$image,media,script,third-party,domain=~feedback.pornhub.com|~feedback.pornhubthbh7ap3u.onion|pornhub.com|pornhubthbh7ap3u.onion|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com

Except that `image,script,third-party` seemed to have become `stylesheet,~third-party`.

If uBO 1.31.0 was to read the compiled filter with version 1.30.6, then `image` would become `stylesheet` and `media` would become `script`. Also, `first-party` would become `third-party`. Se this definitely confirms that for some people, uBO 1.31.0 is being fed compiled format of 1.30.6.

It's seems to still be quite a rare occurrence given the user base, and I still do not see how this can happen in the launch code ([this is where](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/start.js#L189-L202) uBO removes the no longer valid compiled data), so at this point I think it's possible that sometimes something is not working properly with the storage API.

**Comment by keczuppp** [comment]
Another weird thing on the screenshoot is that `/googleads/*$domain=~github.com` wrongly matches and blocks domain `https://translate.googleapis.com/translatestatic/`:
- it's not blocked on my end
- on the screenshoot, there is a dark-red font background highlight missing, which should show which part of the request has been matched by the filter, what proves that the filter doesn't match any part of the domain, but as seen the request is still being blocked...

![6565656565](https://user-images.githubusercontent.com/74409207/101056333-286eac00-358b-11eb-8cf9-ce659a067186.png)

**Comment by gorhill** [comment]
> `/googleads/*$domain=~github.com` filter wrongly matches

I am not able to explain this one.

**Comment by gwarser** [comment]
Are tokens 7 characters long? `googlea`?

**Comment by keczuppp** [comment]
The same happens on screenshoot from the first comment: 
- filter `|https://*:` doesn't match any of the requests because the requests to be matched should contain port number after the domain, to be matched, like `:80`, for example : 
`https://www.news.ycombinator.com:80/` and not 
`https://www.news.ycombinator.com/`
- it's also proved by matching parts of the requests are not highlighted with dark-red font background as well, 
because there is nothing to match...but somehow the requests are still being blocked

**Comment by gorhill** [comment]
> Are tokens 7 characters long? `googlea`?

Good thinking, I had forgotten about this. But then, the pattern still has to match ultimately. I should run 1.30.6 then disable the compiled data being thrown away in 1.31.0 and see if I can reproduce.

**Comment by gorhill** [comment]
Ok I can reproduce bad filtering as seen in the screenshots when I comment out the removal of the cached compiled filter lists, at [this line](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/start.js#L191):

![a](https://user-images.githubusercontent.com/585534/101070902-ee40e280-3569-11eb-8b49-8dfe5874055d.png)

Also as a consequence, I also see errors thrown in uBO's console, so this could cause the other unexplained block filters; in short uBO is quite broken.

I was surprised that just commenting out the removal of compiled filter lists would still cause an issue, because the test at [this line](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/storage.js#L737) should have ensured that the compiled lists are not going to be used.

However I overlooked that uBO makes another try at loading the compiled list at [that line](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/storage.js#L769), and at that location there is no check for bad compiled filter list data, and as a consequence the issue here.

I suspect uBO should wait for the removal to be completed by waiting for the extensions API to confirm the operation has completed, I have assumed that the order of operations ensured this but now I am not so sure. I will see if this makes a difference.
