### ISSUE TITLE
Request: allow for cosmetic filters

### ISSUE THREAD

**Issue by vylmen** [uBlockOrigin/uBlock-issues#1385]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
A way to prevent a cosmetic rule from being applied. Details, see steps to reproduce.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

Not relevant, since current behaviour is working as documented.

### Steps to Reproduce

0. A cosmetic rule is buried somewhere in the 3rd party filter list. The rule is generally useful, but not for a specific situation.
1. There is no facility to disable this rule for a specific site.
2. Researching what cosmetic filter or even which cosmetic filters (plural) are responsible for the element being matched, can be daunting given the multitude of methods available to select a given element. Even when found, turning it off can only be done by turning off the 3rd-party list.
3. A work-around is to use the style() action and override the hiding that uBlock origin is doing. However, this still counts as a "block", so the count of "elements hidden" doesn't decrease and instead of preventing an action, it's doing 2 actions in order to give the appearance of no change.

### Expected behavior:

I would like to request an "allow" action that prevents any action by other rules from happening on the selected element. As a result, the "hidden elements" counter should not be increased.

### Actual behavior:

Not relevant.

### Your environment

* uBlock Origin version: uBlock Origin v1.31.0
* Browser Name and version: Firefox 83.0
* Operating System and version: MacOS 10.14.3

**Comment by gorhill** [comment]
> There is no facility to disable this rule for a specific site.

Yes, it's called an exception filter, and you can use uBO's DOM inspector to assist you in creating them.

**Comment by uBlock-user** [comment]
> A way to prevent a cosmetic rule from being applied.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exceptions

**Comment by vylmen** [comment]
Gah, I guess I missed that cause the cosmetic filter specific page and introduction to static filters, doesn't mention exceptions at all.

**Comment by keczuppp** [comment]
> vylmen : Gah, I guess I missed that cause the cosmetic filter specific page and introduction to static filters, doesn't mention exceptions at all.

Bullshit, it seems you are just looking for an easy excuse of YOUR fault reading uBO documentation...
don't blame it, because it DOES mention exceptions in 5 places already:

At the beginning of [THIS](https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#static-extended-filtering)  uBO wiki page it says:

> uBlock Origin ("uBO") supports most of EasyList filter syntax, so you can refer to existing filter syntax documentation from [Adblock Plus](https://adblockplus.org/en/filters) and [AdGuard](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).

and then just:
- (1) following the Adblock Plus documentation link, it clearly mentions cosmetic exception filters here:
https://help.eyeo.com/en/adblockplus/how-to-write-filters#elemhide_exceptions
- (2) ( just like uBlock-user already mentioned in his comment https://github.com/uBlockOrigin/uBlock-issues/issues/1385#issuecomment-739567188 )
following the AdGuard documentation link, it clearly mentions cosmetic exception filters, here:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exceptions


Also:
- (3) at the beginning of [THIS](https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#static-extended-filtering) uBO wiki section it shows a cosmetic exception filter
- (4) another uBO wiki section [HERE](https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#scriptlet-injection) shows a cosmetic exception inject filter whose syntax is based on cosmetic filters
- (5) (just like gorhill already mentioned in his comment https://github.com/uBlockOrigin/uBlock-issues/issues/1385#issuecomment-739565681)
[THIS](https://github.com/uBlockOrigin/uBlock-issues/wiki/DOM-inspector) uBO wiki page mentions about using uBO DOM-inspector to inspect and create cosmetic filters exceptions
