### ISSUE TITLE
$popunder works in Opera but not in Firefox on some websites

### ISSUE THREAD

**Issue by keczuppp** [uBlockOrigin/uBlock-issues#1393]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
- not sure whether it's a bug in uBO or in Firefox or the website somehow bypass [`$popunder`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#popunder) so it (the `$popunder`) needs to be fixed
- visit the url and click a green button labeled "Pokaż kod rabatowy"
- filter `kod.rabatowy.pl$popunder` works in Opera but not in Firefox
- same filter works in Firefox just fine for other similiar websites:
`$popunder,domain=rabatio.com|alerabat.com|salesandshopping.pl|kodyrabatowe.olx.pl`
https://github.com/MajkiIT/polish-ads-filter/blob/7334eec147caed2434f5bdf4d745fcc5f817c2e0/polish-adblock-filters/adblock_ublock.txt#L390
- orginal issue: https://github.com/MajkiIT/polish-ads-filter/issues/18048 + https://github.com/uBlockOrigin/uAssets/issues/8332#issuecomment-739552506, also here: https://github.com/uBlockOrigin/uAssets/issues/8348
- so for `kod.rabatowy.pl` in Firefox we have added also an alternative filter: 
```
!#if env_firefox
kod.rabatowy.pl##+js(nostif, gotoUrl, 300)
!#endif
```
 as well, but it is not a full replacament as it will only prevent the orginal tab from redirecting to new/ads url instead of closing it completely

### A specific URL where the issue occurs

`https://kod.rabatowy.pl/benevento`

### Steps to Reproduce

1. make sure that for testing purposes you have disabled `POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda` as it already contains filters which can be interferring https://github.com/MajkiIT/polish-ads-filter/blob/7870b2305ee9d96f893f8127ea293203781a4c12/polish-adblock-filters/adblock_ublock.txt#L390-L393
or alternatively add:
`$popunder,domain=rabatio.com|alerabat.com|salesandshopping.pl|kodyrabatowe.olx.pl|kod.rabatowy.pl,badfilter`
`kod.rabatowy.pl#@#+js(nostif, gotoUrl, 300)`
2. visit the url and click a green button labeled "Pokaż kod rabatowy" - notice "popunder" ads  (as described [HERE](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#popunder))
3. add filter `kod.rabatowy.pl$popunder`
4. repeat step 1. (visit & click)
5. notice the filter works in Opera but not in Firefox

### Expected behavior:

Should work in both Opera (Chromebrowsers) and Firefox
### Actual behavior:

Works only in Opera (Chromebrowsers), doesn't work in Firefox

### Your environment

* uBlock Origin version:  1.31.3b6
* Browser Name and version: Firefox 83 / Opera 72
* Operating System and version: Win 7 SP1 64bit

### Screenshot(s)

![222222](https://user-images.githubusercontent.com/74409207/101764764-bcd39400-3ae0-11eb-936f-59220b21f388.png)

**Comment by gorhill** [comment]
> maybe `remove-attr.js` should be enhanced with observer.

It has been since a while now -- so should this issue be closed?

**Comment by gwarser** [comment]
@gorhill can you look closer at this? I think Firefox is not calling `onCreated` for tabs opened from `target="_blank"` links. Does not pause on https://github.com/gorhill/uBlock/blob/5a7600925b999e1839e271a473af58808729f9b2/src/js/tab.js#L526 Most of the popup code is not executed at all because of this. https://github.com/gorhill/uBlock/blob/5a7600925b999e1839e271a473af58808729f9b2/src/js/tab.js#L499 is skipiped because `popupCandidates` is empty.

Maybe related: https://bugzilla.mozilla.org/show_bug.cgi?id=1344376

STR:

- open https://kod.rabatowy.pl/benevento
- click green button

**Comment by gorhill** [comment]
`||kod.rabatowy.pl^$popunder` works for me:

![g](https://user-images.githubusercontent.com/585534/123676550-16e43e80-d812-11eb-8e29-7f648cccdb7e.png)

What am I missing?

**Comment by gwarser** [comment]
In Firefox?

**Comment by gorhill** [comment]
Yes, Firefox 89.0.2, uBO 1.36.1b1, Linux Mint 20.1.

**Comment by gorhill** [comment]
Hmm just found out I had `fission.autostart` set to `true`, toggling it to `false` (reportedly the default value), I can reproduce the issue.

**Comment by gorhill** [comment]
It seems I could theoretically detect new tabs being created from the onUpdated() event listener, but given that there is a workaround filter anyway, and given that so far this is not a seriously breaking issue (given the number of conditions required to trigger it), I prefer to wait for Firefox to fix the issue, so that I don't end up throwing ever more code risking regressions potentially more serious than the initial problem. This can be re-opened if ever the issue become more serious.
