### ISSUE TITLE
Possible to add more UI customization settings?

### ISSUE THREAD

**Issue by stbeep1** [uBlockOrigin/uBlock-issues#1435]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Is it possible to add more UI customization setting? e.g allow user to customize the ubo blocked page? e.g custom blocked message/ custom blocked icon/ and allow users to chose if they want to hide the above sentence and button. 
"Disable strict blocking for xxx.wxyz.com" , Temporarily, Permanently.

![image](https://user-images.githubusercontent.com/76418860/103500833-3dd73e80-4e87-11eb-89f7-cca5b0bdc8d2.png)
The reason I request that is because it will make the blocked page more neat and tidy and also professional. 
Plus, is it possible to allow users to upload their own png image to be the icon of the uBO extensions? 

* Browser Name and version: Chrome v85
* Operating System and version: Windows 10 (2004)

**Comment by gorhill** [comment]
Customizing such page is not really trivial -- the page is privileged because it must communicate with uBO's main process to exchange information, which would not be possible by loading a page from outside uBO's package.

So the only option left is customizing piecemeal by injecting HTML/CSS content to replace what is there, something not trivial at all, and add to this that the JS code in there expect a certain HTML layout to function properly.

> it will make the blocked page more neat and tidy and also professional.

Well I think it looks fine already, it was designed in collaboration with Mozilla's people. What do you think does not look "professional"? The problem with such customization is this involves a lot of work taking time away from working for uBO's core purpose.

**Comment by stbeep1** [comment]
> So the only option left is customizing piecemeal by injecting HTML/CSS content to replace what is there, something not trivial at all...

_This is what I want,_ hope that will be available in a future release.

**Comment by stbeep1** [comment]
Also, can I change uBO's blocked page background to black?

**Comment by gorhill** [comment]
Declined, I consider this to be work beyond the core purpose of uBO, not worth for me to invest my limited time and future time required for maintenance purpose and issue arising of more code being thrown in uBO codebase.
