### ISSUE TITLE
An admin settings to disable some buttons in the blocked page

### ISSUE THREAD

**Issue by stbeep1** [uBlockOrigin/uBlock-issues#1437]
### Prerequisites

- [x] ✔️ I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] ✔️This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] ✔️I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

Ablity to set specific setting / or all settings to be read-only and disable users from clicking the "disable strict blocking for abcxx.com" button in the blocked page, config by an admin using the policy named _adminSettings_? 

### My environment

* uBlock Origin version: v1.31.2
* Browser Name and version: Google Chrome 85 
* Operating System and version:  both Windows 10 (2004) and Chrome OS 85.

**Comment by gorhill** [comment]
> specific setting / or all settings

That sort of statement is unactionable.

---

> disable users from clicking the "disable strict blocking for abcxx.com" button in the blocked page

This is what I am asking, a specific item which is actionable.

So you are asking that a user is prevented from dismissing the warning and prevented from navigating to the blocked site?

**Comment by stbeep1** [comment]
My suggestion is that having a settings for that in the "advanced settings" 
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/advanced-settings.html

**Comment by stbeep1** [comment]
> That sort of statement is unactionable.

but why?

**Comment by stbeep1** [comment]
I want the ablity to set all settings to be read-only by end users, please!

**Comment by gorhill** [comment]
How can I know what work is to be done for something vague like _"specific setting / or all settings"_? How can I know whether I agree or disagree with a vague description of something?

If you can't understand this, it's now going to work very well, I have already spend a lot of time this morning **not** doing actual work in whatever time slice I allocate to this project.

**Comment by stbeep1** [comment]
Sorry about that.

**Comment by stbeep1** [comment]
I want the ablity to set all settings to be read-only by end users, is that possible?

> How can I know what work is to be done for something vague like _"specific setting / or all settings"_? How can I know whether I agree or disagree with a vague description of something?
> 
> If you can't understand this, it's now going to work very well, I have already spend a lot of time this morning **not** doing actual work in whatever time slice I allocate to this project.

**Comment by stbeep1** [comment]
I want to have the ablity to set the above settings as read only by end users. Thanks.

_Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses 
Disable cosmetic filtering 
Block media elements larger than x
Block remote fonts 
Disable JavaScript 
Reset to default settings
Block CSP reports 
set All filter list and Custom block list as read only by end users
set my filter list as read only by end users
set all of my rules list as read only by end users
set whitelist website as read only by end users
set trusted site as read only by end users_
_^^ disable users from clicking the "disable strict blocking for abcxx.com" button in the **blocked page** (both Temporarily and Permanently button)_
**All** advanced user settings 

is that possible to implement that in a future release? Thank you @gorhill

**Comment by gorhill** [comment]
Declining this.

Here is the reason: this morning the first notification I opened was you asking for the ability to admin-add trusted-site directives to the user's own list of trusted-site directives. I thought this was a fair, pointed request, and did the work to support this. Now you are asking me something that is incompatible with that original request, and which is a long laundry list for the ability to lock down uBO's settings, in contradiction with your first request.

What you ask is non-trivial, appears to be completely a laundry list of things-you-would-personally like with apparently no second thought about how burdensome such requests is on volunteers here and without visible restraint as whether it's beneficial to actually all admins out there, and as per your own description in your first request, this is something that you did not even have with ABP, and possibly never care to ask the paid developers behind ABP.

**Comment by gorhill** [comment]
You can set `popupPanelDisabledSections` to 28 to create an obstacle to access options from popup panel.

**Comment by 29039** [comment]
Hey @gorhill thanks for uBlock Origin, very useful, I have installed it on dozens of PCs to help friends and family avoid bad content.  I hope that I haven't caught you on a bad day. 

I just wanted to let you know that I have a family member who clicked onto an item on the badware list and was stupid enough to press the 'Temporarily' button and fall for it because they are stupid and have no clue as to what they are actually doing, and had conditioned themselves to always press that button after having found that they shopping coupons were being blocked as well.

I am just wondering if there is a possibility to be able to lock-down uBlock Origin in a way that filters, especially badware/malware etc. cannot be bypassed. 

I have checked a few other blocking solutions and yours is the only one which blocked this particular site, which is a real credit to your work.

If you would like a donation to complete the work, please tell me how much to give will make it worth your while?

I really prefer to avoid Malware cleanups in the future so I would really like to put in some kind of solution which will protect users from themselves by locking away the ability to bypass so easily. 

I am not dictating a particular implementation, but perhaps:

* The locked features can be hidden behind a configurable password?
* Maybe too much work, but if the Strict Blocking page has been hit due to a Malware/Badware filter as opposed to regular old adware, make the page look more scary (Red background, exclamation mark, etc.) and remove the 'Temporary', 'Permanent' & the On/Off symbol options.
