### ISSUE TITLE
Add a CSS / Stylesheet row in advanced settings (se picture)

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1492]
### Prerequisites

- [x I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

To increase usability of 3P add an option to (noop) stylesheets/CSS

![image](https://user-images.githubusercontent.com/30925856/107288425-b96a7380-6a63-11eb-9dd0-a10e29b41602.png)

### A specific URL where the issue occurs

https://www.nu.nl/

### Steps to Reproduce

block 3p, noop images, surf to nu.nl
### Expected behavior:

[What you expected to happen]
An option (like images) in the advanced grid (matrix :-) ) to noop CSS. This would break less websites when I would use block 3P

### Actual behavior:
Not a bug but an enhancement

### Your environment

* uBlock Origin version: 
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
Why not just globally block 3rd-party scripts and frames, such that when you noop the 3rd-party cell, the resulting effect is to allow only passive content such as CSS.

**Comment by Kees1958** [comment]
Okay, I thought that 3p als covered fetches/xmlhttprequests and websockets. When not what is the purpose of having 3p and images as option to block/noop?

I am using that on Edge, but on Firefox I use block all and when blocking all, I seem to miss the CSS option.

**Comment by gorhill** [comment]
> thought that 3p als covered fetches/xmlhttprequests and websockets

If these are 3rd-party, yes, this will also block fetches etc.

> on Firefox I use block all and when blocking all, I seem to miss the CSS option

As per your screenshot it's because the CSS is hosted at a cname-cloaked server, so you have to noop this to get the stylesheets and all should work fine.

Blocking all 3rd parties only without blocking 3rd-party scripts and frames is an unconventional use, as suggested in the _hard mode_ [documentation](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode), the benefit of blocking various levels of 3rd-party is that you can use [relax blocking mode command](https://github.com/gorhill/uBlock/wiki/Keyboard-shortcuts) to fall back to a lesser dynamic filtering mode.

I don't see a _stylesheet_ cell fitting nicely into this, so I prefer to decline this. Your best action as per the case you submitted is to simply noop `d319isq1sikamv.cloudfront.net`.

**Comment by Yuki2718** [comment]
> Okay, I thought that 3p als covered fetches/xmlhttprequests and websockets. 
> 

If you block 3p script, 3p xhr or fetch doesn't happen except for those by CORS and xhr/fetch by CORS are still not very common as of 2021.
