### ISSUE TITLE
Suggestion: Add an option to prevent websites from automatically fullscreening themselves

### ISSUE THREAD

**Issue by Intermo101** [uBlockOrigin/uBlock-issues#1540]
This would be very useful for blocking malicious websites if uBlock could prevent a website from fullscreening itself through Javascript and then display a prompt if the website should be allowed fullscreen access.

**Comment by gwarser** [comment]
Browsers already do this, no?
Do you have any example of such pages?

**Comment by Intermo101** [comment]
If there is such an option in Chrome, I was unable to find it. Probably the best example would be Fullscreen API hijacks ([see this](https://www.youtube.com/watch?v=ebWftq6kA30&t=7s))

**Comment by gorhill** [comment]
Closing as invalid. Report instances of such issue to uAssets. The link you posted is not an actual instance of this, it's a 7-second Youtube video showing some sort of proof-of-concept.

If ever such instances are reported, then we will decide how to best deal with this, I do not add such filtering feature just because someone asks it, I add filtering capabilities based on discussions with filter list maintainers and according to prevalence of such issues.
