### ISSUE TITLE
Request for Select All Option

### ISSUE THREAD

**Issue by v00v** [uBlockOrigin/uBlock-issues#172]
Can you please add "Select All" lists option? Its very anoying having to manually select many lists, by clicking on every checkbox. Thank you!

**Comment by gorhill** [comment]
Declining, this will encourage users to select all lists with no second thoughts, while I [warn against](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#stock-filter-lists) too many lists in the wiki due to higher likelihood of site breakage.

**Comment by v00v** [comment]
@gorhill At least have this as an option in advanced mode to be enabled O_o It can be off by default. I have been using all filters with uBlock and uMatrix ever years and never had any breackage issues.

**Comment by ggygvff** [comment]
you&nbsp; can not&nbsp;send&nbsp; me&nbsp; information&nbsp; &nbsp;any&nbsp; more，because&nbsp; i&nbsp; have&nbsp; get&nbsp; my&nbsp; project.



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 5, 2021 18:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [uBlockOrigin/uBlock-issues] Request for Select All Option (#172)




 
@gorhill At least have this as an option in advanced mode to be enabled O_o It can be off by default. I have been using all filters with uBlock and uMatrix ever years and never had any breackage issues.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by felix-22** [comment]
> I have been using all filters with uBlock and uMatrix ever years and never had any breackage issues. Otherwise having all those checkboxes with predefined filters is useless.

Then most likely you have been just lucky, not true that non-default filter lists don't cause breakages, this is an exact reason why they are not enabled by default, especially annoyance lists have tendency to break sites, some other non-default lists like AdGuard Base or AdGuard Tracking Protection don't break sites more often than EasyList or EasyPrivacy hence I have the mturned on and would only agree to enable the mentioned two AdGuard lists by default, and no other.


> Why not than just create a textarea or input box were we can add custom lists from the start. 

There is already such input text area for custom filter lists: 
https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

> Also you can easily check for duplicate filters programaticly, unless you don't know how its done O_o Than no breakage will ever happen!

uBO already does remove duplicates.

> Without having a single default list aside from uBlock onces. All this uncked filters also encorage people to check them all thinking it will protect them better. So best not have any third-party lists at all than and just have an option to add from official uBlock repo list.

Depends on the needs and preferences of the individual user, one user needs these lists, the other doesn't, some users have broken sites and the other are lucky and don't have broken sites, let the lists stay and let each user decide for himself whether to use them or not, they are good lists, should not be removed.

**Comment by gwarser** [comment]
Make custom config and import it after new install. If you have many installs use policies.
