### ISSUE TITLE
Edge extension blocks backward in  some page

### ISSUE THREAD

**Issue by strngtn** [uBlockOrigin/uBlock-issues#1740]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When enabled UBO with default settings in Edge(not check other browser), I find out it will block backward sometime. 

After disable all filters set, it works well the the issue gone. After one by one check, I figure out the problem mostly reproduce when these bundled filter set (UBO filter Privacy / UBO filter Resource Abuse) enabled.  

Not report this as a filter issue because 
1. It comes from bundled set and turn on by default.
2. I find out that the previous page(link in step 1, when I click the back button at step 3)

### A specific URL where the issue occurs

    https://www.mysmth.net/nForum/#!board/GameIndustry

### Steps to Reproduce

1.  Goto this forum https://www.mysmth.net/nForum/#!board/GameIndustry
2. Click one link in the main article pane
3. Click browser back button and notice

### Expected behavior

Goto web page in step 1.

### Actual behavior

Stay at web page in step 2.

### uBlock Origin version

uBlock Origin 1.38.0

### Browser name and version

93.0.961.52 (x86_64)

### Operating System and version

macOS 11.6

**Comment by gwarser** [comment]
Removing `+js(nofloc)` fixes this. Adding `+js(set, test)` broke it again - really something in injector?

**Comment by gorhill** [comment]
I can reproduce.

> Few people complained about this on Reddit

For the same site?

**Comment by gorhill** [comment]
I get the same issue with AfGuard + AdGuard Chinese, so there is a bigger issue related to scriptlet injection -- possibly a site or browser issue (I can't reproduce with Firefox stable).

**Comment by gorhill** [comment]
For now we should just except the `no-floc` scriptlet for the site. I can reproduce in Chromium even though the script does absolutely nothing because `Document.prototype.interestCohort` is not defined.

I notice that when I click a link in the front page, I see an extraneous entry in the history because there is a redirect occurring:

1. `https://www.mysmth.net/nForum/#!article/GameIndustry/10702403`
1. `https://www.mysmth.net/nForum/article/GameIndustry/10702403`
1. `https://www.mysmth.net/nForum/#!board/GameIndustry`

So when going back, it goes back to 2., which then again redirect to 1. That extraneous entry is not present when disabling scriptlet injection with `mysmth.net#@#+js(no-floc)`.

**Comment by gwarser** [comment]
It was probably this thread https://www.reddit.com/r/uBlockOrigin/comments/noe1eg/ublock_blocks_mouse_back_button_on_some_pages/

But It looks like slightly different issue and I cannot reproduce on provided page, Instagram or Gmail.
