### ISSUE TITLE
Security: Comments can still be used to smuggle arbitrary CSS

### ISSUE THREAD

**Issue by hackvertor** [uBlockOrigin/uBlock-issues#1794]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

This bug is related to #1693 and was marked fixed. However, it's still possible to smuggle arbitrary CSS through filter selectors. The following filter list causes a CSS injection:

```
##input,input/*
##input[x="*/{}*{background-color:red;}"]
```

The {} is used to make the CSS parser drop everything before as an invalid selector, this then allows you to define your own selector, in this case I make the background red but you could change it to use background URLs etc.

### A specific URL where the issue occurs

https://portswigger-labs.net/

### Steps to Reproduce

1. Create a filter in my filters:
```
##input,input/*
##input[x="*/{}*{background-color:red;}"]
```
2. Visit https://portswigger-labs.net/ and the background should appear red.

### Expected behavior

The background should not appear red and arbitrary CSS should not be allowed to be injected.

### Actual behavior

The filter injects CSS onto the page and the background goes red.

### uBlock Origin version

1.38.4

### Browser name and version

Chrome 95.0.4638.69

### Operating System and version

MacOS 10.15.7

**Comment by gwarser** [comment]
```
Invalid generic cosmetic filter in user-filters: ##input,input/*
```

Is logged in 1.38.7b12

**Comment by uBlock-user** [comment]
> and the background goes red.

Can't repro that on Firefox.

**Comment by felix-22** [comment]
- I can reproduce on `1.38.4` and `1.38.6` - both filters are accepted.
- but not in `1.38.7b12`, because the first filter get's rejected as invalid [like gwarser already mentioned](https://github.com/uBlockOrigin/uBlock-issues/issues/1794#issuecomment-958961163) 

So it seems this has been fixed somewhere in `1.38.7b` line, 
best for you to upgrade uBO to the newest dev or wait for official standard release.

**Comment by gorhill** [comment]
The commit <https://github.com/gorhill/uBlock/commit/4f923384de152fafaa52df8fa3e282cbe3db8659> made the issue here go away.

Also, there is no need to use words as _smuggle_ or _arbitrary_ when it's already allowed by design to apply `background-color:red` with a cosmetic filter like:

    *##* { background-color: red }

**Comment by hackvertor** [comment]
@gorhill The background colour was only to demonstrate the issue. It's possible to use background urls too. Which isn't possible with a cosmetic filter right? That's why I said arbitrary CSS because normally this wouldn't be allowed.

**Comment by gorhill** [comment]
> It's possible to use background urls too

Please provide a proof of concept.

**Comment by hackvertor** [comment]
Sure ...

```
##input,input/*
##input[x="*/{}*{background:url(https://hackvertor.co.uk/images/logo.gif)}"]
```

**Comment by gorhill** [comment]
Thanks, I can reproduce. [This commit](https://github.com/gorhill/uBlock/commit/a2d85453820cd2016dc45d904870b4cdafb6bc25) was specifically looking for opening comment in style declarations, while in the current case the opening comment is outside a style declaration.

The filter `##.fail,.fail/*` ([test page](https://gorhill.github.io/uBlock/tests/css-selector-based-cosmetic-filters.html)) no long work because now uBO detects that this filter can't be injected in a declarative manner in a stylesheet, the browser rejects the declaration because of the dangling `/*`.

Currently when this happens, uBO tries to compile the filter as a procedural one, but end up rejecting it because implicitly global procedural filters are forbidden.

So I tried `*##.fail,.fail/*` which render the filter valid as an explicit global filter, but due to the fact that the filter is compiled as a procedural one, it will never be injected in a style sheet, which was the root issue here.

So it appears by chance [this commit](https://github.com/gorhill/uBlock/commit/4f923384de152fafaa52df8fa3e282cbe3db8659) took care of the issue here.

**Comment by gorhill** [comment]
Related: <https://portswigger.net/research/ublock-i-exfiltrate-exploiting-ad-blockers-with-css>
