### ISSUE TITLE
Element Picker not working

### ISSUE THREAD

**Issue by RookieNeophyte** [uBlockOrigin/uBlock-issues#1795]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

When I launch element picker (eyedropper), I cannot select elements, entire page is grayed out and cursor presents as a "+" only.   Element zapper mode works fine.

### A specific URL where the issue occurs

www.nytimes.com

### Steps to Reproduce

Open NY Times homepage
Log in
Select element picker tool
Entire page grayed out, cursor moveable but only a "+" hovering over gray background top of page to bottom

### Expected behavior

Ability to select individual elements to create filters

### Actual behavior

Unable to select anything at all, have to refresh page to get rid of gray overlay.

### Configuration

Current versions of Microsoft Edge, Win10, Ublock origin version 1.38.4 (most recent I can load, although reference to 1.38.6 release found)

**Comment by gwarser** [comment]
Does it work on images? Did you disabled cosmetic filtering (eye icon in uBO popup)?

**Comment by RookieNeophyte** [comment]
Thanks for suggestion, I had cosmetic filtering on, seems to work with it off.

**Comment by gorhill** [comment]
> I had cosmetic filtering on, seems to work with it off.

That is the opposite, you had cosmetic filtering off, it's on by default.

**Comment by gorhill** [comment]
> - [ ] uBO with default lists/settings

This was removed from the template, had this been verified, this would have made it clear the "issue" was linked to customizations.

**Comment by RookieNeophyte** [comment]
Thanks for clarification and correction, I thought I had it "on" by clicking.

**Comment by felix-22** [comment]
> RookieNeophyte :
> ### Prerequisites
> [x]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
>
> I thought I had it "on" by clicking.

Really? If you'd checked, you would have know that it is enabled by default and you had it manually "off" by clicking: 

> https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering : Cosmetic filtering is always enabled by default.

<hr>

> RookieNeophyte :
> ### Prerequisites
> [x]  I performed a cursory search of the issue tracker to avoid opening a duplicate issue

Really? Maybe too cursory then...searching issue tracker for "Element picker" in title quickly finds the same issue on the 7th place from the top: 
https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+in%3Atitle+%22Element+picker%22+

Your issue is a duplicate of: https://github.com/uBlockOrigin/uBlock-issues/issues/1569 
Both are invalid for the same reason: abused/skipped template / some steps falsely marked as completed.

<hr>

> RookieNeophyte : Thanks for clarification and correction

Issue tracker is not a proper place for "clarification and correction" user-side modifications, there is a documentation for it and steps to follow and mark as completed in the issue template.
If you had actually read the documentation and followed the required steps, you would have realized that it was a problem on your side, and you would not have had to create an invalid ticket. 
"I thought I had it "on" by clicking." is a cheap excuse for your abusement of the issue tracker.
