### ISSUE TITLE
'Address of webpage' textbox needs to be readonly or changes to it need to be monitored

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uBlock-issues#1836]
If the user changes what is in the `Address of the web page:` textbox,
those changes are ignored when he presses the `Find similar reports` button!
E.g., if he changes example.com to example.net, the form will still look for example.com reports!
Same with the Create new issue button.
If not planning to read what the user changed, then at least make that textbox readonly.

_Originally posted by @jidanni in https://github.com/uBlockOrigin/uBlock-issues/issues/1541#issuecomment-975526568_

**Comment by uBlock-user** [comment]
Do not bypass the template.

**Comment by jidanni** [comment]
> Do not bypass the template.

I hit "Reference in new issue". You need to add a template to it.
![20211125T132929](https://user-images.githubusercontent.com/1230959/143384971-76682150-4fc8-4893-a206-fa692df22f1c.jpg)

**Comment by jidanni** [comment]
They can still 'remove' information by highlighting and copying the part they want to remove, from a readonly field instead.
Keeping it editable misleads users into thinking they are actually changing the form inputs.

**Comment by felix-22** [comment]
> [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out) *

Given this issue example: https://github.com/uBlockOrigin/uAssets/issues/10574 ( `open.spotify.com` ):

- current default search behaviour after pressing "Find similiar reports" button is searching uAssets tracker for full domain name `open.spotify.com` which results in finding only 2 issues: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22open.spotify.com%22+in%3Atitle
- if reduce from `open.spotify.com` ==> `spotify.com` it could find 4 issues, which is twice as many issues compared to default: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+spotify%2Ccom
- if reduce further from `spotify.com` to `spotify` it could find 14 issues, which is 7x more issues compared to default: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22spotify%22+in%3Atitle+

Another example: `twitter.com`:
- 5 issues found when searching for `twitter.com`: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+twitter.com
- 22 issues found when searching for `twitter` : https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+twitter , which is over 4x more than issues compared to default

As seen:
- I've provided just 2 examples / sites (spotify, twitter), but there is many more, you can try yourself with any medium to big popular sites and you will notice the same issue: most of issues missed
- the point is, searching for the whole specific domain often results in missing many legitimate results/issues
- on the other hand, it may have an advantage that it does not inundate the user with unnecessary overly general results like: 
  - generic domains while the issue occurs only in a subdomain, 
  - different reginal TLDs while  the issue occurs only in one specific TLD
- but, further on the yet other (another) hand, often issues affect different TLDs and the whole high level domain

So the whole final point is to whether to search:
- for a specific domain (`sub.domain.com`) 
- or for a whole site name (`domain`)

As proven, the both solutions have their pros and cons, so the final and the biggest point is to decide which search method is more beneficial than harm compared to the other.

I am not saying right away that the current method needs to be changed, but on the other hand, I am not denying it, I am simply informing about the problem and putting it to discussion. 

<hr>

Another part of the issue is that some sites have their collective thread :
- (Facebook) https://github.com/uBlockOrigin/uAssets/issues/3367
- (Youtube) https://github.com/uBlockOrigin/uAssets/issues/7636
- (Twitch) https://github.com/uBlockOrigin/uAssets/issues/5184
<br>

- in case of 2 of them (`youtube.com` and `twitch.tv`) they are being found when using "Find similiar reports button" 
  - `youtube.com` ==> https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+youtube.com
  - `twitch.tv` ==> https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+twitch.tv
- but not `facebook` because it's collective thread's name is missing TLD 
  - `facebook` ==> https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+facebook.com

The solutions: 
- change the name of the collective thread https://github.com/uBlockOrigin/uAssets/issues/3367) from `facebook` to `facebook.com` 
- or...as discussed earlier: change default search method from specific (`facebook.com`) to generic (`facebook`)
- or put in the reporting issue feature template some information / detection that the site being reported is popular and has it's own collective thread so instead of creating a new issue , create a new comment in the already existing collective thread, just like AdGuard does:
  - https://github.com/AdguardTeam/AdguardFilters/issues?q=is:issue+is:open+sort:comments-desc
  - (Facebook example collective thread reporting) https://github.com/AdguardTeam/AdguardFilters/issues/92570

**Comment by gorhill** [comment]
> Also maybe you prefer to wait and see how things will evolve.

Yes.

All this needs road testing before asking for changes based on assumptions. There have been already changes in the template following the unforeseen spamming of issues raised yesterday, and we will keep fine tuning according to how things go rather than according to our anyone's assumptions of how they will go.

**Comment by felix-22** [comment]
Ok, but as for me, I have not been asking for anything, only have provided an information / facts and optional solutions, which one may or may not apply, and the optional solutions are based mainly on facts, not only on assumptions, as seen, it has been jidanni who has been "asking for changes bases on assumptions":

>  - jidanni : make that textbox readonly.
>  - jidanni : You need to add a template to it.

**Comment by gorhill** [comment]
> I have not been asking for anything

I know, my answer was not directed at you, it is directed at whoever reads the thread to clarify how the specific issue opened by @jidanni is being handled.

**Comment by uBlock-user** [comment]
That _Reference in new issue_ button is just waiting to be exploited, GitHub didn't think about how it bypasses the templates before implementing it, now anybody can click on it and create a whole new issue based on a "comment" post on any issue.

**Comment by jidanni** [comment]
All I know is if there is a search box
```
Search: ____A
```
and the user changes it to
```
Search: ____B
```
and hits ENTER, then he usually would expect it to search for ... B.
Else why let him change it?

**Comment by felix-22** [comment]
>  gorhill  : I know, my answer was not (...)

Yeah, I know too, but still some others may not have been so smart and may not have guessed and may have been suggested it was, which was making me feel uncomfortable (being mixed with someone else even by unintentional suggestion) that's why I preferred to explain it, as seen you also preffered to explain it further, so it's very clear and ok now.

<hr>

> jidanni : Else why let him change it?

Didn't you just miss the reply? I think it was already explained in:

> gorhill : https://github.com/uBlockOrigin/uBlock-issues/issues/1836#issuecomment-977913493 : 
> someone could want to remove information from the URL without changing the target site itself. 

I think the reply was about that someone may need to remove some private/tracking information from URL.

**Comment by jidanni** [comment]
> someone may need to remove some private/tracking/sensitive information/parameter from URL (so called "redacting").

I see. Somebody is about to take a screenshot to post in a bug report, and wants to remove `NSFW` from `NSFW.com` or something, instead of blurring it later in the .JPG .

Seems like a 1/1000 rare case, and the other 999 are my 'I changed A to B but it still searched for A' head-scratchers. So nobody has convinced me. Sorry.

**Comment by felix-22** [comment]
- I think the reply was more about to remove/redact tracking paramters from long urls like:
https://github.com/uBlockOrigin/uAssets/issues/10162#issuecomment-959690037 . 
- at least the URLs I've provided are encoded, but I saw several cases where they were not, and raw parameters like IP were smuggled via URL
- not sure about how often it happens ("jidanni : 1/1000")

**Comment by jidanni** [comment]
So,
the user removes the tracking parameters from the field,
but even so, they are **sent anyway by the form** upon him hitting submit, no?
So this is even worse than I thought.
The form fools him into thinking he has cleaned up his personal details,
but when he clicks submit, his personal details are sent anyway,
and perhaps he didn't notice,
or perhaps he did, but now it is too late!

**Comment by gorhill** [comment]
Yes, I need to fix this.
