### ISSUE TITLE
update assets.json for "public_suffix_list.dat"

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#193]
New URLs to add:
https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat
https://publicsuffix.org/list/effective_tld_names.dat

**Comment by gorhill** [comment]
I can add `https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat` because it's not redundant with the other.

However `https://publicsuffix.org/list/effective_tld_names.dat` is redundant to the current one -- both are hosted on the same server, so I don't see the benefit of adding it.
