### ISSUE TITLE
Wrong colors from color picker in [Appereance, Custom accent color]

### ISSUE THREAD

**Issue by Alpengreis** [uBlockOrigin/uBlock-issues#1957]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The color picker from [Appereance, Custom accent color] does not work right. For many colors the color changes automatically after selecting and OK.

### A specific URL where the issue occurs

Unrelated to URLs

### Steps to Reproduce

1. Go to uBlock settings.
2. Pick a Custom accent color, for example the light gray.

### Expected behavior

I would expect that the Custom accent color is light gray.

### Actual behavior

The Custom accent color has changed automatically to light red.

### Configuration

- OS: Microsoft Windows 10 Pro x64 [19044.1503] [21H2] [de-CH]
- Browser: Firefox Dev. 97.0b9 (64-Bit)
- uBlock: 1.40.9b9

**Comment by gorhill** [comment]
It's because I limited saturation to not be lower than 50. I could allow all saturation range, but even then the color set will very unlikely be the color picked -- for this feature to work (and actually make sense), uBO has to control precisely the lightness, and the widget shows you the color picked (hue, saturation) at lightness 70, from which all other lightness are derived. I will remove the lower limit on the saturation, but beyond that, the color shown being different than the color picked is by design -- the only way to "fix" this would be the write my own color widget instead of the browser's built-in one -- not something I ever intent to do.

**Comment by gorhill** [comment]
After some more thought, probably best uBO remember the exact selection even though internally it will use a normalized version. Problem with greys is that the hue information is always reset to zero -- so remembering the exact picked color and reusing it next time the picker is brought up -- internally uBO will you a normalized palette.

**Comment by gwarser** [comment]
Looks good.

**Comment by Alpengreis** [comment]
It's not good yet it seems. At least here the button color itself is now ok. However, the color in use is still wrong in my testing.

I tried for example with both yellow colors: the color in use is still the wrong AND the same for both yellow variants. The same with gray: button is NOW ok, color in use IS gray NOW but for both gray variants the same.

Is this by design or still a problem?

**Comment by gorhill** [comment]
By design, it's impossible to use the exact color as picked. When you pick a color, you merely tell uBO which hue and saturation you want, but uBO has to use specific lightnesses, otherwise this just would not work, you could end up with bright yellow text over light background, or dark blue over dark background. The lightness is controlled by uBO to guarantee that whatever color is picked is going to work with either the light or dark scheme.

**Comment by gwarser** [comment]
@Alpengreis you can try here: https://www.hsluv.org/

**Comment by gorhill** [comment]
That <https://www.hsluv.org/> site and library was key to unlock the dark theme and sanitizing color usage in the user interface -- I am very happy to have discovered this -- can't remember how, just know I spent a huge amount of time reading all over the place about how to design dark theme and ended up [there](https://www.boronine.com/2012/03/26/Color-Spaces-for-Human-Beings/) -- everything has become quite simple with this now, I can pick any color I want, and I just have to adjust the lightness to make the same color used in both light and dark theme. Ideally in some future browsers would support natively HSLuv, I still have to convert to rgb using the online tool.

**Comment by Alpengreis** [comment]
@gorhill, @gwarser 

Understood, thanks for the explanations and the link!

**Comment by gorhill** [comment]
> The lightness is controlled by uBO to guarantee that whatever color is picked is going to work with either the light or dark scheme.

Just to give a concrete example, the power button in the popup panel has always a color with a (Luv) lightness of 50 for light theme, or 60 for dark theme. regardless of the hue/saturation. So whatever hue/saturation is picked, uBO apply a lightness of 50 (or 60 for dark theme) to use for the power button, and never a worry about legibility as a result regardless of what the user pick.

**Comment by gwarser** [comment]
> Ideally in some future browsers would support natively HSLuv, I still have to convert to rgb using the online tool.

It will probably be https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch(), https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/ in CSS4.
