### ISSUE TITLE
Missing icon on firefox 61

### ISSUE THREAD

**Issue by IAMtheIAM** [uBlockOrigin/uBlock-issues#198]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

The uBlock Origin icon is missing from firefox 61. I uninstalled, restarted firefox, reinstalled, and no icon. Where is the icon? It is not in "customize" either.

**Comment by uBlock-user** [comment]
The issue is on your end, icon appears as expected.

**Comment by gorhill** [comment]
Did you look in the overflow menu?

**Comment by gwarser** [comment]
Probably Firefox issue because problems like this one have been reported on Reddit for different extension. For example 

- https://www.reddit.com/r/firefox/comments/9biabi/extensions_not_working_on_newest_version_of/
- https://www.reddit.com/r/firefox/comments/99yzfr/noscript_should_be_there_but_this_am_my_browser/

**Comment by IAMtheIAM** [comment]
Why should a person have to delete their entire user profile, losing all settings, extensions and preferences, just to get ublock working? That is a poor solution and I think not correct.

I checked overflow menu and it did not appear there either. If not a uBlock issue, then indeed its a firefox issue.

**Comment by gorhill** [comment]
You don't need to delete the profile, that was a bad advice. You just need to test in a brand new one to see if the issue is still there.

**Comment by IAMtheIAM** [comment]
@gorhill Thanks for that tip. It appears something is wrong with my profile because I created a new one, installed ublockorigin and icon appears as normal. So, that's unfortunate, because now I have to either recreate my profile or figure out what happened somehow.

**Comment by gorhill** [comment]
In `about:config`, on my side I see an entry, `browser.uiCustomization.state` which value is a huge string, and which seems involved in dealing with extension icons. You could try saving the value on your side and reset that string to see the result. You can always reassign the saved value if nothing comes out of this.

**Comment by IAMtheIAM** [comment]
@gorhill You sir are a genius! I simply deleted that string, restarted firefox, and viola, the uBlock Origin icon appears now. Thanks!!

**Comment by uBlock-user** [comment]
FYI, in your case, that about:config value was changed either by you unintentionally or by another extension you use that can access about:config values which lead to this. Corrupted profiles can happen in Chromium too due to number of reasons,here it was one possibility. 

Regarding about:config, Firefox doesn't offer `Reset all to default` button, and given the number of values, you would have to reset them all one by one just to find which one works, which is a physically tiring and imposing task and not worth doing, so gorhill's guess about that one particular was the saving grace here fortunately, otherwise you would end up reseting them all anyways and losing extension amoung other things in the process.

**Comment by gorhill** [comment]
@uBlock-user Firefox controls that string. Extensions do not have access to `about:config`.
