### ISSUE TITLE
Hide predefined whitelist directives

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#214]
It could hide the predefined whitelist directives so that any user does not delete them by mistake, or that they are only visible when the user previously check the option "I am an advanced user". Or it could also hide for the "advanced user" as for the "common user". It's just a suggestion.
```
about-scheme
chrome-extension-scheme
chrome-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
wyciwyg-scheme
```

**Comment by gorhill** [comment]
Gave some thoughts about this and I agree. Also for `behind-the-scene` rules/switches.

**Comment by uBlock-user** [comment]
Keep it visible for the advanced users, no need to hide it from them as they already have access to dynamic filtering.

**Comment by vlaszlo** [comment]
How about making them stand out visually, by giving them a gray text color for instance? The same would apply to the default rules in the "My rules" tab. I think it would make it easier to quickly scan both lists. (I'm not quite sure this hasn't been suggested before and declined; a quick search didn't bring up anything. If so, I apologize)

**Comment by gorhill** [comment]
I had a change of mind and was about to close as _declined_, mainly because rendering those whitelists directives invisible would not be very useful in the end since anybody can easily remove any of these directives through the power button. Things could become confusing, and this would also now complicate the code further.

However I will consider @vlaszlo's suggestion to make the default directives/rules appear visually differently, I am guessing this shouldn  be too complicated using CodeMirror's capabilities.
