### ISSUE TITLE
Scrollbar Overlays Left Block/Allow Colors in Pop-Up UI

### ISSUE THREAD

**Issue by always-depends** [uBlockOrigin/uBlock-issues#2140]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

My environment:
- Ubuntu 22.04 Jammy Jellyfish
- 64-bit
- Firefox v102.0b7

The scrollbar on the left overlays the allowed/blocked color indicators for third-party domains when pop-up UI is in maximum More mode.  Issue was observed after jumping from Firefox v100 stable to v102 beta.  Did not check v101 Firefox releases and Firefox v100 behaved as expected.  uBO remained constant at v1.42.4 throughout.  Running uBO in medium mode in case that is significant.

![Screenshot from 2022-06-13 16-17-43](https://user-images.githubusercontent.com/6319181/173464846-a43959b7-c592-45be-9416-219f6037ae75.png)

### A specific URL where the issue occurs

https://www.cbssports.com/

### Steps to Reproduce

1. uBo pop-up UI in maximum "more" mode (continue clicking "More" in pop-up UI until "More" is no longer an option)
2. Visit a web site with enough third-party associations to engage the scroll bar
3. Observe scrollbar overlays allowed/blocked color indicators, making it challenging to distinguish colors/scrollbar

### Expected behavior

Pop-up UI left scrollbar and indicator colors independently viewable and distinguishable.

### Actual behavior

Pop-up UI left scrollbar and indicator colors overlay each other and difficult to distinguish.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 102
filterset (summary): 
  network: 133310
  cosmetic: 220440
  scriptlet: 36678
  html: 685
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext&showintro=1: 3644-0, 1d.22h.22m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 644-8, 1h.33m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1897-21, 1h.32m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-11, 4d.10h.17m
    https://www.i-dont-care-about-cookies.eu/abp/: 24951-4, 1d.8h.11m
    adguard-generic: 64758-5162, 9h.44m
    adguard-mobile: 7850-155, 9h.43m
    adguard-spyware: 26275-919, 9h.41m
    adguard-spyware-url: 629-98, 9h.40m
    block-lan: 43-0, 4d.10h.18m
    adguard-annoyance: 54096-4997, 9h.38m
    adguard-social: 17694-53, 9h.37m
    fanboy-annoyance: 72484-10274, 4d.10h.17m
    ublock-annoyances: 4452-8, 9h.36m
  default: 
    user-filters: 38-0, never
    ublock-filters: 32455-93, 9h.48m
    ublock-badware: 4195-5, 9h.47m
    ublock-privacy: 228-3, 4d.10h.18m
    ublock-abuse: 75-0, 4d.10h.18m
    ublock-unbreak: 1812-2, 9h.46m
    ublock-quick-fixes: 196-0, 1h.35m
    easylist: 68211-756, 9h.42m
    easyprivacy: 27206-10457, 9h.39m
    urlhaus-1: 7519-0, 1h.34m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
hostRuleset: 
  added: [array of 543 redacted]
urlRuleset: 
  added: [array of 34 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  cloudStorageCompression: false
supportStats: 
  allReadyAfter: 9004 ms (selfie)
  maxAssetCacheWait: 6794 ms
```
</details>

**Comment by gorhill** [comment]
If you stop scrolling, the scrollbar fade away -- it looks like it's the new default for the browser.

**Comment by gorhill** [comment]
In `about:config`, on my side I found that setting `widget.gtk.overlay-scrollbars.enabled` to `false` will restore classic scrollbars.

**Comment by always-depends** [comment]
I thought it might be the browser but thought I would start here.

Setting `widget.gtk.overlay-scrollbars.enabled` to `false` fixed the issue.  Thanks so much for the quick response and for such an awesome product.  Really appreciate this critical tool.

**Comment by gwarser** [comment]
"Always show scrollbars" in `about:preferences` should help.

**Comment by ayushnix** [comment]
I think this issue should be fixed by extending the colors as a background-color to cover either more (half?) or the entire domain cell rather than changing how scrollbar behaves.

1. If I enable "Always Show Scrollbars" in Firefox, the scrollbar on menus and web pages permanently occupies some screen real estate. This may not seem like an issue on large desktop monitors but on small laptop screens, it wastes precious pixels.
2. If I enable disable overlay scrollbars and use classic scrollbars, a lot of sites start experiencing layout shifts because they don't use either `overflow-y: auto` or `scrollbar-gutter: stable`.

I've also increased the size of the overlay scrollbar to `24` using `widget.non-native-theme.scrollbar.size.override` in `about:config` which helps me to scroll easily without missing my click. However, this completely hides the colors in the uBlock menu. As I've explained before, neither the 1st nor the 2nd approach is a suitable solution.

I request that changes to the UI should be considered in this case.

**Comment by gorhill** [comment]
If there is a change, that will be to remove the colors, there are completely unneeded and I never use them as a source of information. The pluses/minuses convery all the information needed about network requests allowed/blocked.

**Comment by ayushnix** [comment]
> The pluses/minuses convey all the information needed about network requests allowed/blocked.

Huh, now that you mention it, the colors do seem unnecessary.

I think if colors are desirable to keep around, their UI probably needs a change. The plus/minus symbols seem sufficient to me but the presence of colors offers a "better" (more attention grabbing I guess) visual indicator. I would assume that many people would find themselves reaching for the colors rather than those symbols, even when both options offer the same information.

If colors are indeed viewed as unnecessary, they should probably removed in favor of the plus and minus symbols.

**Comment by Yuki2718** [comment]
> If there is a change, that will be to remove the colors,

I disagree. I use (and have been using for years - commented the same on wilders) yellow color as an ancillary but intuitive clue about domain potentially needs to be nooped first. Ofc I can look at +/- but they're less salient/intuitive.
