### ISSUE TITLE
disabling javascript causes element picker to stop working

### ISSUE THREAD

**Issue by rokit** [uBlockOrigin/uBlock-issues#2175]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [ ] uBO is the only extension
- [X] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

### Description

Disabling JS causes the element picker to stop working.

### A specific URL where the issue occurs

https://spectrum.ieee.org/

### Steps to Reproduce

1. visit site
2. disable JS
![image](https://user-images.githubusercontent.com/1229742/179391615-fc476031-f025-4152-a4d6-a8b158f0f0f5.png)
3. go into element picker mode
4. Mouse over this popup and notice it can't be selected or clicked
![image](https://user-images.githubusercontent.com/1229742/179391486-b7cb8013-36ff-4368-9996-83b182a63c5f.png)
5. Enable JS, and notice element can now be clicked

### Expected behavior

Element can be clicked

### Actual behavior

Element can't be clicked

### uBlock Origin version

1.43.0

### Browser name and version

chrome 103.0.5060.114

### Operating System and version

win 10

**Comment by u-RraaLL** [comment]
You disabled cosmetic filtering which means you can only use network filters in the Picker.

However the website only loads images when JS is enabled, so there's nothing to select anymore.

The issue is invalid.

Enable cosmetic filtering and you'll still be able to pick elements.

![image](https://user-images.githubusercontent.com/92610420/179395546-24a78295-8176-4925-a4a8-1ff38794bdc7.png)

**Comment by rokit** [comment]
@u-RraaLL @gorhill If I'm selecting options that cause the element picker not to work, perhaps the element picker should become disabled with a message telling what I need to do. I wouldn't say the issue is invalid. I'd say there's an issue with the UI.

**Comment by gorhill** [comment]
The issue is invalid because:

- Contrary to what you reported, toggling JS does not change the behavior of the picker
    - As pointed out by @u-RraaLL, toggling **cosmetic filtering** off is what changes the behavior of the element picker
- As Pointed out by @u-RraaLL, when toggling off cosmetic filtering, the element picker is still useful to create network filters, hence why the element picker icon is still available in the popup panel

**Comment by rokit** [comment]
@gorhill Sorry, you're right. I thought I only toggled JS when I was testing. Thanks for the explanation.
