### ISSUE TITLE
Changing `--popup-main-min-width` broke scroll bar in firewall of popup

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#2184]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I have set the advanced setting `popupPanelHeightMode` to **1** *(instead of the unset 0)*. 
then after `uiStyles` I put `--popup-main-min-width: 0;`

Now the scrollbar in the firewall doesn't work

![image](https://user-images.githubusercontent.com/81161435/180473023-615a502b-d02a-4289-96e3-a7ad86b43859.png)

But is should be

![image](https://user-images.githubusercontent.com/81161435/180474969-b0c58cc8-cce1-4f56-983e-104808ed1441.png)

I achieved this by manually changing `:root.desktop body.vMin #firewall {max-height: 100vh;}` back and forth in the source code (by bringing up the UI, right clicking in it and clicking "View Page Source".)

### A specific URL where the issue occurs

`https://news.google.com/`

### Steps to Reproduce

1. change `popupPanelHeightMode` from 0 to 1 in advanced settings;
2. change `uiStyles` from unset to `--popup-main-min-width: 0;`
3. go to news.google.com
4. wait until the page is fully loaded and scroll down until the end of the page
5. open the popup and open the firewall (if not already open)
6. see that the scrollbar is missing and that the height of the extension has become larger. --> see the big grey space below the button "less"

### Expected behavior

Scrollbar should be there if there are to many domains

### Actual behavior

Scrollbar don't appear at all.

### uBlock Origin version

1.43.0

### Browser name and version

MS Edge 103

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Nowhere is it stated that changing `--popup-main-min-width: 0;` is going to do whatever you think it should do _without_ any side effects whatsoever.

It seems the issues you have been opening lately are all related to [that other issue](https://github.com/uBlockOrigin/uBlock-issues/issues/2106) another user opened which I closed a long while ago as `wontfix` because I do not want to spend any time on the sort of very specific and personal customization.

Please respect this and do not open any more issue related to this, and especially more so that the original person you are trying to assist describe me as "super self-centered", "blind", "liar", "whiner". I have no motivation whatsoever to invest my own time to try to please or interact in any way with such person.

**Comment by JohnyP36** [comment]
If someone comes across this issue: I've fixed it. 

The minimum width must be at least `96px`. 

Don't use `fit-content`, because this will brake the firewall if the hostname is very long. 
Below 96px the scrollbar of the firewall is not correct rendered.
