### ISSUE TITLE
Logger window stays on top (Firefox + KDE + Wayland)

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2334]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Fedora 36 KDE (Wayland) + Firefox 105.0.2

After opening the logger, it stays on top of other browser windows and only goes away when I minimize the logger window.

It does not stay on top of other open programs meaning I can switch to other programs without minimizing the logger.

It doesn't happen when using the Tor browser (91.13.0esr) or Ungoogled Chromium.
I could also reproduce this problem when using older versions of Firefox and using older versions of uBO.

Also I did a quick test and this doesn't happen when using X11 (Xorg).

### A specific URL where the issue occurs.

Any page

### Steps to Reproduce

1. Fedora 36 + KDE + Wayland
2. Open Firefox
3. Open uBO's logger
4. Try to go back to the previous browser window by clicking on the panel<sup> (taskbar)</sup> icon

### Expected behavior

I should be able to move between browser windows.

### Actual behavior

I can't switch between browser windows because the logger window stays on top of all browser windows.

### uBO version

1.44.4

### Browser name and version

Firefox 105.0.2

### Operating System and version

Fedora 36 KDE

**Comment by gorhill** [comment]
Windows Manager are out of control of uBO.

**Comment by benyaminl** [comment]
@gorhill I just want to ask, does that mean it's because of Firefox? Because as we see this doesn't happen on other than Linux. Thanks

**Comment by gorhill** [comment]
It doesn't happen in Chromium on Linux, so my guess is that Firefox does something different when opening as a popup window. 

You can set the advanced setting `loggerPopupType` to `normal` to get a normal window. The problem though is that as a normal window you could end up closing it last which means Firefox would only restore this one next time you launch the browser.

**Comment by gorhill** [comment]
This has been the behavior on my side since forever.

**Comment by u-RraaLL** [comment]
On my side the "on top" behavior is actually preferred.

I've found another problem though. I was considering creating a new issue, but based on this one it'll likely also be marked invalid.

I'll describe it anyway, in case anybody else encounters it:

The logger's popup window sometimes launches for me with the top of the window being off-screen, which can be a bit annoying if you don't remember shortcuts to move, resize or maximize windows to bring it back in place.

This happens when you repeatably move the popup window's bottom off-screen before closing it. You might only try to do that due to this issue's "on top" behavior, IDK. Personally I often pin windows as the top one anyway and roll them up to the title bar for visibility since XFCE gives me these options.

Anyway, once the popup is closed partly off-screen it relaunches stickied to the taskbar. But not in its original height - slightly taller. Repeat that a couple of times and you'll lose access to the title bar.

https://github.com/user-attachments/assets/5fd45cc9-8142-44f5-83b4-8647ac8b0b20

Happens only on Firefox. Only on Linux, as far as I know. I was unable to reproduce after launching an old Win10 partition.

Anyway, this is just an FYI. I don't want to "fix it" using a normal window. Like I said, I like the "on top" behavior.
