### ISSUE TITLE
Chrome Web Store: "Action Required: uBlock Origin Requires Changes to Comply with Chrome Web Store Policy"

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#2344]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Received this email a few hours ago -- needless to say, I have no idea what must be done. There has been no change in years to the description, and being markety, or worse deceptive, is antithesis of what I do (no "rate me!", or "best", etc.)

![Screenshot from 2022-10-28 09-04-46](https://user-images.githubusercontent.com/585534/198607796-a8f96e72-8f38-4e35-814c-27ebe3e07ef1.png)

I did click the link in:

> You can use this [Support Page](https://support.google.com/chrome_webstore/contact/one_stop_support) to learn more about this violation and get in touch with us.

The result is a link to a section titled _"Deceptive behavior"_: <https://developer.chrome.com/docs/webstore/troubleshooting/#deceptive-behavior>.

Which provide no clarification about the actual issue.

I can't just start to spend my whole free time endlessly trying random fixes for an "issue" which has no exact details of what needs change -- a reminder it's a hobby, and has always been since I first published uBlock on June 23rd, 2014.

uBO users should prepare themselves for uBO being removed from their browser and the end of the 30 days countdown. uBO will still be present in both Firefox, Miscrosoft, and Opera web stores (see <https://github.com/gorhill/uBlock#ublock-origin>).

### A specific URL where the issue occurs.

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

### Steps to Reproduce

1. Make coffee
2. Open email agent
3. Read new email

### Expected behavior

No email about "deceptive behavior".

### Actual behavior

Email about "deceptive behavior".

### uBO version

1.44.4

### Browser name and version

106.0.5249.119

### Operating System and version

Irrelevant

**Comment by dportvine** [comment]
>We do not allow products that deceive or mislead users, including in the content, title, description, or screenshots.

`https://developer.chrome.com/docs/webstore/program_policies/#impersonation`

The overview in English and Ukrainian languages ​​are different.

<details>
<summary>Ukrainian review translated into English</summary>

Review

Products supported by your device
An effective ad blocker did appear. Does not load the processor and memory.
Effective ad blocker: does not load memory and processor much and can work with many more filters than other blockers. 

Illustrated overview of efficiency: https://github.com/gorhill/uBlock/wiki/uBlock-vs.-ABP:-efficiency-compared 

Usage: This large power button in the popup allows you to disable or enable uBlock₀ for the current website. The effect only applies to the current website. This is not a global power button. 

*** 

Being versatile, it is more than just an "ad blocker". It can also create filters from hosts files. 

The following filter lists are loaded and applied by default: 

– EasyList 
– Peter Lowe's list of ad servers 
– EasyPrivacy
- malicious domains 

The following lists can be optionally enabled: 

- Fanboy 's enhanced watchlist 
- Dan Pollock's hosts file - hpHosts 
ad and tracking servers 
- MVPS HOSTS 
- Spam404 
- and more. 

Of course, the more filters you enable, the more memory will be used. However, even after adding two additional Fanboy lists, tracking servers and phHosts ads, uBlock₀ consumes less memory than other popular blockers. 

Also, keep in mind that the use of some additional lists may increase the probability of damage to the functioning of the site. Especially those lists that are usually used as hosts file. 

***

Without installed filter lists, this extension is nothing. So if you really want to contribute, consider the people who work hard to maintain the filter lists you use for free. 

*** 

Free. 
Open Source and Public License (GPLv3) 
For users by users. 

Contributors @ Github: https://github.com/gorhill/uBlock/graphs/contributors 
Contributors @ Crowdin: https://crowdin.net/project/ublock 

*** 

This is still very early, so keep that in mind when you review. 

Project changelog: 
https://github.com/gorhill/uBlock/releases
</details>

<details>
<summary>English review</summary>

Overview
Finally, an efficient blocker. Easy on CPU and memory.

IMPORTANT: uBlock Origin is completely unrelated to the site "ublock.org".

uBlock Origin is not an "ad blocker", it's a wide-spectrum content blocker with CPU and memory efficiency as a primary feature.

***

Out of the box, these lists of filters are loaded and enforced:

- uBlock Origin filter lists
- EasyList (ads)
- EasyPrivacy (tracking)
- Peter Lowe’s Ad server list (ads and tracking)
- Online Malicious URL Blocklist

More lists are available for you to select if you wish:

- Fanboy’s Enhanced Tracking List
- Dan Pollock’s hosts file
- MVPS HOSTS
- Spam404
- And many others

Additionally, you can point-and-click to block JavaScript locally or globally, create your own global or local rules to override entries from filter lists, and many more advanced features.

***

Free.
Open source with public license (GPLv3)
For users by users.

If ever you really do want to contribute something, think about the people working hard to maintain the filter lists you are using, which were made available to use by all for free.

***

Documentation:
https://github.com/gorhill/uBlock#ublock-origin

Project change log:
https://github.com/gorhill/uBlock/releases

Contributors @ Github:
https://github.com/gorhill/uBlock/graphs/contributors

Contributors @ Crowdin:
https://crowdin.net/project/ublock
</details>

Perhaps the problem is also related to Zuckerberg's screenshots

**Comment by gorhill** [comment]
See, that is the problem, we are here speculating and I could spend all my free time trying stuff to no end. I prefer to not subject myself to this and not play along this madness. The required change should be spelled out exactly, as would Opera and Firefox stores would (as shown per past experience).

**Comment by 0x416c69** [comment]
I think what they're trying to say is they want you to remove the keyword "Free" from the description of the extension, of course this doesn't make any sense and it exists on other extensions' description such as [AdGuard](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg)

![chrome_2022-10-28_17-56-43](https://user-images.githubusercontent.com/10671711/198644428-f59ec698-c635-4a6c-a9bc-3c62bf7c9488.png)

Maybe they also received an email or maybe this is just some trolls on Google's part? But they're definitely saying that you should get rid of the "Free" keyword.

**Comment by gorhill** [comment]
It is free, it's actual truthful information.

**Comment by 0x416c69** [comment]
Of course but I think from their point of view since every extension is free to install (but not free to use), they don't want to see this word? Whatever the case is, this is what is in the middle of the email.

A clarification on this would be great but in case Google never replied, you might wanna rephrase the "Free" keyword into something like "No payments in the extension" or just delete it? If the extension is going away from the web store it's worth a try.

**Comment by gorhill** [comment]
It is free, and has always been, there is nothing deceptive about this. Agreeing to change this imply I agree that I was deceptive. I am not and have never been. I refuse to implicitly agree that I was deceptive by changing the description.

**Comment by gorhill** [comment]
Sort of related: <https://news.ycombinator.com/item?id=33361311>. If anything, this shows the demands might never stop. I understand businesses have to be pragmatic and play along. uBO is not a business and I don't have to play along and legitimize their flawed approach by acting on their demands.

The real fix is to not target good faith parties, and being unable to differentiate is not really going to help, deceptive parties will always make it through any rules in the end. As a suggestion, maybe track record should count for something, uBO has been in the CWS for over 8 years with same ownership.

**Comment by gorhill** [comment]
Comparison of descriptions of similar extensions:

---

[uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), labelled with "deceptive behavior" as per Chrome Web Store email (note there is not a single markety claim in text or screenshot in uBO in the CWS, unlike other blockers below):
![Screenshot from 2022-10-28 12-36-00](https://user-images.githubusercontent.com/585534/198689431-3da9a5e9-3520-41c8-a45f-9225ca4cdf6a.png)

---

[Adblock Plus - free ad blocker](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb):
![Screenshot from 2022-10-28 12-34-17](https://user-images.githubusercontent.com/585534/198689899-1c563d49-33af-4b9c-a0dc-0ba703c28e71.png)

Adblock Plus also has a _"Enjoying the extension? [RATE ABP]"_ in its popup panel.

---

[AdBlock — best ad blocker](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom):
![Screenshot from 2022-10-28 12-51-13](https://user-images.githubusercontent.com/585534/198690949-0f224b50-4cbf-4cfc-9f0d-55ca907ff60e.png)

---

[AdGuard AdBlocker](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg):
![Screenshot from 2022-10-28 12-38-46](https://user-images.githubusercontent.com/585534/198689545-0faf6449-2fe1-4aab-b0cd-ee9e05a0ee70.png)

---

**Comment by sp33dy85** [comment]
Going through the various options & links on their support page,
maybe the issue isn't what the average user see on the uBlock's Chrome Web Store page, 
but what's in the 'meta data' (generic or wrong maybe??) in the page source??

**Comment by diekaines** [comment]
You cant just  leave all of us that are using chrome behind. This extension doesnt needs any description aside from "blocks ads" .
Please think again about our poor souls 

Thank you for your hard work

**Comment by krystian3w** [comment]
> description aside from "blocks ads"

🇺🇸: The drastic shortening of the description is also rather out of the question he must have with ≈140 characters, and the proposed description has 9.

//

🇬🇧: The drastic shortening of the description is also out of the question: it has to be ≈140 characters long and the proposed description is 9.

---

> using chrome behind

🇺🇸/🇬🇧:  It remains to switch to uBlock Origin Lite as it will not be banned by same time (27 November) or it will be a ban on the developer account (so also gone uBO-Scope or CCaptioner) or the entire Google services from under the given login.

**Comment by dotproto** [comment]
Hey uBO folks, [@mixajax](https://twitter.com/mixajax) on Twitter [tagged me](https://twitter.com/mixajax/status/1587581142613499910) to let me know about this issue. 

First up, it looks like the takedown warning has been removed from [cjpalhdlnbpafiamejdnhcphjbkeiagm](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm). @gorhill, have you received an email to that effect? I'm asking as I suspect you may not have (and therefore we could improve our process here). Also, if there's an active violation on the extension it would appear in the Status tab of the detail view for the extension in the [CWS developer dashboard](https://chrome.google.com/webstore/devconsole/). 

Second, I think [0x416c69](https://github.com/0x416c69) accurately summarized the reviewer's assessment in [this comment](https://github.com/uBlockOrigin/uBlock-issues/issues/2344#issuecomment-1295082024): the part about the use of "free", not the part about it being "just some trolls on Google's part". The use of "free" is not forbidden; the original verdict was a bit overzealous. We sometimes make mistakes, but we don't intentionally troll devs. 😅

Third, if you encounter issues with the CWS review process in the future I'd recommend reaching out to developer support using our [One Stop Support](https://support.google.com/chrome_webstore/contact/one_stop_support) form. That page is also linked from the original email in the "Do you believe this was a mistake" section near the bottom. The uBO community is large and passionate enough that the issues this project encounters tend to get _someone's_ attention internally and escalate from there. That said, it can take longer to resolve that way and (more importantly) using that form is the most direct and effective way for basically any other extension to appeal a verdict or let us know we made a mistake.

**Comment by krystian3w** [comment]
Complete gone on 2024 (with enterprise polices).

**Comment by gorhill** [comment]
@dotproto 

Thanks for dropping by.

> have you received an email to that effect?

No email -- including a daily check of junk folder. Happy to hear the required action has been dropped.

> recommend reaching out to developer support using our [One Stop Support](https://support.google.com/chrome_webstore/contact/one_stop_support) form

That's what I did, which led me to the "Deceptive behavior" section I mention in the opening comment. However I did not go further with _"Do you require more help?"_ as I didn't see the point of arguing the obvious that there was no deception.

**Comment by dotproto** [comment]
> No email -- including a daily check of junk folder. 

Thanks for the confirmation. I'll look more into this on my end.

> However I did not go further with "Do you require more help?" as I didn't see the point of arguing the obvious that there was no deception.

From my perspective the point is that we're (clearly) not perfect and that by letting us know we made a mistake we can prevent that mistake from affecting your users. That said, I know you've had your fair share of frustrating experiences with our review process and empathize with your position.
