### ISSUE TITLE
uBo broken after adding a large host file

### ISSUE THREAD

**Issue by User6751** [uBlockOrigin/uBlock-issues#2443]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After adding a large host file, uBo can't work anymore

### A specific URL where the issue occurs.

google.com

### Steps to Reproduce

1. add https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/ultimate.txt to uBo
2. the tablet do not respond
3. close the tablet  and re open screen until it respond
4. click other pane 
5. uBo broken

### Expected behavior

uBo work normally

### Actual behavior

uBo don't respond anymore, can't open website.

![Screenshot_20230104-181442_Firefox](https://user-images.githubusercontent.com/120245025/210534586-0748b28a-656a-49ed-a9fb-8493c82b78bc.jpg)
![Screenshot_20230104-181452_Firefox](https://user-images.githubusercontent.com/120245025/210534597-5acb8905-9d26-4d1c-be9f-7672844e9209.jpg)

after closing the uBo and re open it
![Screenshot_20230104-181713_Firefox](https://user-images.githubusercontent.com/120245025/210534673-45f8b166-d8e9-4536-b990-c4d5c0500bee.jpg)
![Screenshot_20230104-181526_Firefox](https://user-images.githubusercontent.com/120245025/210534681-cd4c60bb-7f23-4d82-be9d-24b1918c0458.jpg)

website will not load anymore
![Screenshot_20230104-182647_Firefox](https://user-images.githubusercontent.com/120245025/210535286-c513f4ac-b5dc-492f-99ea-6490b22e03ce.jpg)

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Firefox Mobile 108.1.0

### Operating System and version

Android 10

**Comment by gwarser** [comment]
uBO is using 8GB of RAM when parsing this list on desktop in Nightly.

**Comment by gorhill** [comment]
The list is ~67 MB and loads fine in Chromium/Firefox, but there is a delay before it's all parsed and loaded in memory, during which time uBO will be unresponsive -- there are 2.2 M entries in that list.

Loading that list into a browser tab causes the tab to crash in Chromium, and the rendering to be broken in Firefox, so even the browsers have issues with loading that list as a document.

You are trying to load the same list in a browser on a device with performance limitations, so you will have to wait much, much longer for the list to be parsed and loaded in memory. The workaround is to not use such huge list on Android.

When loaded in Chromium/Firefox, the lists takes long to be parsed and loaded, and such list will also be impractical on desktop because the same process of parsing/loading in memory will occur every times the list updates. Once it's parsed and loaded in memory, the browser loads page fine with no performance hit to CPU usage, though uBO will use more memory of course, but nothing undue. Once uBO emit a selfie, uBO still loads under a second, and memory usage is still lower than some other top blockers with only their default lists.

Don't use such huge list in uBO in Android version of the browsers.

**Comment by garry-ut99** [comment]
uBO is a very fast and optimized program, the culprits for the performance problems when loading larger lists are buggy browsers and weak/cheap tablets/smartphones from the marketplaces.

The huge host list takes only 10-20 secs to load on my Win 7 PC, while it took several minutes on an old and weak smartphone and required clicking continue "unresponsive script" dialog several times, but finally loaded fine and I could browse webpages with no issues !

> gorhill: Loading that list into a browser tab causes the tab to crash in Chromium, and the rendering to be broken in Firefox, so even the browsers have issues with loading that list as a document.

I agree, on my Win 7 PC on Opera, it's loading 30 secs, and then the tab always crashes after exceeding insane 4 GB of memory. On Firefox, it takes 20 secs loading, max memory during loading is 1 GB, rendering problems appear, but they completely dissappeared after next 20 secs.

> gwarser: uBO is using 8GB of RAM when parsing this list on desktop in Nightly.

Wow, really insane, on Firefox 108.0.1 it takes 1 GB for me on Win 7. Another insane thing is Opera/Chromium eating 4 GB when loading the list into a browser tab and  then crashing...

**Comment by gorhill** [comment]
@gwarser How did you get that _Memory_ graph in your profiling results? I can't see this on my side and there seem to be no options to have that. In any case, when eye-balling Extensions process in `about:processed`, it seems the process peaked at just below ~1GB before the memory being garbage collected.

**Comment by gwarser** [comment]
I've had profiler set to Custom preset, but it seems to work with "Nightly" ("Browser"?) preset. It's just another track.

**Comment by garry-ut99** [comment]
It's available only in Nightly: https://profiler.firefox.com/docs/#/./memory-allocation
