### ISSUE TITLE
Created a Norwegian translation of the README file

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#247]
In the same manner as the Korean, Chinese and Portuguese translations of the uBO repo's Readme file, I decided to create one myself, for Norwegian: https://github.com/DandelionSprout/NanoCore/blob/patch-2/README.md

Yes, I know, I know. The filename claims that it's from Nano Adblocker. But it isn't, as GitHub seems to think that my forks of uBO's and Nano's repos come from the same repo.

Is this translation good enough for you guys to link to it in https://github.com/gorhill/uBlock/blob/master/README.md#ublock-origin, or does it need any changes to it?

**Comment by LEISER307** [comment]
How to block such a multi generator
generates a different name after refreshing the page or blocking this line
```
site.com##.ffs7Pz1pT3z1RbiMhV5vdy.neke
site.com##.ffs7Pz1pT3z1RbiMhV5vdy.keke
site.com##.ffs7Pz1pT3z1RbiMhV5vdy.xeke
site.com##.ffs7Pz1pT3z1RbiMhV5vdy.peke
```

**Comment by gorhill** [comment]
> same manner as the Korean, Chinese and Portuguese translations of the uBO repo's Readme file

I removed links to those translations a long while ago, because it's a maintenance burden, as I have no idea whether what is linked is up to date and valid. People who wants a translation from English can use a translation extension in their browser to ensure whatever they read reflect the current state of the project.
