### ISSUE TITLE
"Update now" button flashes for 1 second before changing the count numbers

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#248]
### Description

This I do not consider a problem, but something annoying. After checking all filter lists for "Force update", then "Update now" and notice that the "Update now" button flashes for 1 second before changing the count numbers of: Network filters + Cosmetic filters.

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox 62.0.2
* Operating System and version: Windows 8.1

**Comment by MS-PC** [comment]
Taking advantage of the fact that this issue is open, it could also be corrected to show the translation "uBlock Origin (off)", specifically "off".

**Comment by uBlock-user** [comment]
seen since the beginning, thought this was by-design.

**Comment by gorhill** [comment]
Notes for future reference when I forget why this happened:

The glitch occurs before the last "asset updated" notification occurs, _and_ after the "all assets updated" notification occurs.

The last "asset updated" notification occurs before the "all assets updated" notification because "asset updated" is fired _after_ the data has been confirmed written to cache storage, while the "all assets updated" is fired as soon as the asset is successfully downloaded (i.e. before it is actually written to cache storage).

The fix will be to fire "asset updated" without waiting for confirmation that the asset's content has been effectively written to cache storage.

**Comment by MS-PC** [comment]
@gorhill I had the same problem in version 1.18.0, solved in version 1.17.4. Same steps
