### ISSUE TITLE
Persist position of exclamation point in filters when toggling comment status

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlockOrigin/uBlock-issues#2543]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I maintain a large uBO filter list.  Leading spaces are used to improve readability of the filter list, and in particular, of disabled filters. For example:
```
    ! if use this filter, will break xyz
      ! ||example.com/abc
```

Using the tab button to comment/uncomment such lines moves the position of the exclamation point.  Would it be possible/reasonable to have uBO not lose the position of the exclamation point?

### A specific URL where the issue occurs.

https://www.example.com

### Steps to Reproduce

1. Enter these filters:
```
    ! if use this filter, will break xyz
      ! ||example.com/abc
```
2. Go to the second line
3. Press the `tab` keyboard key
4. Press the `tab` keyboard key again

### Expected behavior

The exclamation point to not move.

### Actual behavior

The exclamation point moves.

### uBO version

1.47.4

### Browser name and version

Firefox 110.0.1

### Operating System and version

Linux

**Comment by gwarser** [comment]
What is wrong with:

    ! if use this filter, will break xyz
    !    ||example.com/abc

?

**Comment by Gitoffthelawn** [comment]
@gwarser Syntactically, nothing is wrong with that at all.  But when using different levels of indentation to differentiate filters of different types/groups, adding the leading exclamation point interferes with the visual flow and ease of quickly discerning a group of related filters.  It's why when creating a bulleted list of items in a word processor, the bullets get indented with each item instead of all being left-justified.

**Comment by gwarser** [comment]
[ABP:](https://help.adblockplus.org/hc/en-us/articles/360062733293#comments)

>Any rule that starts with an exclamation mark (!) is considered a comment.

Editor does not allow to type space in empty box. Spaces are stripped when filter is added.

[AdGuard:](https://adguard.com/kb/general/ad-filtering/create-own-filters/#comments)

>Any line that starts with an exclamation mark is a comment.

![image](https://user-images.githubusercontent.com/886325/225237814-3bb95349-ec87-475f-9eb8-094de7c65b4b.png)

(Wondering if it's only syntax highlighting)

(Personally, I think that syntax with leading spaces should not be supported)

**Comment by garry-ut99** [comment]
Currently the editor simply adds an exclamation mark at the beginning when commenting out a filter, and thanks to this spimplicity, it's easy and bug resistant. What OP asks for, is a Python-like indentation, and would require to rewrite the editor and to add complexity to handle several  additional cases, the Python-like indentation introduces:
- it would require the editor to remember/save a position of an exclamation point and all the prepending  characters for every particular line, before commenting out, to be possible to recover it at the same exact position
- another thing is that if between commenting  & uncommenting a given line, content of the editor changes: some lines added, some removed, so that the current line changes it's vertical position, the editor will have to revalidate a position of the current line again, which means the editor will have to remember positions of all the commented lines too
- another case is that the editor will have to handle various cases when a content of the current commened out line changes (intentionally or mistakenly) before uncommenting it, for example: some characters added / removed or replaced, before a position of the exclamation mark
- there may also be unexpected cases that the editor will be unable handle or can't predict them, thus a risk of bugs increases

**Comment by Gitoffthelawn** [comment]
@garry-ut99 I think that's likely overkill.  Simply remember the position until the user leaves the current line.  That will handle 99% of the need without creating 99% of the potential complexity and edge cases.

**Comment by garry-ut99** [comment]
Does that mean that:
- after reading my comment you has changed your request/mind from "remember permanently" to "remember temporarily"
- or you forgot to mention previoulsly in your issue that you wanted it to be temporarily only, since the beginning

 <br>

And how you calculated those 99%.

**Comment by gorhill** [comment]
I prefer to decline, I don't see myself spending time on this just for the sake of one user.
