### ISSUE TITLE
Remember and reuse last position/size of the logger popup window

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#256]
I was wondering if you can also set in the logger window in maximized just like Firefox. Since it is uncomfortable to maximize the logger window every time. Since the window is small, and does not show much. It's just a suggestion.

**Comment by gorhill** [comment]
The browser set the size of the logger window, I prefer to keep it this way.

**Comment by gorhill** [comment]
Actually, what I could try to do (need experimentation) is to restore the position/size of the logger popup window that last time it was used.

**Comment by gorhill** [comment]
Unfortunately it does not work perfectly with Chromium, the restored position is a bit offset from what it was last time. It seems Chromium is not returning to proper value in [`chrome.window.get()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/get) for the `left` and `top` position -- I consider this a browser issue. The same code work fine with Firefox.

**Comment by gwarser** [comment]
In Firefox, when title bar is disabled, if I close main window and then logger, on next start logger window is also without title bar.

![image](https://user-images.githubusercontent.com/886325/50190719-a26be300-032a-11e9-86e2-3d8a79bf64e5.png)
 
It's OK on stable, because buttons in top right corner are still visible, but on beta and Nightly they sometimes disappear. 

![image](https://user-images.githubusercontent.com/886325/50190827-0ee6e200-032b-11e9-9d32-b787cc7f8888.png)

**Comment by gwarser** [comment]
Hmmm. This is not about Firefox stable/beta, but uBO stable/dev

**Comment by gorhill** [comment]
How do you disable the title bar?

**Comment by gwarser** [comment]
Right click on toolbar, select "Customize", in new tab bottom left corner.

**Comment by krystian3w** [comment]
Try recover session Firefox with opened logger, for my side comeback uBO logger as maximalized.
