### ISSUE TITLE
[feat request] allow sending filters/rules to list keepers

### ISSUE THREAD

**Issue by zsg100** [uBlockOrigin/uBlock-issues#2575]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi! 

This is my first ever contribution, so I'm sorry if this is out of place.

The idea is to crowd source list keeping.
uBlock could provide ways for users to send their own filters and rules to list keepers, helping them achieve more comprehensive and perhaps more timely data.

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

.

### Browser name and version

.

### Operating System and version

.

**Comment by gwarser** [comment]
You can already share your filters when reporting an issue using the ["Report an issue..."](https://github.com/uBlockOrigin/uBlock-issues/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website) button. Or use the "Home" icon next to a filter list name to go directly to the specific filter list home page, where you can report issues. 

There is not a much more uBO can do, because it does not have its own server (privacy/security/man power issues). Also, filters must be reviewed by maintainers anyway, so it cannot be: click -> a new filter lands in the filter list.

Or maybe you are imagining this in some other way, then you need to describe it in more detail.

**Comment by gorhill** [comment]
Having filter list maintainers receive list of filters out of context with no detailed explanations of why each filter exists and no detailed repro steps for exact sites to validate why each of them is needed is not how filter lists are maintained. Every single case to create a filter needs to be investigated by filter list maintainers so that the best solution is reached. A filter list that would just blindly assemble filters from various source into a filter list would result in a very low quality filter list.

The best tool to develop high quality filter lists is for users to report filter issues using the chat icon in the popup panel.

**Comment by krystian3w** [comment]
Worse if maintainer don't have github account and don't want register on MS portal.
