### ISSUE TITLE
disable only some filter lists on a website

### ISSUE THREAD

**Issue by CrazyPython** [uBlockOrigin/uBlock-issues#267]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

I want to disable only some filter lists on a website. For example, I might want to disable EasyList to allow ads but not the other privacy lists.

I believe this follows "The user decides what web content is acceptable or not in their browser." and  "Users are best placed to know what is or is not acceptable to them. uBlock's sole purpose is to give users the means to enforce their own choices."

### A specific URL where the issue occurs

use case example: https://www.economist.com/

multiple tracking sites, ads, high-quality content

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
Declined, it's technically the opposite of trivial.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
Excuse me for bringing up this issue

i had a suggestion about this issue and also a question.

As English isn't my native language, do you mean it will make users confuse?
or you mean it is difficult to implant?

if your concern here is UX, i have a suggestion for it that may be useful
you can let users enable/disable groups of filterlists for example several buttons in that mini menu that appear when ublock button clicked. 

I mean for example having several buttons on that menu with this names:
- a slider (button) for enable/disable ad filters
- a slider (button) for enable/disable annoyance filters
- a slider (button) for enable/disable hosts filters
- a slider (button) for enable/disable tracking protection filters

(all filters will only for that specific website like the main on/off button so there won't be any conflics and confusing)

Also you can combine the buttons for better UX for ex:
- enable/disable ad + hosts filters
- enable/disable annoyance filters
- enable/disable privacy filters

i think there isn't reason to put button for malware filterlists because user enabled them for protection and the likelihood of that filter causing conflicts and issues is very low.

Also you can let user to put its custom filters in some groups for using them in this menu and also may be you may want to let user customize what groups he/she wants to put button for it in the menu.
for example a user may have many dedicated filterlist for coin miners and want to put all of them in a new group named "miners" or a user have many filterlists for annoyance and wan to put all of them in annoyance button.

this option will be really usefull and win-win solution for both users and websites owners but in the end this is a suggestion and you have more knowledge about users/ux and ... and you know better.

Thanks

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/91

**Comment by geekley** [comment]
> Declined, it's technically the opposite of trivial.

@gorhill May I ask why? If you don't mind, that is.
I understand it's not trivial at all. But is it that complicated? At least to conceptualize?
Do you intend to ever implementing it at some point in the future, maybe?

From what I see, the steps to implement just the core functionality (no UI) would be:

1. Code assigning the built-in lists to a "group id" (ads, privacy, malware, etc).
2. New whitelist syntax allowing partial whitelisting.
    E.g.: `@ads::example.com` whitelists only ad-blocking lists ("ads" group id) on example.com.
3. Code for matching a page against whitelist entries also returns the groups ids whitelisted, if any. E.g.: Page "example.com/somepage" -> Allow groups `['ads']`
4. If page is partially whitelisted (it returned group ids), handling of resources is as follows:
    - When uBO detects that a requested resource matches a blocking pattern:
    Get the list that blocked it, then its group id.
    (Since uBO has that event log, I presume that it wouldn't be too hard to make pattern matcher also return the id of list containing that pattern - and if getting that is somehow less efficient, it's still pre-known that this method of handling it is just a special case anyways)
    - If the list's group is whitelisted on the page, don't block the resource.

That would be enough for implementing the core functionality.
The things I mentioned in #1109 about UI (lower priority) could be optionally made after, if desired.

5. Code and UI to edit grouping of lists, to make it work for custom lists (not just the ones built-in).
6. Code and UI for the group toggles in the popup, to allow easily enabling those, and handle inclusion in whitelist.

Sorry if my understanding is completely wrong, or if I missed important steps.
But, if you ever decide to make it, maybe this helps, I hope?

**Comment by Yuki2718** [comment]
>     4. If page is partially whitelisted (it returned group ids), handling of resources is as follows:
>        
>        * When uBO detects that a requested resource matches a blocking pattern:
>          Get the list that blocked it, then its group id.
>          (Since uBO has that event log, I presume that it wouldn't be too hard to make pattern matcher also return the id of list containing that pattern - and if getting that is somehow less efficient, it's still pre-known that this method of handling it is just a special case anyways)
>        * If the list's group is whitelisted on the page, don't block the resource.
> 
 
uBO's matching doesn't work like you think. It uses only ONE list that is compiled on browser launch or filter updates (redundant rules are discarded here), then uses this list to match requests to. Only chance uBO knows from which list a rule came is when you click a logger entry, upon which uBO performs reverse lookup. Your suggestion requires reverse lookup before matching which slows down the process with little benefit, even if it's trivial to implement. For your purpose of allowing ads and not tracker, use dynamic rules - tho dynamic allow will be removed due to misuse, those who know what you're doing can still use it. It should not take too much time to search for which domain is mainly for ads and which is mainly for tracker. However, filter classification is not always that accurate, no wonder as some are both ads and trackers at the same time.

**Comment by geekley** [comment]
Thanks a lot for the clarifications, @Yuki2718 !

> It uses only ONE list that is compiled

Is the problem more about efficiency? Not sure if the result of compilation is like regexes or similar (it's probably very complex), but I suppose it's still possible to make that same compilation also produce an additional mapping like `patternPosition->listId` (can be a separate object). Would that be hard to implement? Maybe somewhere in the process you already have something for `patternPosition` and `listId` that is trivial to obtain and aggregate into an object during compilation.
If it's feasible, that would allow O(1) lookup for the group id (+ any other list property desired).

> slows down the process with little benefit

I think the ability of keeping at least the malware lists while disabling others is a significant security benefit. It even makes sense to keep those enabled, even for whitelisted sites.

In my opinion, uBO is already the best content blocker, but if this feature would make it be visibly far ahead every other alternative.
