### ISSUE TITLE
uBlock stops working after adding custom filter

### ISSUE THREAD

**Issue by ghost74747** [uBlockOrigin/uBlock-issues#2671]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello,
After adding one or more custom filters, ublock stops working.
If I disable the added custom filters, ublock works again.

I tried:
Reinstallation uBlock
Reinstallation Firefox

![adasd](https://i.postimg.cc/x8jxqwsy/adasd.png)

### A specific URL where the issue occurs.

All page

### Steps to Reproduce

1. I add a new custom filter
2. I open the page, but uBlock does not work

or...

1. I add a new custom filter
2. I close the browser, clearing the browsing data
3. I open the browser
4. I open the page, but uBlock does not work

or...

1. I add a new custom filter
2. I disable uBlock
3. I close the browser, clearing the browsing data
4. I open the browser
5. I turn on uBlock
6. I open the page, but uBlock does not work

### Expected behavior

Page will be loaded

### Actual behavior

Page not loading

### uBO version

1.49.2

### Browser name and version

Firefox 113

### Operating System and version

Android

**Comment by ghost74747** [comment]
"_All page_", I meant as all adress WWW, meaning it doesn't matter what page it is, it happens on all pages I open.
The same with the filter, which I would not install the situation is the same. The `adguard-annoyance` filter is only as an example.

```
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
  network: 93608
  cosmetic: 37747
  scriptlet: 17875
  html: 964
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 0-0, 11m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34809-412, 10m
    ublock-badware: 6950-1, 10m
    ublock-privacy: 373-1, 10m
    ublock-abuse: 70-0, 10m
    ublock-unbreak: 2015-2, 10m
    ublock-quick-fixes: 209-0, 10m
    adguard-mobile: 8797-121, 9m
    easylist: 65879-17388, 10m
    easyprivacy: 30899-1798, 10m
    urlhaus-1: 7286-1, 10m
    plowe-0: 3735-2, 9m
    POL-0: 7947-145, 9m
    POL-2: 1278-17, 9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 961 ms (selfie)
  maxAssetCacheWait: 128 ms
```

**Comment by gorhill** [comment]
> I will have to close this issue as invalid if you do not provide exact URL and filter.

You did not provide an exact webpage URL and an exact filter which you say "breaks uBO". Provide these in the next comment otherwise I will close the issue as invalid.

**Comment by ghost74747** [comment]
The site address nor the filter name has anything to do with this problem. It happens on all sites, regardless of the filter.

**Comment by gorhill** [comment]
The idea is that I want to go through the same steps as you do, so we can compare the same results. Last time I ask.

**Comment by gorhill** [comment]
Closing as _invalid_ since OP is not willing to make the case of his reported issue. Since no URL and custom filter were provided as asked, I created my own case, which worked all as expected:

- Navigate to`example.com`
- Launch element picker
- Select "Example Domain" header
- Click _Create_
- Reload the page: works as expected
- Quit Firefox for Android
- Launch Firefox for Android
- Navigate to `example.com`
- Page load, and the "Example Domain" header is filtered as expected.

**Comment by ghost74747** [comment]
Thanks for your professional help, now everything works great with AdGuard. Even additional filters don't need to be added manually, just move the checkbox.

**Comment by krystian3w** [comment]
It's your fault, because you made the filter/filter list pasted into the "import list" field as confidential.

To me, the descriptions looks like you used the "filter list" tab, rather than "my filters" or picker (🇵🇱 pipety/zablokuj element).

The list import mechanism can only be improved by knowing the problematic URL/string, which resisted the sanitization mechanism.

As for me, the problem seems too impossible for you to generate it at the level of "my filters" tab or picker by pasting there anything from the Internet advice.

---


In AdGuard you may also encounter the problem that the Filter List is not added to any of the groups and you have to add it manually to the subscription:

- in their GUI or

- from a working `abp:subscribe?location=URL` or `https://subscribe.adblockplus.org/?location=` link.

Their picker also does not create filters usefully: based on the `:nth-child` enumeration in the "CSS" path, where in uBo you immediately have a proposals and the option to build a shorter "CSS" path.
