### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by bfred-it** [uBlockOrigin/uBlock-issues#286]
I’d like to contribute a new UI for uBlock because I find the current one unclear in most cases. 

If you agree that there’s room for improvement I can propose a new UI for the popup and we can discuss it. 🙂

**Comment by uBlock-user** [comment]
Post your proposed UI changes and gorhill will respond.

**Comment by gorhill** [comment]
Keep in mind I constantly refrain from making big UI changes because I value stability in order to never force users to re-learn everything next time they launch uBO. When I modify the UI for whatever reason, I try to incrementally keep it to a minimum, the idea being that users have more important things to do than having to re-learn uBO when they launch their browser -- this is especially true for the most commonly used UI parts.
