### ISSUE TITLE
`trusted-set-cookie` can't be used to bypass some Cookie notices (and other elements).

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#2893]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I use Brave, and in Chromium (I don't know about Firefox), `document.cookie` when the site starts with `www.` the cookie will be set for the root domain as `www.example.com`, and sometimes the cookie is expected for all subdomains as `.example.com` for it to work.

That can be accomplished by adding `domain=example.com` to the document.cookie, the problem is that there is no way to do that with the set-cookie scriptlet, to make it put the cookie in the right 'domain' the site is expecting the cookie to be and therefore causing issues since it can't bypass easy cookie notices and stuff like that.

Today someone reported an issue with: `rts.ch`  and the site not displaying elements unless the cookie notice is accepted, and I saw that the issue was the whole `www.example.com` vs `.example.com`, which means the network connection that is blocked has to be completely allowed it for this website to work properly, `trusted-set-cookie can't be used for this`

So, this is basically the issue shown in the Devtools, where rts website will only read the cookies set in `.rts.ch` and not `www.rts.ch` domain.
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/148586312/31926cfb-ec50-4aa3-b692-1040b0ef80bb)

I made a workaround on my side, a quick and dirty/easy one to prove to you that the domain option is needed and it works. What I did was to modify the path argument to be able to add the domain if needed.
https://github.com/gorhill/uBlock/blob/f0cd93335ed26238373f5b150fe6f949b9c11380/assets/resources/scriptlets.js#L773C23-L773C23

This is all I changed to make it work:
```diff
- if ( path !== '' && path !== '/' ) { return; } 
+ if ( path !== '' && path !== '/' ) { cookieParts.push('; path=/', '; domain=', path); }
```
So I know it works and it's clear Domain option is needed in some cases just like Path and Expires and Reload option.
I decided to do it this way in the Path, instead of adding the domain argument like in the past, to keep compatibility with any existing rule already in place in the filter lists, while being able to add the domain option for the document.cookie to work properly if needed.
With my change, the rule ended up like `example.com##+js(trusted-set-cookie, CookieName, Value, , example.com)` to make the cookie be set in `.example.com` and not `www.example.com`,

Note: I want to make it clear that **this is not to set cookies in different domains, that's impossible for the browser to do anyway**, the cookie will be fail to set anyway, this is just to specify root vs subdomains in these cases of websites that start with `www.` like rts and so many, so the cookie will be read as expected because it is in the 'right place' the website is expecting the cookie to be.

### A specific URL where the issue occurs.

https://www.rts.ch/info/suisse/14378302-comment-la-suisse-evoluetelle-faites-notre-questionnaire-interactif.html

### Steps to Reproduce

0. Enable `EasyList/uBO – Cookie Notices` or add `||usercentrics.eu^$3p` to My Filters
1. Add these rules scriptlet injections rules:
   ```
   rts.ch##+js(trusted-set-cookie, rts-consent-cookie, essential%2CcustomCategory-37e8dfb9-5b08-4500-819f- 
   f838d37a030b%2CcustomCategory-c983c522-acc5-4cd4-bc4c-e6d79f26c390)
   rts.ch##+js(trusted-set-local-storage-item, uc_user_interaction, true)
   rts.ch##+js(trusted-set-local-storage-item, uc_settings, )
   ```
2. go to https://www.rts.ch/info/suisse/14378302-comment-la-suisse-evoluetelle-faites-notre-questionnaire-interactif.html
3. you should see the `Contenu externe`  and you can't click the accept button, it is been blocked by the adblocker.
4. go to Devtools and find the `rts-consent-cookie`
5. change the domain of the cookie from `www.rts.ch` to `.rts.ch`
6. refresh the site
7. now the notice is gone and you can see the media/graphic and it works as it should.

### Expected behavior

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/148586312/6e73baae-7b20-4324-a82a-4886efe9c47c)

### Actual behavior

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/148586312/e8baf13a-4904-4943-80dc-583c33e0a3e7)

### uBO version

1.52.2

### Browser name and version

Brave 1.61.38 Chromium: 118.0.5993.96 (Official Build) nightly (64-bit) 

### Operating System and version

Windows 11 2H22

**Comment by gorhill** [comment]
Are you suggesting to remove the `www` part as the default behavior?

**Comment by gwarser** [comment]
Do I understand correctly?

Visiting the `www.page.test` sets cookie for `www.page.test`, but it may in background request `consent.page.test` to check for cookie consent, and in this case cookies set on `www.page.test` will not be sent and check fails?

**Comment by gorhill** [comment]
Problem with removing `www.` is that `www.com` or whatever tld is a thing. The scriptlet does not have access to the public suffix list. But if the browser throws as a result of trying to set a cross-origin cookie, then I guess we can implement the suggestion.

**Comment by BraveUser-HGhost88-TEMP** [comment]
Yes, exactly, the problem is some pages like `www.page.test` cookies will be set in `www.page.test` and sometimes cookies are expected in `.page.test` like in the case of rts.ch to by pass the cookie notice.

when you don't specify a domain in document.cookie will add it as `www.` (or in most cases I have seen)
if you specify a domain, well, it needs to be valid to be set, if not nothing will happen.

I also don't think an Option, like reload or dontOverwrite is a possible in this case, since you have to specify a real domain, if not the cookie will fail to set, which means getting `rts.ch` and set it as domain from a URL like `https://www.rts.ch/info/suisse/14378302-comment-la-suisse-evoluetelle-faites-notre-questionnaire-interactif.html` means a lot of things when it is easier to just manually set it in a rule if needed.

In this case, domain.cookie output with `page.test##+js(trusted-set-cookie, CookieName, Value, , page.test)` would set the document.cookie as: `CookieName=Value; path=/; domain=page.test` and it will work.

And yes, about validness of domain in the document.cookie, well, first document.cookie will not set cookie if you try `page.test##+js(trusted-set-cookie, CookieName, Value, , example.com)`.

But about subdomains, you can use `brave.com##+js(trusted-set-cookie, safesearch, off, 1year, search.brave.com)` but it won't work in `brave.com`, it will only work if you go to `search.brave.com` because the browser doesn't even like what you are trying to do, even if it is a subdomain, it won't be set from the root or any other subdomain.

So Browsers already deal with this time of situation when wanting to set a cookie in what it thinks it is the incorrect domain, and if people want a cookie in a subdomain from the root domain, then `.domain.com` which means **all** subdomains is the only answer, talking about setting a cookie through JavaScript, of course.

**Comment by peace2000** [comment]
I have randomly seen issues with websites that `trusted-set-cookie` sets the cookie but it doesn't work even if the value and name are valid. Maybe this issue could be related to that.

**Comment by BraveUser-HGhost88-TEMP** [comment]
Thanks @gorhill! it is working great! didn't know it was that easy to add it as option, nice.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/148586312/f064519f-215e-4f81-be18-a38bef8f7f92)

BTW, this is Twitch:

`twitch.tv##+js(trusted-set-cookie, CookieName, Value, , , domain, .twitch.tv)` = `.twitch.tv`
`twitch.tv##+js(trusted-set-cookie, CookieName, Value)` or `, , domain)` = `www.twicth.tv`
And for whatever reason:
`twitch.tv##+js(trusted-set-cookie, CookieName, Value, , , domain, twitch.tv)` = `gql.twicth.tv`

👍👍

**Comment by gorhill** [comment]
For your original case, this works:

    rts.ch##+js(trusted-set-cookie-reload, rts-consent-cookie, essential%2CcustomCategory-37e8dfb9-5b08-4500-819f-f838d37a030b%2CcustomCategory-c983c522-acc5-4cd4-bc4c-e6d79f26c390, , , domain, rts.ch)

**Comment by BraveUser-HGhost88-TEMP** [comment]
Yes, I noticed it needed to be reloaded for it to work properly.
Sideloading scriptlets in Brave is kind of... interesting, so I only built the normal trusted-set-cookie, but using `trusted-set-cookie-reload` makes more sense if available.

thanks again! 👍

**Comment by gorhill** [comment]
> Sideloading scriptlets in Brave is kind of

No need, you can use the vararg `, reload, 1`, this should work:

    rts.ch##+js(trusted-set-cookie-reload, rts-consent-cookie, essential%2CcustomCategory-37e8dfb9-5b08-4500-819f-f838d37a030b%2CcustomCategory-c983c522-acc5-4cd4-bc4c-e6d79f26c390, , , domain, rts.ch, reload, 1)

**Comment by BraveUser-HGhost88-TEMP** [comment]
Oh, don't worry! I meant sideload uBlock scriptlets for Brave adblocker, I had to make sure everything is working there as well, so no issues happen if they push an update that can cause an issue, like once where Youtube completely broke, because ACS I think broke.
This way I don't wait 300 years for them to push the update, so using the `trusted-set-cookie` was the easier to test.

So not your problem, just something unrelated to uBlock. I could wait, but I won't wait, and since `-reload` will do the same as adding the option `reload, 1`, then I didn't care to use that one.

It just takes time because of the new `.fn` in the new uBlock scriptlets, Brave has to load each scriptlet, and each scriptlet has to include each individual dependency you add on it, there is a change in setCookieFn? well, 3 scriptlets have to be updated, and since you changed today the name to `setCookieFn` that also meant to change names to the other functions individually, and then encode it and place it in the json file.

As you can imagine, It is a lot of duplicate JS code, but it was the easier way for Brave to deal with it (I guess).

But making sure everything is okay and won't break takes time and the more dependencies a scriptlet has, the worst becomes to sideload, the good thing is set-cookie is a 'simple' one. but wanted to test it quickly.

Maybe you should learn RUST if you haven't, and work at Brave to improve the adblock-rust faster and everything will work just as it work in uBlock, so no more issues for me 'hacking' Brave adblocker to get the same functionality as uBlock lol 😁jkjk (half joking).

Take care Captain 🫡

**Comment by peace2000** [comment]
> For your original case, this works:
> 
> ```
> rts.ch##+js(trusted-set-cookie-reload, rts-consent-cookie, essential%2CcustomCategory-37e8dfb9-5b08-4500-819f-f838d37a030b%2CcustomCategory-c983c522-acc5-4cd4-bc4c-e6d79f26c390, , , domain, rts.ch)
> ```

How about making the switch more simpler?

Instead off:
`, domain, example.org`

How about:
`, nowww`
or
`, onlybase` (referring to the base domain)
or
`, nosubdomain`

@gorhil

**Comment by gorhill** [comment]
> How about making the switch more simpler and convenient?

a vararg is always a pair of values, otherwise it becomes impossible for the code to know what is a vararg name and what is a vararg value.

**Comment by gorhill** [comment]
Scriptlet does not know about what the base domain, it doesn't have access to the public suffix list.

**Comment by peace2000** [comment]
Could this be added to `set-cookie` as well? Now it's only for `trusted-set-cookie`.

**Comment by peace2000** [comment]
@MasterKia Don't know if that issue on that page (I can repro) is related to this domain-matter.

This doesn't work either:

`fplstatistics.co.uk##+js(trusted-set-cookie, OKCookie, 1, 1year, , reload, 1, domain, fplstatistics.co.uk)`

**Comment by gorhill** [comment]
When the cookie is not set, the site sends you to `/Home/ConsentMB?actionName=Top50Android`, and the only way to leave this page is by clicking the consent button, through JS code in the page. Using `, reload, 1` doesn't accomplish anything because the redirection is client side, and only through a click.

**Comment by krystian3w** [comment]
Clicker sometimes works at second visit, these maybe too can be improved?

**Comment by peace2000** [comment]
@MasterKia 

https://github.com/uBlockOrigin/uAssets/commit/3d6a6123ca239f84f6d6e45a470e0f3735779e19
