### ISSUE TITLE
Regex support for `urltransform`

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2924]
https://github.com/uBlockOrigin/uBlock-issues/discussions/2923:

I want to change `https://upera.shop/ref/3m8/ckz0oa1m` to `https://upera.shop/ckz0oa1m` to prevent tracking, but I can't do this using `$urltransform` since it doesn't support regex.

They're the download links here:
`https://www.doostihaa.com/post/1402/08/09/%d9%82%d8%b3%d9%85%d8%aa-18-%d9%85%da%af%d9%87-%d8%aa%d9%85%d9%88%d9%85-%d8%b9%d9%85%d8%b1-%da%86%d9%86%d8%af-%d8%aa%d8%a7-%d8%a8%d9%87%d8%a7%d8%b1%d9%87.html`

`3m8` is the tracking code for each site (many sites use the `upera.shop` download links).
`ckz0oa1m` is the video code.

### A specific URL where the issue occurs.

`https://upera.shop/ref/3m8/ckz0oa1m`

**Comment by gorhill** [comment]
What if `urltransform` use the same syntax as `replace=`:

    "/" regexp "/" replacement "/" modifiers

**Comment by u-RraaLL** [comment]
Is there any chance you'd consider either:
* Allowing subdomain changes,
* Forcing absolute links become relative?

Why I'm asking - a few days ago reddit made my account part of an experiment where they forced `sh.reddit.com` interface onto me. That interface is very incomplete and it made moderating quite difficult.

Other than contacting reddit to get to the bottom of it, I tried switching to the `new.reddit.com` domain. It worked only partially, because there's a number of absolute links used in that interface (including inside mod tools).

Before successfully making my case for getting me out of this experiment, I was considering my options and whether a userscript or installing Redirector was my only way out of this.  So I'm just wondering if there'd be a way of doing it with uBO.

Since this would surely involve a lot of work for little benefit, please treat this as more of a theoretical question than a serious request.

**Comment by anewuser** [comment]
@u-RraaLL If you use Firefox, I recommend [Request Control](https://addons.mozilla.org/addon/requestcontrol/) for this. The default example rules might be outdated, but it allows you to perform all sorts of advanced URL manipulations with very specific rules. I've created these for Old Reddit: [reddit.txt](https://github.com/uBlockOrigin/uBlock-issues/files/13257941/reddit.txt). If you want to play with them, go to the `Settings` tab and use the `Import rules` option.

**Comment by gorhill** [comment]
I won't change the requirement that the resulting transformed URL has to be on the same domain, there are extensions specialized in this, this doesn't have to be undertaken by uBO, this would just open the door to a huge amount of added burden to maintainers because it would become expected uBO replace those specialized extensions.

> Forcing absolute links become relative?

I don't understand that request, `urltransform=` works at the webRequest level, there are no relative URLs at that level.

**Comment by gorhill** [comment]
I commented in the past about why I see burden ahead with opening the door to "bypass url-based trackers", see <https://github.com/uBlockOrigin/uBlock-issues/issues/1784#issuecomment-954004343>. There will always be a case that is just one step away from whatever ability we add to `urltransform`, there will always be a request to extend to include that one-step-away case, and in the end `urltransform` will become an ugly pile of code to maintain. It's why I really see this as best taken care by a specialized extension.

**Comment by gwarser** [comment]
This is fixed now. `||youtube.com/shorts/$urltransform=/^\/shorts\/([^\/?]+)/\/watch?v=\$1/` works for YT shorts when navigated directly. @MasterKia ?
