### ISSUE TITLE
DOM Inspector issues on latest dev builds 1.54.1.*

### ISSUE THREAD

**Issue by u-RraaLL** [uBlockOrigin/uBlock-issues#3004]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On latest dev builds if you open DOM Inspector in a private window, nothing gets listed.
On b5, the page will display the page correctly, but disabling DOM Inspector will not reset the page layout back.

### A specific URL where the issue occurs.

https://www.reddit.com/r/uBlockOrigin/

### Steps to Reproduce

1. Make a new browser profile.
2. Install latest uBO dev version.
3. Open a private window.
4. Open reddit.
5. Launch logger>DOM Inspector.
6. Nothing is listed.
7. Disable DOM Inspector.
8. Page layout still shows the cosmetic filters preview.

### Expected behavior

DOM Inspector works as intended.

### Actual behavior

<details><summary>screeenshots</summary>

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/92610420/8796b2b5-974e-482c-bb26-f61dd49e3c01)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/92610420/e05c605d-89df-481a-a241-2a9db2965d8f)
</details>

### uBO version

1.54.1.5

### Browser name and version

FF 120

### Operating System and version

MX Linux 21.3

**Comment by avi12** [comment]
For me it fails in general
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/6422804/848f8731-2db2-46f9-be96-338c9bc69c3a)

**Comment by gwarser** [comment]
IndexedDB is working in 115esr. https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by gorhill** [comment]
Right but I think the idea of not allowing BroadcastChannel in private context is to avoid exfiltration to contexts which have no restriction on writing to storage, so really unrelated to <https://bugzilla.mozilla.org/show_bug.cgi?id=1639542>, since this one is just to make the storage _appear_ as working, in the end it still is restricted.

I definitely see that the broadcasted messages from the frame are not reaching the logger's broadcast message listener.

I probably should comment on <https://bugzilla.mozilla.org/show_bug.cgi?id=1401362> for confirmation, and if confirmed, should point out that extensions should be exempt from the block.

Anyway, meanwhile the fix would be to proxy the data from the frame intended for the logger to be proxied through uBO's main process. Unfortunate though, I liked the idea of direct communication between the frame and the logger without involving uBO's main process.

**Comment by u-RraaLL** [comment]
While DOM Inspector is running, Picker and Zapper don't work. And while Picker is open, DOM Inspector doesn't work.

**Comment by gorhill** [comment]
I don't think this ever worked, it does work with 1.54.0.

**Comment by u-RraaLL** [comment]
It definitely worked before. I often have DOM Inspector and picker open when creating filters for a website I'm filtering myself.

I just installed 1.54 on a new browser profile and it works fine for me there. Even zapper which I've never actually tested before (with DOM Inspector open).

**Comment by gorhill** [comment]
Just tested again and you're right. I think I must have enabled the wrong uBO version when I meant to enable 1.54.0.
