### ISSUE TITLE
"Apply changes" button can't be clicked while filter lists are updating

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#3066]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As the title says

### A specific URL where the issue occurs.

chrome-extension://EXTENSION-ID

### Steps to Reproduce

1. Click Update now, enable any of additional stock lists, and then Apply changes while lists are still updating

### Expected behavior

Able to click, as this had been the case

### Actual behavior

Not

### uBO version

1.55.1b0

### Browser name and version

Chrome 120.0.6099.200

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> Able to click, as this had been the case

Pretty sure "Apply changes" has always been disabled after clicking "Update now", it's not a new behavior.

**Comment by Yuki2718** [comment]
Hmm, confirmed. My bad.

**Comment by gorhill** [comment]
> My bad.

I am not saying the current behavior is ok, just saying it's not a regression.

**Comment by gorhill** [comment]
There is a quirk I want to look into following the fix here.

If you enable many new filter lists, clicking "Apply changes" mark them all as out of date, and seemingly nothing happens from the user's point of view. After a while the pane will refresh and show all as expected. The delay where nothing happen is not a good user experience. When enabling a new list, clicking "Apply changes" should result in the same behavior as if updating since the list has to be fetched from a remote server, same as when updating.

**Comment by u-RraaLL** [comment]
I think the `Update` button should also animate when `Apply changes` is pressed (for new lists).

Since it stays "active", users might think there's still something to update and try pressing it. But the button is unresponsive while new lists are getting downloaded. Animating it as if when pressed would take care of that.
