### ISSUE TITLE
BUG missing purge cached filter lists

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [uBlockOrigin/uBlock-issues#3090]
Hello!

Version 1.55.0 waterfox newest.
Just wanted to purge cached filter lists and the button next to 
[Apply-changed][Update now] is missing. 
Any news about that?

Thank you for your work!

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/1995cww/why_purge_all_caches_is_now_removed_from_ubo/

**Comment by gorhill** [comment]
@hetszunyukapanyanyimonyok What specific issue (provide all details please) are you having that you think that button would solve?

**Comment by hetszunyukapanyanyimonyok** [comment]
Thanks, I have read it searched before "purged".

**Comment by garry-ut99** [comment]
Cheap excuse or poor searching, I wonder how you were smart enought to bypass the issue template, and at the same time not smart enought to find many duplicate issues, but you're asking for a fish so nicely, that it seems everyone will forgive you anyway.

**Comment by garry-ut99** [comment]
To whoever has hidden my comment: stop disrespectfully hiding my comments, are you feeling better now? My comment was a peaceful/sarcastic reply, I just stated few facts and I let it go, because the guy was nice, but you are hallucinating/overreacting and you have had to hide it for whatever weird reasons you imagined in your head, if you prefer some noob, than a several years contributor, then maybe go and marry this noob.

Now what? Let me guess, you lack arguments, and you will provide (or not) some crappy reply, to which you will not let me respond to, like usual, and you gonna hide this comment too? Or even remove it? Or maybe lock the thread? Or ban me? Or you'll take out your gun and shoot me? Take your mental meds, bro, before it's too late, I wonder who has hidden my comment this time, the previous time was here : https://github.com/garry-ut99/test/issues/1#issuecomment-1859283657

**Comment by garry-ut99** [comment]
Not spam, stupid fake-labelling, I was provoked because my comment was hidden > then I replied and said to not disrespect me > then I have been disrespected even more by marking my reply stupidly as spam > now my reply again, see I only keep defending against your provocations, it's always someone else who starts hiding my comments for some strange reasons, then you're acting like it was me who causes the shit-show, I'm not your dog, stop abusing me, let me guess, you're going to hide my comment again with some stupid label sticked again, or maybe you will remove comment this time or lock thread, I DON'T GIVE A FCK.
