### ISSUE TITLE
Purge All Cache is gone

### ISSUE THREAD

**Issue by PandaBot2001** [uBlockOrigin/uBlock-issues#3112]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I'm trying to purge all cache in Ublock and I've googled the issue and it seems like in the last month, a lot of people lost the ability to purge their cache.
The button is just gone.

### A specific URL where the issue occurs.

```yaml
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#settings.html
```

### Steps to Reproduce

There were no steps.

### Expected behavior

The button to purge cache should be there.

### Actual behavior

The button to purge cache is gone.

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122440
 cosmetic: 45424
 scriptlet: 20422
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80401-14, 3m Δ
  easyprivacy: 50143-36, 3m Δ
  plowe-0: 3786-1183, 7d.16h.5m
  ublock-badware: 7849-140, 3m Δ
  ublock-filters: 37159-211, 3m Δ
  ublock-privacy: 998-6, 3m Δ
  ublock-quick-fixes: 199-4, 3m Δ
  ublock-unbreak: 2206-32, 3m Δ
  urlhaus-1: 7320-0, 15h.46m
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 391 ms (selfie)
 maxAssetCacheWait: 131 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by iam-py-test** [comment]
[It was removed in 1.55.1b28 (and in the stable release after that)](https://github.com/gorhill/uBlock/commit/bd7ce41224) for good reason. uBlock Origin's filterlists already automatically update often, but they use a technology called "differential filterlist updates" to reduce the load on the servers. The "Purge all caches" button bypasses that technology, and puts more load on the servers.
Thanks

**Comment by u-RraaLL** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/1995cww/why_purge_all_caches_is_now_removed_from_ubo/

**Comment by PandaBot2001** [comment]
Oh, it's just that it made the filter list work consistently, and if a site
detected adblock, purging the list allowed it to work again.

**Comment by gorhill** [comment]
> purging the list allowed it to work again

The only way it "worked again" is when volunteers added filters to solve an issue, otherwise this accomplished nothing -- the button was not a magic wand solving issues on it's own without intervention of volunteers. Now when you report an issue we tell you whether it's fixed or not, and if it is fixed, we will provide you a link to click to update only what is necessary for you to get the fix. Given that the lists now update every few hours instead of every few days, the update button has become pointless.

Really I am just repeating what is being said at the links you were provided.

**Comment by gwarser** [comment]
Wondering if it would be possible to have a bot which will respond in issue with an update link.

**Comment by Sometimes-The-Dragon-Wins** [comment]
> The only way it "worked again" is when volunteers added filters to solve an issue, otherwise this accomplished nothing -- the button was not a magic wand solving issues on it's own without intervention of volunteers.

gorhill, whats wrong man?

**Comment by FinrodFaithful** [comment]
I miss the purge button too, because whenever I'm backing up my uBlock settings, the first thing I used to do was purge and update all the filter lists, and check to see my active versus total filters.

**Comment by FinrodFaithful** [comment]
By the way, I've given up on trying to find gorhill's most recent filter lists and rule sets for browsing websites like Facebook, LinkedIn, etc.  I'm not a programmer, so I used to just download them from gorhill's Wiki on GitHub and follow The Hated One's advice, because the Hated One's advice was the easiest to follow for using uBlock Origin and uMatrix to block ads and scripts, and harden up the security on all my browsers.  (See https://www.youtube.com/watch?v=2lisQQmWQkY)  I suspect there's no more up-to-date, easy-to-follow advice like that any more from YouTube, and that weblink for "How to use uBlock Origin to protect your online privacy and security | uBlock Origin tutorial 2018" is now old.  That's dissapointing, but I still think Raymond Hill is a genius and probably has created the best ad blocking and script blocking extensions you can find, so I'm still using them, and desperately trying to find any way possible to keep them up-to-date on Firefox, Chrome and Chromium.

**Comment by FinrodFaithful** [comment]
I found this in an old version of uBlock Origin on Google Chrome:

Support --> Troubleshooting Info --> More --> Purge all caches.  

After the full purge, you’ll see your reduced memory usage.  But I don't know if that's useful any more, because I should probably switch to the latest uBlock extension.

**Comment by FinrodFaithful** [comment]
Updating filters used to be easy for me when uBlock Origin and uMatrix were actively supported for FF and Chrome, but I assumed I had to manually update the filter lists since circa 2023, like 2 or 3 at a time, which was painstaking, until I realized I can purge all the filters at once, as above.

**Comment by FinrodFaithful** [comment]
I wonder what happened to The Hated One?  He and gorhill are really the only security experts I trust, when it comes to safe and secure browsing.  I think they're both really thorough and diligent about online privacy and security.
