### ISSUE TITLE
Separate Social lists to independent section

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#3154]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Currently both AdGuard – Social Media and EasyList – Social Widgets are under Annoyances in Filter lists. I constantly see complaints that blocker hides sns buttons on Twitter, though most of them don't name which blocker they use and apparently many are either AdGuard (Social filter may be enabled depending on the installation process and products) and ABP (same). Those who check AdGuard – Annoyances and/or EasyList – Annoyances might not notice they include social lists.

### A specific URL where the issue occurs.

```yaml
chrome-extension://extensionID/dashboard.html#3p-filters.html
```

### Steps to Reproduce

Obvious

### Expected behavior

Social list should be in its own section

### Actual behavior

Not

### uBO version

1.56.0

### Browser name and version

Chrome 122.0.6261.95

### Operating System and version

Windows 10

**Comment by Yuki2718** [comment]
Some old complaints are in https://github.com/AdguardTeam/AdguardForWindows/issues/3776. I stopped adding new tweets as it's not my intention to bother AdGuard devs for all these, but it keeps happening.

**Comment by gwarser** [comment]
Maybe the section should expand when enabled?

**Comment by Yuki2718** [comment]
> Maybe the section should expand when enabled?

You can't enable without expanding first. I don't think that fully prevents people to enalbe social lists unknowingly. AdGuard Social is completely independent from the rest of Annoyances in the first place, though Fanboy Annoyances includes Fanboy Social.

**Comment by gorhill** [comment]
You mean a new section at same level as _Annoyances_, or a sub section under _Annoyances_?

**Comment by Yuki2718** [comment]
> You mean a new section at same level as _Annoyances_, or a sub section under _Annoyances_?

The former, with a label Social.

**Comment by gwarser** [comment]
> You can't enable without expanding first.

Ah, it's not like POL lists section. POL lists are selected by default for me and collapsed. "Annoyances" section is collapsed by default and I thought "AdGuard – Annoyances" is also collapsed, but it's not.

I think it's pointless to change it, because people likely select everything from top to bottom without even reading what it says.

**Comment by gorhill** [comment]
As part of the changes I already removed the default expanded state of AG/EL Annoyances section, but I could make the _Annoyances_ section itself expanded by default. Could be worth spinning off cookie notices-related lists in their own section as well since these are popular, and a lot of people have no idea uBO supports filtering out cookie notices.

**Comment by troysjanda** [comment]
Are the new sections supposed to be empty? the Cookie and Social I updated bur both have no lists in them.

**Comment by gorhill** [comment]
They will be populated once your `assets.dev.json` update.

**Comment by troysjanda** [comment]
Ok, that is done automatically? I'll check later.

**Comment by gorhill** [comment]
It is set to update every ~13 days.

These sections  should not be shown if they are empty, it's going to cause issues when releasing stable. I need to fix this.

**Comment by krystian3w** [comment]
IMO this break genesis of Fanboy Annoyances - these cut normaly socials + annoyances from one file.

**Comment by gorhill** [comment]
We are going to need spinning off a new `assets.json` for next stable release, maybe `assets.2.json` otherwise all versions before 1.57.0 will be broken by an `assets.json` with group names which are not built-in in those previous versions of uBO.

**Comment by Yuki2718** [comment]
Maybe related to this, but I got empty Filter lists which complains unsaved changes if I try to move to other tabs. I override with devbuild and no more complaints, but filters were still empty and I had to enable each list and settings one by one.

![ubo-1 56](https://github.com/uBlockOrigin/uBlock-issues/assets/58900598/63f5fae0-1778-4e73-a8ed-be230194d3a5)

**Comment by gorhill** [comment]
Stable release uses `assets.json`, and this one wasn't changed (yet). However, before I revisited how the changes to the categories should happen, I believe going from dev to stable could cause an issue because the then cached `assets.json` would be `assets.dev.json`, which contained values that would cause such breakage -- i.e. 1.56.0 isn't designed to deal with unexpected categories. But I revisited all this and going back and forth should work fine now with the new `assets.dev.json` -- though I didn't test this yet.
