### ISSUE TITLE
Ubloc Origin is not working on gab.com

### ISSUE THREAD

**Issue by mark4th** [uBlockOrigin/uBlock-issues#3183]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have ZERO interest in checking all your asinine boxes so i just checked them all.  im reporting a bug do wtih it as you will

### A specific URL where the issue occurs.

```yaml
www.gab.com
```

### Steps to Reproduce

go to gab.com
cright click on any post
NO UBLOCK MENU ITEM

### Expected behavior

i expect the addon to work

### Actual behavior

it doesnt work

### uBO version

no idea

### Browser name and version

not saying

### Operating System and version

not saying im not being data mined im reporting a bug

**Comment by garry-ut99** [comment]
Given two facts :
1 I'm unable to reproduce your issue on several different browsers
2 also you didn't provide any required details to determine whether it's uBO issue or not

we can claim three other facts :
A] - we can say that your issue report is spam and speculation & blind guess as whether it's a uBO's bug or not.
B] - purpose of the checkboxes you ignored is to avoid issue tracker being spammed by duplicate / invalid issues not caused by uBO
C] - I can only speculate and guess that this is not a uBO's bug but rather something broken / misconfigured on your side which caused Element Picker to be disabled, and that you ignored not only checkboxes, but also the uBO official documentation : 
- https://github.com/gorhill/uBlock/wiki/Element-picker#element-picker-does-not-work-removed-element-reappears-when-you-reload-the-page
- https://github.com/gorhill/uBlock/wiki/The-context-menu

if additionally Element Picker icon is missing from uBO Popup, it's not uBO's bug either, jsut a feature :
- https://github.com/uBlockOrigin/uBlock-issues/issues/3179
