### ISSUE TITLE
Tabs crash on Chrome with STATUS_ACCESS_VIOLATION as of version 125.0.6415.0 of Chrome

### ISSUE THREAD

**Issue by qwer1304** [uBlockOrigin/uBlock-issues#3205]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As of version 125.0.6415.0 of Chrome tabs crash with Error code: STATUS_ACCESS_VIOLATION, e.g. on issues.chromium.org/issues. This is completely reproducible: turn the extension on on the site and the tab crashes, turn it off and no problem occurs.

### A specific URL where the issue occurs.

```yaml
issues.chromium.org/issues
```

### Steps to Reproduce

Install extension
Open site

### Expected behavior

Site should open

### Actual behavior

Tab with site crashes with Error code: STATUS_ACCESS_VIOLATION

### uBO version

1.57.0

### Browser name and version

Chrome 125.0.6415.0 (Official Build) canary (64-bit) (cohort: Clang-64) 

### Operating System and version

Windows 10 Home Version 10.0.19045 Build 19045

**Comment by gorhill** [comment]
Browser crashes have to be reported to browser devs -- moreso when this concerns the dev build of Chrome. uBO is HTML/CSS/JS, it's not supposed to crash the browser, the same way a webpage is not supposed to crash the browser.

**Comment by qwer1304** [comment]
It has been reported to the Chrome team. But if the extension doesn't work with the browser, then it cannot be used.

**Comment by gorhill** [comment]
Can you provide the link to the Chromium issue?

**Comment by qwer1304** [comment]
https://issues.chromium.org/issues/333967642

**Comment by gorhill** [comment]
> doesn't work with the browser, then it cannot be used

It works in stable release of browsers.

**Comment by qwer1304** [comment]
Yes. It's a regression as of 125.0.6415.0

**Comment by garry-ut99** [comment]
> Browser crashes have to be reported to browser devs (...)

Yes, but sometimes they turn out to be useful when additionaly reported on uBO tracker, because sometimes they are addressed additionally on uBO side:
`https://github.com/gorhill/uBlock/issues/533`
`https://github.com/uBlockOrigin/uBlock-issues/issues/9`

**Comment by gorhill** [comment]
These were special builds of Chromium, not official Google Chrome. It's often been said here, the Google Chrome Canary is not officially supported because it's too unstable.

**Comment by garry-ut99** [comment]
True, but I was speaking in general (just like you in your first comment) despite the examples were about dev builds only indeed, because same crash story might happen with official builds, which will be addressed on uBO side, although I haven't found any similiar cases so far, anyway it's good that you've mentioned that dev builds should not be reported at all, which I had forgotten about.

**Comment by gorhill** [comment]
Even that crash for which I cared to provide a workaround a long time ago in that unofficial build of Chromium is a browser issue, not a uBO issue. In no circumstance should the browser crash through mere HTML/CSS/JS. I made an exception in this one case but ultimately the issue should have been fixed in the browser. Such crashes are potential vectors for exploits.

**Comment by garry-ut99** [comment]
> but ultimately the issue should have been fixed in the browser. Such crashes are potential vectors for exploits.

To be clear: I agreed since the beginning, I nowhere said in my comment that it shouldn't be reported/fixed in a browser:
a] in my first comment I even agreed and said "_yes_", and then I said they can be  "_additionaly_ reported on uBO tracker" (to be addressed / workarounded temporarily if necessary / worth, until a proper fix lands in browser, which might take time)
b] in my second comment I said "which will be addressed on uBO side" I still meant the same what in the first comment, and not that it should be addressed only in uBO, sorry if I didn't make myself clearly enough

But even if you don't want any crash reports anymore on uBO tracker, I still do understand and I'm fine, they are more spam than useful, I just mentioned out of curiosity,  I didn't intend to change tracker rules, on the contrary, I always seconded declining crash reports: 
`https://github.com/uBlockOrigin/uBlock-issues/issues/2851#issuecomment-1751956983`
`https://github.com/uBlockOrigin/uAssets/issues/16613#issuecomment-1415835892`

**Comment by garry-ut99** [comment]
Oh, one more thing I had forgotten, given how many invalid crash issues land on uBO tracker, in that case would be useful to add to a statement or a checkbox to [uBO issue template](https://github.com/uBlockOrigin/uBlock-issues/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml), something like in https://github.com/uBlockOrigin/uBlock-issues/issues/3205#issuecomment-2053618513:

"Browser and website crashes have to be reported to browser devs, uBO is HTML/CSS/JS, it's not supposed to crash the browser, the same way a webpage is not supposed to crash the browser."
