### ISSUE TITLE
“My filters” tab isn’t scrollable in higher zoom rate

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uBlock-issues#3211]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

“My filters” tab isn’t scrollable in higher zoom rate (e.g. 150% on Firefox). After the addition of settings above the custom filters’ box in version 1.57.0, you can’t see it with this browser configuration, unless you zoom-out.

### A specific URL where the issue occurs.

```yaml
everywhere
```

### Steps to Reproduce

1. Open uBO settings
2. Zoom-in at 150% and above
3. Go to “My filters” tab

### Expected behavior

“My filters” tab is scrollable letting you to scroll down in order to access the custom filters’ box.

### Actual behavior

“My filters” tab isn’t scrollable (like other tabs) showing only custom filters’ settings.

### uBO version

1.57.2

### Browser name and version

Mozilla Firefox 115.9.1esr

### Operating System and version

Windows 7 32bit SP1

**Comment by gorhill** [comment]
Unable to reproduce with Firefox 124.0.

Please provide a screenshot to be sure I understand what you are describing.

**Comment by DimitrisKalaboukas** [comment]
@gorhill At 100% zoom rate:

![1](https://github.com/uBlockOrigin/uBlock-issues/assets/101707608/da1d27f1-2e86-4d4a-be0e-65d71f0017d4)

and at 150% zoom rate:

![2](https://github.com/uBlockOrigin/uBlock-issues/assets/101707608/d5aabb52-2663-460a-bda0-80db91f7450f)

E.g. in "Filter lists" tab it has scrollbar and can also be scrolled by mouse:

![3](https://github.com/uBlockOrigin/uBlock-issues/assets/101707608/6180b426-22ce-4162-b448-502da91148c1)

**Comment by gorhill** [comment]
What is the resolution of your display?

**Comment by DimitrisKalaboukas** [comment]
@gorhill 1024x720.

**Comment by u-RraaLL** [comment]
The issue may be your browser customization. There's supposed to be a "maximize" button on the left of the search box - see if it works even if you can't see it.

I need to zoom by 320% to wholly lose the text box from viewport and even then, using the button works. (But I can't reproduce the search box getting partially hidden like on your screenshot.)

**Comment by garry-ut99** [comment]
> 1024x720.

Looking at the screenshoots resolution it's 1280x720 (HD), with such resolution + menu toolbar & bookmarks toolbar  enabled, I can reproduce the issue at 170% zoom with **"text zoom only" feature disabled**, a fact that OP can reproduce at 150% zoom, is most likely caused by his additional Windows or Firefox theme modifications.

> The issue may be your browser customization. There's supposed to be a "maximize" button on the left of the search box - see if it works even if you can't see it.

The invisible uBO maximize viewport button is caused by Windows 7 "High contrast black theme": https://www.youtube.com/watch?v=OO8Zqh_FpCo but the button is still here and still does work, also browser's maximize/minimize/close buttons becomes flat, like on OP's screenshoots.

**Comment by gorhill** [comment]
I can reproduce when zooming above 300% on my side with a reduce window size. I have a local fix but I need to look more into it to see if this will break in other ways.

**Comment by garry-ut99** [comment]
> above 300%

I don't understand why you need so much given I can reproduce at 170% (on both Win 7 SP1 and Win 10 22H2).

**Comment by garry-ut99** [comment]
OK, I know why I could reproduce at 170%, it's because I also had Windows 7 system zoom set at 125% in Screen options, most likely OP did same too.

But then I double-checked the issue on Windows 10 22H2 without any system zoom modifications to be sure it's not caused by Win 7 system zoom, and I could still reproduce at 170%.

Then it has turned out it's caused by a fact I run Windows 10 22H2 in VM, so it seems VM somehow replicated Win 7 host 125% system zoom into virtual machine Windows 10.

Now I set Win 7 system zoom back to default 100% and I need 240% to reproduce.

This must be similar issue OP reported: https://answers.microsoft.com/en-us/windows/forum/all/changing-text-and-apps-size-to-125-zooms-in-the/d5507d37-8602-4078-b81a-853aed1b6cd6

**Comment by DimitrisKalaboukas** [comment]
I need this kind of display setup due to severe visual impairment, as many other people with similar difficulties. My fault, the display resolution I use is really 1280x720 with DPI scaling at 125%. I don’t have issues with any button (I’m aware of dark theme limitations in Windows 7) and my browser is always maximized.

**Comment by u-RraaLL** [comment]
> I don’t have issues with any button

There is a button that should work as a workaround for your issue. You just don't see it. Here:

<details><summary>screen recording</summary>

https://github.com/uBlockOrigin/uBlock-issues/assets/92610420/69aa59a9-6cd3-4737-9a06-84db3d3c7715
</details>
