### ISSUE TITLE
duplicateBuster bug

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#325]
Found this bug while making some changes in my own fork today.

`duplicateBuster.add()` is located on the wrong line in `skipGenericCompiledContent`. Thus duplicate specific cosmetics aren't detected with ignoreGenerics enabled.

Fix: instead of [the current line](https://github.com/gorhill/uBlock/blob/1.17.4/src/js/cosmetic-filtering.js#L858) it should be moved 8 lines earlier. This makes it the same as `fromCompiledContent` which is already correct.

**Comment by gorhill** [comment]
Sorry for marking as invalid, I had created a quick test case to validate the issue, and I the result was that the duplicate was seemingly detected. Turned out I had forgotten to disable the parsing generic cosmetic filtering, then I could see the duplicate not being discarded in the "Filter lists" pane.
