### ISSUE TITLE
Let user customize auto comment date format

### ISSUE THREAD

**Issue by danielwerg** [uBlockOrigin/uBlock-issues#3265]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Today I was creating new filter and notice that date in auto comments use different format and not ISO8601 anymore. Then I found https://github.com/gorhill/uBlock/commit/a5f6c35bb091d26693fd1f7986e499905b7b8e73 commit.

Can we get an option to customize date format or just use ISO8601?

### A specific URL where the issue occurs.

```yaml
https://github.com/uBlockOrigin/uBlock-issues/issues

any
```

### Steps to Reproduce

1. Start element picker
2. Pick any element
3. See date in auto comment

### Expected behavior

Being able to customize auto comment date or use ISO8601.

### Actual behavior

`Jun 5, 2024`

![2024-06-05_09-56-05](https://github.com/uBlockOrigin/uBlock-issues/assets/35052399/6c48fb17-acdf-448b-90ff-a54cee9cebf5)

### uBO version

1.58.0

### Browser name and version

firefox-126.0.1

### Operating System and version

linux

**Comment by danielwerg** [comment]
Wish it was `new Date().toLocaleDateString('en-SE', { dateStyle: 'short' })`.

**Comment by krystian3w** [comment]
Older method is bugged: https://github.com/gorhill/uBlock/commit/a5f6c35bb091d26693fd1f7986e499905b7b8e73

**Comment by milroneth** [comment]
Since this was removed in the first place because `toISOString()` also converts the timezone to UTC and trying to fix that manually can indeed introduce issues, the solution could be improved with `.replace('{{isodate}}', d.toLocaleDateString('en-SE', { dateStyle: 'short' }))` as @danielwerg suggested since Sweden uses the ISO format officially –or simply `.replace('{{isodate}}', d.toLocaleDateString('sv', { dateStyle: 'short'}))` because `en-SE` is a bit spotty– and `toLocaleDateString()` returns the date in the local timezone as opposed to `toISOString()`.

It's not a significant improvement, I personally don't much care if the dates end up written being in the previous day as much as I need the ISO format, but still it seems like a better solution with correct results.
