### ISSUE TITLE
Undo: uBlockOrigin/uBlock-issues (https://github.com/gorhill/uBlock/issues/3726)

### ISSUE THREAD

**Issue by ImprovedTube** [uBlockOrigin/uBlock-issues#3271]
> Reason: the new issue tracker allows me to grant full permissions to volunteers in processing issues without having to grant full commit rights to code repository.

( https://github.com/gorhill/uBlock/issues/3726 )

> Triage: Recommended for contributors who need to proactively manage issues, discussions, and pull requests without write access

https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

**Comment by garry-ut99** [comment]
> ImprovedTube : Triage (...)

Triage is too low, at least "Write", but your suggestion is pointless anyway, because:
-  filters repository ([uAssets](https://github.com/uBlockOrigin/uAssets/issues)) requires it's own separate Issues tracker and Discussions anyway, to avoid spamming [uBlock](https://github.com/uBlockOrigin/uBlock-issues/issues) repo by a lot of unwanted issues/discussions/questions/notifications related to filters/websites, and not to uBlock itself.
   - AdGuard did the same: created separately [AdGuard Browser Extension](https://github.com/AdguardTeam/AdguardBrowserExtension/issues) repo and [AdGuard Filters](https://github.com/AdguardTeam/AdguardFilters/issues) repo
- "Write" might still contain too many priviledges which uBO owner might not want to allow

**Comment by ImprovedTube** [comment]
hi @garry-ut99,

 can have labels semi-automatically to exclude or include them in certain 'uBlock-itself' views

 github.com/gorhill/uBlock/issues/3726 sounds like triage is all needed

**Comment by ImprovedTube** [comment]
hi @garry-ut99,

>at least "Write"

why? github.com/gorhill/uBlock/issues/3726 sounds like triage is all needed

**Comment by garry-ut99** [comment]
Because "Triage" can't do many actions which are often used by uAssets devs:
- Create, edit, delete labels
- Merge a pull request
- Edit and delete anyone's comments on commits, pull requests, and issues
- Transfer issues (see "Transferring an issue to another repository" for details)
- Push to (write) the person or team's assigned repositories

On the other hand "Write" can do the following which might be undesired as it most likely should be restricted to uBO owner:
- Create and edit releases
- Edit a repository's description
- Publish packages

**Comment by uBlock-user** [comment]
This is not up for discussion.
