### ISSUE TITLE
Element picker enhancement 

### ISSUE THREAD

**Issue by UnfortunateLiama** [uBlockOrigin/uBlock-issues#3498]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

For experienced users can the element picker mode include a force create filter ? would be much faster this way than to add it from the dashboard > my filters 😄

### A specific URL where the issue occurs.

```yaml
.
```

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.61.3b11

### Browser name and version

.

### Operating System and version

.

**Comment by u-RraaLL** [comment]
Please don't ignore the issue template and don't make us guess what you're refereeing to exactly.

What's wrong with the current [Create] button?

What are you trying to accomplish? Create filters that have 0 matches? The main problem with that is that picker fills in the domain for you. If it could now ignore matches, it wouldn't necessarily fill in the correct domain since the element could be in a subdocument instead of the main document. This is assuming you're talking about cosmetic filters.

If you're talking about network filters, use the logger instead.


Anyway, please edit your post to include all the info. What you're trying to achieve, where, what happens and what you think should happen instead, etc.

**Comment by gorhill** [comment]
Declined.  Feature request without actual, real world convincing use case are not considered.

**Comment by freezer2022** [comment]
Duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1292

Also semi-related:
- https://github.com/uBlockOrigin/uBlock-issues/issues/69
