### ISSUE TITLE
Proposal for integration/unit testing

### ISSUE THREAD

**Issue by geoffdutton** [uBlockOrigin/uBlock-issues#36]
@gorhill I'm not sure if this is something you're interested in, but here is my proposal for unit testing: https://github.com/geoffdutton/uBlock/tree/unit-tests-proposal
Here is the current diff: https://github.com/gorhill/uBlock/compare/master...geoffdutton:unit-tests-proposal?expand=1

I've written a few test cases, and would be happy to contribute more. I think it can help for two main reasons:
1. Preventing regressions
2. Refactoring code and trying performance improvements

Number 2 is especially nice, such as when parsing new filter syntaxes or running extreme scenarios.

I'd be happy to go into more detail on how to write tests, when to mock functions, how to mimic browser features, etc. I chose `jest` because it's fast, and you can mimic any browser like [here](https://github.com/geoffdutton/uBlock/blob/unit-tests-proposal/test/test-utils.js#L21).

Let me know if this is something you're interested in incorporating.

**Comment by jspenguin2017** [comment]
My 2 cents: 
Mocking `chrome` namespace is pretty difficult, have you considered [Puppeteer](https://github.com/GoogleChrome/puppeteer)? You probably would need Puppeteer for integration test anyway. 

> `//  I can't type µBlock...`

Same.

**Comment by gorhill** [comment]
Yes, I'm interested in this, thanks for starting this. Now, this is all new to me, so I need to find my way into all this. I git cloned your repo, and first thing is, how do I launch tests?

> `// I can't type µBlock...`

I use right-`Alt` + `m`, though maybe this works on my side because I use US intl keyboard with dead keys.

I saw that the build script needs `rm -r $DES/js/__tests__`, isn't possible to not copy `__tests__` in the first place by placing it outside `$DES/js/`?

**Comment by jspenguin2017** [comment]
> how do I launch tests?

First install Node.js: 
```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Then install dependencies: 
```
npm install
```

Then execute the test script: 
```
npm run-script test
```

**Comment by gorhill** [comment]
> That doesn't do anything on mine, I think that doesn't work for most people.

I could create an alias of `µBlock` => `uBlock`, with the long term goal of phasing out usage of `µBlock`.

**Comment by geoffdutton** [comment]
@jspenguin2017 I see what you're saying now. Yes, you are right on the need to test the full product in a real browser in an automated way. Puppeteer would be great for that, but I think lower level unit tests can be complimentary.

For example, looking at [this](https://github.com/gorhill/uBlock/blob/ec29c9a127342f6d250c41572017329c45aca0e5/src/js/pagestore.js#L548), I would need to do a lot of set up to make sure [incrementing by 2](https://github.com/gorhill/uBlock/blob/ec29c9a127342f6d250c41572017329c45aca0e5/src/js/pagestore.js#L585) is what I really want.

But now say I wanted to test the correct tab was actually reloaded when the refresh button is clicked in your screen shot, that would be a disaster to test using something like jest. You'd have to mock out the entire chrome messaging system and such.

Another great use case for Puppeteer is "visual regression" sort of testing such as testing css media queries on various view port sizes.

I will take a look at your repo and see if I have any ideas.

**Comment by jspenguin2017** [comment]
@geoffdutton My worry is that uBO isn't really built on functional programming; one functionality can span across multiple files. Ideally you want many small pure functions and a few big controllers to tie them together. This way you can optimize smaller functions without needing to worry about breaking stuff. 

But now it's too late to change, so we have to instead design tests around it. I checked your tests, I have to say they are not ideal. I don't have a better way but ideally you would run a function multiple times instead of `require` a file multiple time; that just look like a headache waiting to happen. 

Also for code like this, it just feel really fragile and hacky: 
```js
chrome.runtime.getManifest.mockReturnValue({ version: '1.1.1.1' });
```

**Comment by geoffdutton** [comment]
> one functionality can span across multiple files.
I guess I'd say that's why having unit tests in place to prove the "contract" of the functionality.

> Also for code like this, it just feel really fragile and hacky:
Well the only thing we care about is that it's 4 digits, but I can see what you're saying.

**Comment by uBlock-user** [comment]
> I use right-Alt + m,

On Windows, `Alt + 230` on numpad types `µ`

**Comment by jspenguin2017** [comment]
It's 181 for me. Could be font-dependent. 
![image](https://user-images.githubusercontent.com/7283682/39960683-1e952904-55e4-11e8-8d24-cf94f78a3e06.png)

**Comment by uBlock-user** [comment]
`Alt` + `0181` also works.

**Comment by sebast889** [comment]
Reason for close? @gorhill not wanting unit tests or just that this particular issue is not needed anymore?
