### ISSUE TITLE
"Block element" item should have ellipsis (usability)

### ISSUE THREAD

**Issue by Explorer09** [uBlockOrigin/uBlock-issues#360]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin's "Block element" item in the context menu should have an ellipsis, which is a UI convention of indicating "needs further user input (e.g. select which element to block and the block rules) before taking the action". Without the ellipsis the user may mistake that the block action happens immediately ("block element right under the cursor" or something).

### A specific URL where the issue occurs

Not specific to any web page. But I give a tutorial article for convenience:

http://technewslog.com/ublock-origin-how-to-remove-any-element-from-a-page-permanently/

### Steps to Reproduce

1. Right-click an element on any web page.
2. See the "Block element" context menu item.

Or:

1. Right-click the uBlock Origin icon on the browser's main toolbar (if you enable it on the toolbar).
2. See the "Block element" context menu item.

### Expected behavior:

Both context menu item should have ellipses ("Block element…")

### Actual behavior:

No ellipses on either item. Tested on both en and zh_TW locales.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox 64.0 (64-bit)
* Operating System and version: Windows 7 64-bit

**Comment by GrissomE** [comment]
I've made changes to the locales to update with ellipses in my fork [https://github.com/GrissomE/uBlock
](https://github.com/GrissomE/uBlock
)Built and loaded modified locales on Firefox dev 67.0b13 (64-bit)/Chrome Version 73.0.3683.103 to check that no functionality was lost. Checked in en and zh-TW locales but changes should be present across all. 

I'd go ahead and submit a PR but can't due to repo policy needing previous contribution.

**Comment by gorhill** [comment]
It's not worth to open a PR for this. The fix here is extremely trivial, it's just to add `...` to one entry in `src/_locales/en/messages.json`. I didn't do it yet because the other part of the fix is to upload the change to Crowdin, then wait for all translations to catch up and download them and commit them here. It's because of these secondary steps that I didn't fix it yet.
