### ISSUE TITLE
Combining procedural selector :has() and :style()

### ISSUE THREAD

**Issue by shesek** [uBlockOrigin/uBlock-issues#382]
This is a very useful combination, but it seems like they don't like working together?

**Comment by uBlock-user** [comment]
Put back the template and fill it if you want to file a bug.

**Comment by gorhill** [comment]
I reopen because I am aware of this, this is a TODO. Many AdGuard filters are discarded because of this. Repro steps:

- Open the logger
- Select "All" in the logger
- set filter expression to "cosmetic filter" in the logger
- Enable (or force a reload of) AdGuard Base Filters

Result: the output of the logger will show many such cosmetic filters being rejected.

**Comment by shesek** [comment]
Apologies for not properly using the template, I wasn't really sure whether its a bug report or I'm simply missing something. Posting this to /r/uBlockOrigin as a question first would probably be a better way to go at this. Sorry!

I'm not sure whether uBlockOrigin cares about enabling non-ad-blocking use-cases, but FWIW, what I was trying to do is modify the appearance of facebook posts that contain a certain hashtag (reduce their visibility using opacity):

```
facebook.com##div[role=article]:has(> div > .userContentWrapper .userContent a[href^="/hashtag/XYZ?"]):style(opacity:0.5)
```

This seems to be quite useful to me and enables all sorts of interesting use-cases. But again, I understand this is not really what uBlockOrigin is for.

**Comment by krystian3w** [comment]
As for me, it's a bit of a strained example, you can do something like this with ViolentMonkey / GreasyMonkey / TamperMonkey also.

**Comment by Grossdm** [comment]
Has `:style()` ever been chainable (allowed on procedural cosmetic filters)? I thought that it was, and I've struggled in creating some filters recently.

If it is at all feasible, implementing this would be useful.

A common need arises in unsticking headers (very helpful for mobile browsing).

If I can find the correct DOM node with the element selector, often the selector is one that seems likely either to not apply on other pages of the site or to not last very long (i.e., small site changes likely to break the selector).

Typically, I can create a procedural selector with either:

1. `:has()` because the "header" (only a `div`, not a `header` tag) contains a class named similar to "nav".

2. `:matches-css()` in some easy cases because the stuck header is simply styled `position: fixed`, but unfortunately lacks an `id` or `class` that a regular CSS selector could match.

Thanks for everyone's work on uBlock Origin!

**Comment by yourduskquibbles** [comment]
> Has `:style()` ever been chainable (allowed on procedural cosmetic filters)? I thought that it was, and I've struggled in creating some filters recently.

Not that I've found. See gorhill's first comment on it that I could find - https://github.com/gorhill/uBlock/issues/781#issuecomment-234574575

I would also find this useful (and have a real use case I would use this on as well)

**Comment by peace2000** [comment]
Found this old request and want to express my interest as well for having this feature.

**Comment by nuchi** [comment]
I got this working locally. If you don't mind I'll open a PR later tonight. No expectation, of course. I saw that you occasionally accept PRs, but this might be a slightly larger change than you ordinarily accept, and I don't know enough about the performance implications to know whether there would be an issue.

**Comment by krystian3w** [comment]
As long as you have permissions to send PR, the author prefers to take care of the quality of the code, and you will probably be able to see your version with a lot of patches.

**Comment by gorhill** [comment]
The reason why this is not fixed yet is not to implement supporting `:style()` itself, which is quite easy to add at this point, the reason is because of all other aspects that have to be revisited to work with the fix: element picker (preview mode), DOM inspector, cosmetic logger and whatever else I am not thinking at the moment, and I don't want  to fix this just to see an avalanche of opened issues for all those other aspects which are expected to work seamlessly with procedural `:style()` operators.

Now that said, @nuchi if you have something that work, let me inspect the code change in your repo -- I couldn't find any uBO repo in your GitHub page.

**Comment by nuchi** [comment]
Thanks! All those details are great to hear about. I took care of excluding the element picker from being styled, because the code for that was right next to the code I was touching, but the other things you mentioned are things I didn't know about. (And am happy to work on, now that you've brought them to my attention, if it makes it easier to accept a contribution.)

I just pushed my changes.
https://github.com/gorhill/uBlock/compare/master...nuchi:hn--add-procedural-styles?expand=1

**Comment by nuchi** [comment]
I just pushed three changes:
1. a fix to a bug I had in the existing code, and
2. element picker implementation (i.e. preview mode)
3. an adjustment to `DOMFilterer.getAllSelectors_` so that logging doesn't get spurious entries
I verified the element picker correctly handles each of the following on `example.com`:
```
##a
##a:style(font-style: italic)
##a:upward(2):style(font-style: italic)
##a:upward(2)
```
You can see those three changes in the three commits in the link above. I hope this might make it easier to accept my contribution, though as before, no expectation.

**Comment by mvastola** [comment]
Is there any news on this? This feature would be insanely helpful.

**Comment by gorhill** [comment]
@nuchi I appreciate your efforts to solve the issue here but this is something I had to go through myself. The reason is that when I have to fix such core feature, I think long before I write any code about what would be the best approach to fix the issue, and most of the time this involves some level of needed refactoring -- which was the case here.

**Comment by nuchi** [comment]
Totally --- thanks so much for adding this feature!

**Comment by imba-tjd** [comment]
I think I found a not-working case.

This works:

```
example.com##html:style(background: red)
```

But these are not:

```
example.com##html:has-text(Example):style(background: red)
example.com##html:has(body):style(background: red)
example.com##html:has(div):style(background: red)
```

Though these works:

```
example.com##body:has(div):style(background: red !important)
example.com##body:has-text(Example):style(background: red !important)
```

**Comment by krystian3w** [comment]
It looks like a protection against hiding html inherited from procedural filters.

**Comment by krystian3w** [comment]
#1240

**Comment by krystian3w** [comment]
AdGuard syntax may no translated if have regex with `{`, `}`.

```js
example.*#$?#body > div > h1:has-text(/[\w\W]{1,24}/) { color: red !important; }
```

I try colorize `<H1>` if have 1-24 characters.

The only problem will be if someone is stubborn with the AGuard syntax.

---

related https://github.com/AdguardTeam/ExtendedCss/issues/114

**Comment by gorhill** [comment]
Enabling AdGuard Base, AdGuard Mobile, AdGuard Annoyance, I get the following cosmetic filters reported as invalid:

    ! adguard-mobile:
    ktuu.com#?#aside > .visible-xs-block > .row:has(> .col-xs-24 > a.ptr[onclick^="trackNativeLink('https://www.ktuu.com/content/sponsored/"]) + hr

    ! adguard-generic:
    oxforddictionaries.com#$#@media (min-width: 1024px) { .main-content > div.container > aside[class="sidebar extend"] { margin: 0 0 20px -300px!important; } }
    hm-news.co.il#$?#a[href][data-item^='{"sources":['][data-item*='Video Ad'] { remove: true; }

    ! adguard-annoyance:
    protanki.tv#$#.ant-modal-mask { display: none!important; } { display: none!important; }
    buzzhand.com#$?#.mash-lightbox[-ext-has="div"] { display: none!important; }
    itemci.com#$#html { oberflow: visible!important; }
    itemci.com#$#body { oberflow: visible!important; }
    511tactical.com#$##.modal-backdrop { display:none!important; }

Fixing your case also fixes parsing the following AdGuard filter:

    hm-news.co.il#$?#a[href][data-item^='{"sources":['][data-item*='Video Ad'] { remove: true; }

The following filters were correctly reject, they have mistakes in them:

    oxforddictionaries.com#$#@media (min-width: 1024px) { .main-content > div.container > aside[class="sidebar extend"] { margin: 0 0 20px -300px!important; } }
    protanki.tv#$#.ant-modal-mask { display: none!important; } { display: none!important; }
    itemci.com#$#html { oberflow: visible!important; }
    itemci.com#$#body { oberflow: visible!important; }
    511tactical.com#$##.modal-backdrop { display:none!important; }

This leaves those two as improperly parsed:

    ktuu.com#?#aside > .visible-xs-block > .row:has(> .col-xs-24 > a.ptr[onclick^="trackNativeLink('https://www.ktuu.com/content/sponsored/"]) + hr
    buzzhand.com#$?#.mash-lightbox[-ext-has="div"] { display: none!important; }

For first one of these two, the parsing error is uBO improperly matching parenthesis. For the other ome, I have to investigate as I am not seeing anything wrong with it.

**Comment by gorhill** [comment]
Actually one is a `@media` directive, it's not supported by uBO.

**Comment by krystian3w** [comment]
And someting like: https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-685566693 `::-webkit-scrollbar-button:vertical:increment`

**Comment by krystian3w** [comment]
`buzzhand.com#$?#.mash-lightbox[-ext-has="div"] { display: none!important; }`

Maybe fixed if server `filters.adtidy.org` serve as:

`buzzhand.com##.mash-lightbox:has(div):style(display: none!important;)`

in the feature.

**Comment by gorhill** [comment]
> `::-webkit-scrollbar-button:single-button:vertical:increment`

Is that valid CSS pseudo-element syntax?

**Comment by gorhill** [comment]
> Maybe fixed if server filters.adtidy.org serve as:

I fixed that one in uBO, along with the case where `{` appear in a pseudo operator.

**Comment by mapx-** [comment]
> > `::-webkit-scrollbar-button:single-button:vertical:increment`
> 
> Is that valid CSS pseudo-element syntax?

https://css-tricks.com/custom-scrollbars-in-webkit/

**Comment by krystian3w** [comment]
Nope for:

`getComputedStyle(document.querySelector('::-webkit-scrollbar-button:single-button:vertical:increment'), null);` 

recommend in the past to read CSS values for `:matches-css*(*: *)`

**Comment by gorhill** [comment]
While investigating, it looks like there is a regression. Trying to find existing filter, this one in uBlock filters:

    enterinit.com##*::selection:style(background-color:#338FFF!important)

The style is no longer applied, the change here causes uBO to always apply `display: none !important` when there is a pseudo-element.

**Comment by yourduskquibbles** [comment]
@gorhill I think there may be another case where this doesn't work consistently  - when filters targeting multiple DOM elements are consolidated into one filter and one of them includes the `:upward(n)` uBO extended filter syntax. 

test link: `https://www.nytimes.com/live/2020/10/01/us/trump-vs-biden`

After scrolling down the page a bit, try to create the following consolidated filters (applying CSS to two elements with one filter) using the element picker:

1. The filter below does **NOT work** to pin the multiple floating header components (when `:upward(n)` is in the first or middle consolidated filter position element picker won't highlight elements and won't allow create): 
`###NYT_TOP_BANNER_REGION:upward(1), #NYT_TOP_BANNER_REGION, #NYT_TOP_BANNER_REGION > div > .interactive-size-medium.interactive-content:style(position: static !important;)`

![nytimes01](https://user-images.githubusercontent.com/22258847/95102575-899c0f80-0701-11eb-8610-999704a3653f.png)



2. But the filter below **WORKS** to pin the multiple floating header components (when `:upward(n)` is in the **last** consolidated filter position): 
`###NYT_TOP_BANNER_REGION, #NYT_TOP_BANNER_REGION > div > .interactive-size-medium.interactive-content, #NYT_TOP_BANNER_REGION:upward(1):style(position: static !important;)`

![nytimes02](https://user-images.githubusercontent.com/22258847/95102565-86a11f00-0701-11eb-90f9-11ef21b3bb33.png)


The filter that you can create with element picker also works on page reload, but the non-working filter doesn't work even if you add it to `My Filters` without going through element picker. 

Tested on both firefox and chrome latest uBO dev builds.

**Comment by gorhill** [comment]
@yourduskquibbles You can't use a procedural in a list of selectors, you will need to separate `#NYT_TOP_BANNER_REGION:upward(1)` from the rest.

When you use a procedural operator in a selector, the whole selector is parsed as a procedural one, and in such case this results in an invalid selector when using a comma-separated list of CSS selector.

**Comment by krystian3w** [comment]
AdGuard maybe support:

`example.*#$#body:has(div[style]), html:has(div[style]) { overflow: visible !important }`

but `upward`/`xpath` now supported only at end of filter due Sizzle (jQuery?) limitation in own environment.

**Comment by gorhill** [comment]
Actually, I need to investigate why  the first form does not show as an error, I would have expected so.

**Comment by gorhill** [comment]
In the next dev build, following selector will be marked and rejected as erroneous:

    *###NYT_TOP_BANNER_REGION:upward(1), #NYT_TOP_BANNER_REGION:style(position: static !important;)

While the following one will be accepted as valid:

    *###NYT_TOP_BANNER_REGION, #NYT_TOP_BANNER_REGION:upward(1):style(position: static !important;)

**However**, the last one has to be understood as `querySelectorAll('#NYT_TOP_BANNER_REGION, #NYT_TOP_BANNER_REGION')` being fed to `:upward(1)`.
