### ISSUE TITLE
ABP's $rewrite filter option - discussion

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uBlock-issues#46]
see
https://issues.adblockplus.org/ticket/6592
https://issues.adblockplus.org/ticket/6622

related:
https://issues.adblockplus.org/ticket/6242

**Comment by gwarser** [comment]
Allow only removing parts of url?

**Comment by gorhill** [comment]
Copy/pasting here a comment I made yesterday in Teams after I pondered this for a while:

***

gorhill May 22, 2018, 10:19 AM EDT

I won't implementing this filter option, I see too many issues with it. I am however open to implement a different filter option with similar purpose, but which would not suffer the issues I see with how `rewrite` has been designed. However, I need to see more cases being solved by such filter option than the just one case mentioned. So far I don't see this.

My concerns:

Security: testing same origin for redirect URL is not enough: both `github.com/gorhill/` and `github.com/toto/` have the same origin, however the content of both URLs is not controlled by the same person. My hunch tells me this is not good.

Security: even with strictly same origin, a malicious filter list author could add bad stuff to a network request.

Performance: the `rewrite=` option _requires_ that the filter is a regex. This is bad, as this prevents such filter from being tokenizable, and as a consequence the filter must be tested against every single network request. With uBO this can be somewhat mitigated (not with ABP) by using type option (ex. `xmlhttprequest`) and party-ness option (ex. `third-party`), but this is still be a concern for me.

Given these concerns, I see a better way to implement similar option but with a more focused purpose: to remove specific query parameters from a URL:

    ||content.uplynk.com/ext/*.m3u8?$querystrip=*

Where the `querystrip` option would mean: "remove all query parameters matching the given lists of tokens or pattern".

Sticking to _remove_ query parameters takes care of the ownership and malicious filter list author issue for the most part -- the filter _removes_ query parameters, it can never rewrite them into something else.

The performance concern no longer exist with such filter, since it does not have to be a regex. The value of the `querystrip` option dictates which query parameter must be removed. It could be `*` to remove all of them, or a `|`-separated list of tokens which tells which specific query parameters should be removed.

Now this does not remove some other concerns I see with `rewrite=`.

One is that it is designed as a block filter.

What if I really want to block using `||content.uplynk.com/ext/`? The way uBO/ABP and all similar-purpose blockers is to stop trying to find a match when a hit is found. If the filter with the `rewrite` option is found first, the really blocking filter won't be found and the network request will go through.  This can be addressed in uBO using the `important` filter option, but still, my gut tells me there is something wrong about a blocking filter which actually does not block -- I feel more thinking is needed there.

My current thinking is that a `querystrip` filter applies if and only if the network request was neither blocked or excepted. Not blocked because block filters *must* result in the network request not being made by the browser, and not excepted because the purpose of exception filters is strictly to counter block filters. So if a network request goes through both block/exception filters unscathed, than it would be fair game for further handling with a `querystrip` option.

Anyway, as said I still need more than just one case to be an argument for such filter -- the last thing I want is to add technical debt to uBO for little tangible benefits overall. Note that a site could simply convert their `GET` request into a `POST` one and this would bypass both `rewrite=` or `querystrip=` filters -- so far the case for such filter options is thin.

**Comment by gwarser** [comment]
>remove specific query parameters

`utm_*` stuff.

`querystrip` may be not enough.
Apart from the `POST` requests - some pages use path to encode query parameters, for example amazon<sup>[1](https://github.com/Smile4ever/firefoxaddons/issues/31)</sup>:
![amazon](https://camo.githubusercontent.com/c689cd03ef71f5b588ecd9614f39af785efb18e0/68747470733a2f2f692e696d6775722e636f6d2f42716a42627a502e706e67)
And some other pages use hash [2](https://github.com/Smile4ever/firefoxaddons/issues/83), [3](https://github.com/Smile4ever/firefoxaddons/issues/133) (not  even handled by network code).

**Comment by gwarser** [comment]
Also ABP code can handle `https://server.com/content/foo-with-ads.m3u8` -> `.../foo.m3u8`

>This can go so wrong, I'd say just hard code the few special websites that need this option in uBO-Extra.

:+1: 

and other cases can be handled by specialized URL redirecting extensions.

**Comment by gwarser** [comment]
>One is that it is designed as a block filter.

How to make this exception-only option? Request can be blocked by one filter, and then repaired by `@@...querystrip=*`.

**Comment by hfiguiere** [comment]
> Also I don't see how the new ABP build can get pass AMO review since it allow injection of arbitrary script. (Or I'm missed something?)

No it doesn't inject arbitrary scripts.

**Comment by jspenguin2017** [comment]
@hfiguiere What mechanism it has to prevent https://github.com/uBlockOrigin/uBlock-issues/issues/46#issuecomment-391190533 from happening?

**Comment by hfiguiere** [comment]
The example in https://github.com/uBlockOrigin/uBlock-issues/issues/46#issuecomment-391190533 change the origin, so the rewrite doesn't happen in that case, and the original query is let through.

**Comment by jspenguin2017** [comment]
@hfiguiere OK, so what about rewriting an URL from RawGit? You can control the content served from RawGit pretty easily. And all apps using RawGit CDN can be attacked.

**Comment by jspenguin2017** [comment]
Nope, it ended poorly: https://www.bleepingcomputer.com/news/security/adblock-plus-filters-can-be-exploited-to-run-malicious-code/

**Comment by rain-1** [comment]
Can i just give you a huge thank you for building and maintaining this amazing addon. You're wonderful

**Comment by Rudde** [comment]
It should be possible to sign filter lists, maybe signed by several maintainers, where uBlock doesn't accept it until changes are signed by n-maintainers.

**Comment by gwarser** [comment]
Will be implemented in Brave https://github.com/brave/adblock-rust/pull/184

https://www.reddit.com/r/uBlockOrigin/comments/poy9us/interest_in_redirecturl_filter_option/

**Comment by KiARC** [comment]
Since this was marked as duplicate elsewhere, I'll mention it here: What if the syntax to rewrite a URL only functioned in My Filters, and was not parsed anywhere else? This would protect users from malicious list maintainers while still allowing people to do this. An example I have for a use case is redirecting requests to `ajax.googleapis.com/ajax/libs/jquery` to `cdnjs.cloudflare.com/ajax/libs/jquery` to avoid the Google API call.

**Comment by gorhill** [comment]
> only functioned in My Filters

uBO is mature software at this point, and my focus is to do work on code which help filter list maintainers. What you ask can already be accomplish by specialized extensions out there.

**Comment by KiARC** [comment]
That's fair, really Request Control is the right extension for this, but unfortunately uBO has a habit of breaking literally any other network filtering extension I install no matter what order they're installed in. In this case, if I block the Google API request and allow the Cloudflare one, uBO blocks the whole request before Request Control can rewrite it, and if I allow both calls uBO inexplicably forwards the request to Google without letting Request Control interact with it, at least as far as the logger says.

**Comment by gorhill** [comment]
> I block the Google API request and allow the Cloudflare one, uBO blocks the whole request before Request Control can rewrite it

Blocking has precedence over redirecting, regardless of extension order of processing. Just don't block network requests you want to be redirected to a different server.

**Comment by KiARC** [comment]
That's new information to me, thank you, but when I allow it in uBO for Request Control to redirect my log seems to show a request to Google and then a request to Cloudflare, which suggests to me that the request is not being redirected but repeated. This behavior is not caused by Request Control, as when uBO is off it does not happen, as far as I am able to tell. Is there something I'm overlooking?

**Comment by gorhill** [comment]
> my log

What is that "log"? If it's uBO logger, then it's normal it's showing you a network request to Google not being blocked (if that is the one you want to be redirected), because everything shown in the uBO's own logger is from the point of view of uBO, and if the request is not blocked by uBO, then the logger will show it as not being blocked. Use the browser dev tools to see the final outcome of which network requests are blocked/redirected/allowed.

**Comment by KiARC** [comment]
I initially used the uBO logger and saw that, and then checked the network tab in DevTools and was getting inconsistent results. Like I said, I'll try to examine it better.

**Comment by YoshiTabletopGamer** [comment]
> > only functioned in My Filters
> 
> uBO is mature software at this point, and my focus is to do work on code which help filter list maintainers. **What you ask can already be accomplish by specialized extensions out there.**

Halfway there (after slash) https://github.com/gorhill/uBlock/commit/2e4525fe3c 🤷

**Comment by stephenhawk8054** [comment]
> work on code which help filter list maintainers.

**Comment by YoshiTabletopGamer** [comment]
> > work on code which help filter list maintainers.

I'm just saying a lot of features have been added without that much community input. Ublock Origin is not mainly and should not be mainly something like a user script extension.

**Comment by stephenhawk8054** [comment]
So what should filter list maintainers do when a large website with large users target uBO specifically and change scripts everyday and quick fix list cannot keep up?

Then hundreds of users come to uBO reddit and github to complain every day?

Can you help us managing those users? Can you help us update the filter lists when the website updates while it's 1AM-3AM while filter lists maintainers cannot stay up that late?

**Comment by YoshiTabletopGamer** [comment]
Like Yuki said,

> One reason I love and **trust uBO is that he always takes serious consideration of security** and privacy https://github.com/uBlockOrigin/uBlock-issues/issues/46#issuecomment-391303700. Those who don't and take every nice or convenient feature demanded [suffer vulnerability](https://blog.adblockplus.org/blog/vulnerability-fixed). Prevention is better than cure.

Which is better, feature creep and increased attack surface, or having to update filter lists more frequently (are they all in the same timezone?)

If we **must** do this to defeat anti blockers, we **need** to think carefully, mitigating the attack surface.

**Comment by YoshiTabletopGamer** [comment]
The [community](https://old.reddit.com/r/uBlockOrigin/comments/178rrk5/was_there_some_kind_of_general_breakthrough_in/) is pressuring the maintainers for quickly defeating anti blockers, but I still believe **we need to justify new trusted filters** and as I previously said, **we must not trade security for functionality**.

**Comment by gorhill** [comment]
> Halfway there (after slash)

As opposed to `rewrite`, only uBO's own lists can use it.

**Comment by YoshiTabletopGamer** [comment]
Hi, gorhill. Sorry for the rant, but I never expected anti blockers to force us to add fully custom filters.

**Comment by stephenhawk8054** [comment]
Then the best way for gorhill is to abandon the project and let whoever can take those ideas do whatever they want. I'll support that decision with both hands and I could be able not to waste my time dealing with filter lists and users any more.

If you have any ideas to both develop the way you think it's better and to counter with the codes that change everyday, just develop and PR it. Talking sarcastically and literaturely without any actions to contribute just wastes time on both sides.

If that's difficult, you can voluntarily help us update the filter lists and talk with users out there. Is it ok?

**Comment by gorhill** [comment]
> I never expected anti blockers to force us to add fully custom filters

I don't understand what that means. Can you clarify?

**Comment by stephenhawk8054** [comment]
In case you don't know, in the last uBO stable release, uBO survived that large website anti blockers solely due to 1 of the trusted scriptlets for weeks before new release could come out while there was litetally no other ways to counter with other scriptlets.

**Comment by YoshiTabletopGamer** [comment]
> > I never expected anti blockers to force us to add fully custom filters.
> 
> You must be new here then. As new tricks and ways appear, uBO continues to develop new features too. This has been ongoing for last 5 yrs and beyond...

Do not misunderstand! I have known for years scriptlets have been essential to uBO. I'm talking about the trusted lists. By "fully custom filters" I mean filters that can now do pretty much the same things a user script can do. It's now clear that the evidence for usage of trusted filters has been growing.

**Comment by YoshiTabletopGamer** [comment]
I know, I myself use medium mode and am an "Advanced User". I just don't use a userResourcesLocation

**Comment by YoshiTabletopGamer** [comment]
> The userScript point of yours has nothing to do trusted sources concept which you were attributing the reason. That's my point. Once `userResourcesLocation` came into existence, many things became possible. trustedSources is now one more step in opening many more possibilities which were still not available to filter lists maintainers.

Yes, I still remember when the subreddit was once filled with advice on how to bypass Twitch ads.

**Comment by gorhill** [comment]
> feature creep

This is not "feature creep", what is being done is necessary to fulfilled user expectation from their content blockers given how the websites evolved. "Feature creep" would be warranted if uBO become large inefficient piece of software, but that is not the case, I am confident that it's still the most efficient content blocker by a good margin given it's capabilities.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/6066c322-7d7c-4b6d-9764-3a8becf88618)

The added features are for the most part not visible to users, i.e. we are not adding buttons and widgets in the user interface, we are adding filtering capabilities in order to improve content blocking in way that is seamless to users, and a testament to this is that vast majority of people out there (before Youtube crack down anyways) have no idea that the "seamless" aspect is due to filter list maintainers constantly working behind the scene, with the capabilities offered by the filtering engines in uBO.

It seems at this point you are arguing against evolving uBO to keep up with websites, arguing for stagnation which will lead to irrelevancy. If you have better solutions to all we are working, best to suggest concrete actions, so far you are not proposing anything actionable beside what is essentially "stop working on uBO".

**Comment by YoshiTabletopGamer** [comment]
**I'm not arguing against Ublock Origin's performance**, I just had this (silly and unlikely) worry [here](https://github.com/uBlockOrigin/uBlock-issues/issues/2229#issuecomment-1765018694). **I'm not arguing for stagnation in any way, shape or form.**

**Comment by YoshiTabletopGamer** [comment]
**I'm not arguing against Ublock Origin's performance**, I just had this (unlikely, but potentially (in the very, very long term, **actionable**) worry [here](https://github.com/uBlockOrigin/uBlock-issues/issues/2229#issuecomment-1765018694)). **I'm not arguing for stagnation in any way, shape or form.**
