### ISSUE TITLE
add gray label in to the selected filter on injector board

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#47]
![2018-05-23-example domain](https://user-images.githubusercontent.com/5884000/40422081-6969c4d2-5e8e-11e8-885a-6475b5b21d05.png)

example suggested change. 
![2018-05-23-example domain](https://user-images.githubusercontent.com/5884000/40422204-ded26c56-5e8e-11e8-952a-b1c3b7932b1d.png)

### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: ubo 1.16.6
* Browser Name and version: chrome 66.0.3359.181
* Operating System and version:

**Comment by uBlock-user** [comment]
Is this a feature request ?

**Comment by KonoromiHimaries** [comment]
@uBlock-user no, this is a bug

**Comment by uBlock-user** [comment]
How ? Make a case and fill in the template.

**Comment by KonoromiHimaries** [comment]
@uBlock-user yea, I am very frustrated by the lack of this feature

**Comment by uBlock-user** [comment]
What feature ? Make a case, why it should be added and what purpose it will serve, this, right now doesn't make any sense.

**Comment by KonoromiHimaries** [comment]
for quick rule search on pages with a large number of possible rules
![2018-05-23-62 edycja standout beautyword 2018 dubai](https://user-images.githubusercontent.com/5884000/40422878-0616aeba-5e91-11e8-8894-6c4070d34c08.png)

**Comment by gorhill** [comment]
That's quite a contrived case, making it look trivial. That is not trivial in the real world, because what you click is not necessarily what will end up in the textarea. This is also true when you use the Ctrl modifier. And as soon as manually modifying the filter, it will again not match any entry.

> for quick rule search on pages with a large number of possible rules

You **just** clicked on the entry, surely you know for sure what you just clicked?

**Comment by uBlock-user** [comment]
Yes but why add a grey label ? What will it do ?

**Comment by gorhill** [comment]
Here is a real case: https://www.youtube.com/watch?v=8TvCGWwQr5o

**Comment by gorhill** [comment]
> Yes but why add a grey label ?

He probably meant to highlight the clicked entry.

**Comment by uBlock-user** [comment]
> keep the clicked entry highlighted.

Yeah thought that too if that's what he trying to suggest.

**Comment by gorhill** [comment]
My fear is that if I keep the last clicked entry selected, and the filter is manually edited, someone will open an issue that the highlighted entry no longer match the content of the textarea, or that someone will expect that manually editing a filter should result in a possibly matching entry to be auto-highlighted -- not the kind of endless issues I want to suffer.

If the highlight is **strictly** to remember the **last clicked entry** regardless of what is in the textbox, than I find this is more acceptable, otherwise it's just over-complicating the code for little benefit.

The problem with the request is that it is superficial, there is no in-depth description of what exactly is sought and details on how to handle all the different scenarios.

**Comment by uBlock-user** [comment]
Yeah, this request is more of a convenience sake for the user to see what entry is currently selected, but you're right about the potential issues that can/will pop up if this gets added.

**Comment by gwarser** [comment]
Idea - enclose these items inside `<a>` tag - they should have dotted border.

**Comment by jspenguin2017** [comment]
How about highlight the last clicked entry, and remove the highlight when the textarea is changed?

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.
