### ISSUE TITLE
Remove MVPS HOSTS because it does not support HTTPS in 2019 (Upstream request from Nano Adblocker)

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#484]
Partially speaking on behalf of @jspenguin2017, who six days ago chose to remove MVPS HOSTS from Nano Adblocker in https://github.com/NanoAdblocker/NanoCore2/commit/7e708d24e84320a2aa9ea22edd6aa65518c2444a, we agreed on bringing up the matter with you guys at uBlock Origin as well.

Not only is MVPS HOSTS not using HTTPS in the year 2019, as one of very, very few adblock lists remaining to not do so, but it will probably **never** ever get HTTPS for several reasons.

You see, as far as I personally understand the situation, the domain *[mvps.org](http://mvps.org/)* was created in the very early 00's to serve as a hub for some members of the *Microsoft MVPs* program. There's probably a reason why his subdomain has the year 2002 in it, after all; as well as why [he use webpage stickers](http://winhelp2002.mvps.org/) dedicated to Kim Komando and the XP-era Microsoft MVPs logo.

Many years later, [WordMVP](https://wordmvp.com/) alleges that mvps.org shut down in January 2017, and that everyone who used to be there moved away from it except the MVPS HOSTS guy. Thus he is now left on a domain that has no technical support whatsoever, that he doesn't own, whose current domain owner doesn't give a darn about anything, and which he seemingly can't do any serious technical changes on whatsoever.

Jspenguin also (as far I understand him) expresses worries about whether the list's licence, https://creativecommons.org/licenses/by-nc-sa/4.0/, is a sufficiently open-source licence for it to really count as being open-source.

I would previously have requested changing the list's sync-link to https://raw.githubusercontent.com/StevenBlack/hosts/master/data/mvps.org/hosts, but as that mirror is not updated instantly, but usually on a delay of several days, I think that just removing the list entirely would've been preferable.

**Comment by gorhill** [comment]
He removed the list a few hours after [this was posted](https://www.reddit.com/r/uBlockOrigin/comments/b23qk6/michael_burgess_chief_maintainer_of_the_mvps/).

I decline, removing the list _exactly_ at that time is quite curious and downright insensitive -- the list is and has been useful for countless people, and the author stated he would still keep maintaining the list despite his unfortunate health issues.

Whoever is bothered by non-HTTPS connection is free to not use the list, it's opt-in.

**Comment by uBlock-user** [comment]
Why not request the author to get a HTTPS cert from Lets Encrypt instead ? It's free for starters.

**Comment by DandelionSprout** [comment]
To Gorhill: Good points for the time being. I was completely unaware of the Reddit thread of of Burgess' recent problems.
————————————————
To uBlock-user: I strongly suspect that it's outside of his control to get a Let's Encrypt certificate for winhelp2002.mvps.org, as he does not seem to control the domain rights or the mvps.org backend. Nevertheless I'll be attempting to suggest such a thing to him now in an E-mail.

**Comment by jspenguin2017** [comment]
> removing the list exactly at that time is quite curious and downright insensitive

How did you conclude that I have seen that post? I have planned to remove the list for a long time, and decided to do it last weekend after being reminded by NanoMeow's log. 

As you know, after [this incident](https://github.com/uBlockOrigin/uBlock-issues/issues/285), I have created a [response protocol](https://github.com/NanoAdblocker/NanoCore2#subresource-integrity-incidence-response-protocol) in order to appropriately respond to future incidents -- I still disagree with the way you handled that incident as removing the filter from `assets.json` does not unsubscribe it and the censorship rules will remain in place for an extended period of time. 

Being privacy and security conscious, you should have known better what's the implication of unencrypted traffic. In order to ensure the integrity of my assets mirror, I cannot let NanoMeow to download filter lists over an insecure protocol, and I have [voiced my concerns](https://github.com/NanoAdblocker/NanoCore/issues/225#issuecomment-437752929) about 5 months ago. There is no excuse to not use HTTPS in 2019 as Let's Encrypt offers free certificate to everyone. 

> it's opt-in

That is still not an excuse for you to promote it. You have better knowledge about privacy and security than the average user, and you should not make it easier for people to shoot themselves in the foot.

**Comment by jspenguin2017** [comment]
Oh, also, `spam404` now support HTTPS on their support URL. 
https://github.com/NanoAdblocker/NanoCore2/commit/89cddadfa737ebe959684cfaaa1df41abe3ba6f6

**Comment by DandelionSprout** [comment]
I'll take an "Either way is fine by me" neutral approach in this thread to avoid causing unintentional drama, although I am very supportive of HTTPS in general.

Having now asked Burgess about the situation, and whether he'd be willing to support HTTPS, here's the answer (Top is his reply, bottom is the question(s) I asked him: 
![image](https://user-images.githubusercontent.com/22780683/54871131-01b91380-4db0-11e9-962a-fdd31fb7b991.png)

So then we know now that he has no ambitions of implementing HTTPS, even upon the promise of me donating to him upon doing such.

**Comment by jspenguin2017** [comment]
> I have no control over MVPS ...

With outdated software and unmaintained servers, it's just a matter of time when the server is hacked and taken over. This is about "when", not "if". 

> I have no intention of moving ... or taking the time to mirror ...

This is downright irresponsible. How could this person claim himself a "most valuable professional" when he actively ignores significant security issues of his hosting setup? With the time he spent to respond to the email above, he could've mirrored his website to GitHub Pages or something. 

---

You know what, maybe I'm missing something. Or maybe @gorhill has some special or personal connections with this person that I'm not aware of. Either way, I don't want to be part of the problem, I'll also donate $10 if the hosting issues can be resolved and the list is re-licensed under a [recognized open source license](https://opensource.org/licenses/alphabetical).
