### ISSUE TITLE
"#@#+js" entries are shown in the logger as yellow instead of green

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#500]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When a `#@#+js`-containing entry is shown in the logger as being triggered(?), its listing is shown as being yellow (The colour of hidden content) instead of green (The colour of whitelisted content).

### A specific URL where the issue occurs

`clipconverter.cc`

### Steps to Reproduce

1. Turn on *uBlock Filters*, as it has an entry called `clipconverter.cc##+js(abort-current-inline-script.js, atob, decodeURIComponent)` in it.
2. Go to *My filters*, and add `clipconverter.cc#@#+js(abort-current-inline-script.js, atob, decodeURIComponent)` to it.
3. Open the logger.
4. Visit `clipconverter.cc`.
5. Look at the logger.

### Expected behavior:

The `#@#+js` entry is shown in the logger in green, as it is a whitelisting entry.

### Actual behavior:

The `#@#+js` entry is shown in the logger in yellow, as if it was a hiding entry.

![image](https://user-images.githubusercontent.com/22780683/55294659-f0ea4c80-5404-11e9-895e-3e42bfefa209.png)

### Your environment

As for my own personal environment, it's:

* uBlock Origin version: Nano Adblocker 1.0.0.97
* Browser Name and version: Google Chrome 73.0.3683.86 64-bit
* Operating System and version: Windows 10 October 2018 Update (Last installed update: KB4489899)

It is also believed to have been tested and replicated by several other people who use various uBO branches, including okiehsch, THEtomaso, and krystian3w.

### Furthermore details and discussions about the issue:

https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-478366463 through https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-478379476.

**Comment by krystian3w** [comment]
Blueish proposition: | Greenish proposition: | Grayish proposition:
--- | --- | ---
![obraz](https://user-images.githubusercontent.com/35370833/55294712-a7e6c800-5405-11e9-8487-ebbf0cee62c0.png) | ![obraz](https://user-images.githubusercontent.com/35370833/55294739-f3997180-5405-11e9-83ff-58c45c2b786a.png) | ![obraz](https://user-images.githubusercontent.com/35370833/55294806-9f42c180-5406-11e9-98e8-3de805959f98.png) 
`rgba(0,255,255,0.1)` | `rgba(0,255,0,0.1)` |  `rgba(192,192,192,0.5)`

**Comment by uBlock-user** [comment]
They have cosmetic filtering syntax, hence yellow. Green is for exception/whitelisted filters which are network filters.

**Comment by uBlock-user** [comment]
> The #@#+js entry is shown in the logger in green, as it is a whitelisting entry

It doesn't whitelist, it disables the `##+js` filter like `$badfilter` does for network filters.

**Comment by DandelionSprout** [comment]
In that case I suppose that an alternate possibility is to not list the `#@#+js` entry in the logger at all, akin to how I now recall that `#@#` entries are treated like.

**Comment by uBlock-user** [comment]
> In that case I suppose that an alternate possibility is to not list the #@#+js entry in the logger at all, akin to how I now recall that #@# entries are treated like.

I agree on that, but turns out `#@#` not appearing in the logger itself is a uBO bug which was discussed somewhere on the tracker with gorhill long time ago, but personally I'm okay with that as `$badfilter` also never appears in the logger and I like that behaviour.

**Comment by okiehsch** [comment]
Personally I would like for the `#@#` and the `badfilter` option to appear in the logger because I was puzzled on a few occasions why a filter did not work before I realized that a `badfilter` negated it.
I do realize that I work a lot with filters and the average user will never notice the problem.

**Comment by kulfoon** [comment]
>  uBlock-user: but turns out `#@#` not appearing in the logger itself is a uBO bug which was discussed somewhere on the tracker with gorhill long time ago

Here: https://github.com/gorhill/uBlock/issues/127, the sad thing is that the issue is 4 years old...

> okiehsch: https://github.com/uBlockOrigin/uBlock-issues/issues/500#issuecomment-478392034

I agree (and if not accepted, then possibly alternatively the good compromise can be to make it as an on/off feature in Settings > Advanced settings, to keep the best of both worlds (average users and developers)).

As for the color, I wish you lots of fun with choosing colors, I stay undecided as for now, any color (other than yellow) will make me happy, but consider 2 factors:
- the first factor is whether to differentiate `#@#` and `badfilter` rules from network exception `@@` rules, if no differentiate then all such kind of rules must have Greenish
- if the first factor is not choosen as all have Greenish color, then another idependent sub-level factor is whether to differentiate disabling rule (`badfilter`) from exception rule (`#@#`) (two different colors), or to keep them together (one color).

**Comment by gorhill** [comment]
> Here: gorhill/uBlock#127, the sad thing is that the issue is 4 years old and still unfixed...

The nice things is that other stuff got fixed/improved. Of course, it's true that I could spend **more** time to sit in front of the computer and fix more stuff in this one project. It's sad that I don't. This is the reality of maintaining a FOSS project, people focusing on the work which has not been done, while ignoring all the work which has been done.

(Actually, I started to fix this a while ago, but this is not trivial and this required adding an overhead just for the sake of logging purpose even when the logger is not in use, so I stalled there and went onto fix other stuff).

**Comment by uBlock-user** [comment]
> The nice things is that other stuff got fixed/improved. Of course, it's true that I could spend more time to sit in front of the computer and fix more stuff in this one project. It's sad that I don't. This is the reality of maintaining a FOSS project, people focusing on the work which has not been done, while ignoring all the work which has been done.

I fear that at the rate that the issues are getting posted versus the rate that they get fixed will someday overwhelm the tracker and in turn you and then this tracker will also turn like the previous one where it became too much to handle and it went out of contro. Hope that it doesn't happen though.

**Comment by DandelionSprout** [comment]
>Of course, it's true that I could spend more time to sit in front of the computer and fix more stuff in this one project. It's sad that I don't. This is the reality of maintaining a FOSS project, (…)

Since we're on this topic now anyway: One thought that comes to my mind, is that it surely can't be mandatory for FOSS projects to be one-man endeavours? I am fully aware that some bad stuff happened back in 2015-ish back when it was a two-man project with Chris Aljoudi, but I can't imagine that people like okiehsch, gwarser, uBlock-user, or even Jspenguin would've betrayed you (gorhill) to such a degree if they became allowed to deal with and resolve issue reports for uBO.

**Comment by okiehsch** [comment]
I am no coder.

**Comment by DandelionSprout** [comment]
Hmm... then, *if* it's ever discussed to give you uBO assistants more rights to edit the code, it would of course have to be discussed who'd consider themselves qualified to deal with which things, be it proper coding or just dealing with basic catalogue entries like `assets.json`, and of course also who among you that would even be willing to be given more rights.

**Comment by kulfoon** [comment]
I think the reason and problem might be because I'm not native english and perhaps used an inappropriate sentence, what I wanted to say and express was:  ~~the sad thing is~~ "it is a pity that the issue is 4 years old and still unfixed..." perhaps the inappropriate sentence (word "sad") was what offened gorhill, does the new sentence change the gorhill's reaction? Anyway, I do not ignore the other fixed/improved stuff and I do appreciate gorhill 's hard work and I am grateful in the depths of my spirit, also I neither do not blame gorhill for the unfixed issue nor did not intend to hurry him to fix the issue nor to offend him in any way.

**Comment by gorhill** [comment]
The chose solution is not to bring in more background color -- which would further complicate dealing with color-blindness -- but to use a strike-through style for static extended exception filters. The background stays the same. I visually removed the prefixes `##` and `#@#` so as to remove what is now just noise taking up horizontal space given the new visual.

**Side note:** static extended exception filters are conceptually equivalent to `badfilter`. _However_, `badfilter` applies at filter list loading time, whereas static extended exception filters apply at runtime. So there is no way for uBO to report `badfilter` in the logger (except possibly at load time, but that would pollute the logger output) since filters which were "baded" are not in the filterset in the end.

Keep in mind static network filtering works _very_ differently from static extended (`##`, `#@#`) filtering: with network filters, the first match is returned, all other potential mayches are ignored, while with extended filtering _all_ matches must be found.

**Comment by THEtomaso** [comment]
@gorhill:
Could you please add the fix for this issue to the Legacy branch as well?

**Comment by gorhill** [comment]
It's far from trivial, the logger was refactored and the solution applies on top of a refactored logger.

This is the [commit for the fix](https://github.com/gorhill/uBlock/commit/9bfbbfec841722da79bc002ea5f03d1b568f68f5), so a pull request made with care is welcomed.
