### ISSUE TITLE
Firefox does not load homepage completely when operating in Single-process

### ISSUE THREAD

**Issue by TOW87** [uBlockOrigin/uBlock-issues#507]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Websites do not load when using Firefox as a Single-process]

### https://www.google.com/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [Disable firefox multi-process by changing the value of browser.tabs.remote.autostart to false in about:config]

### Expected behavior:

[What you expected to happen]
Firefox should load homepage just as normal in Multi-process.

### Actual behavior:
[What actually happened]
Firefox just keeps on loading the homepage at startup but the homepage never loads completely.

### Your environment

* uBlock Origin version:
  uBlock Origin v1.18.14

* Browser Name and version:
Firefox (32bit) 66.0.2
* Operating System and version:
Windows 7 Ultimate 32Bit Service Pack 1

**Comment by uBlock-user** [comment]
Nowhere in this bug report shows having anything to do with uBlock Origin, you changed an advanced setting in Firefox and Firefox is having issue on your end. I can't reproduce, but changing that setting breaks new tab page in Firefox.

**Comment by TOW87** [comment]
I am sorry. But i can not have firefox to use multi-processes because that way it uses over 90% of my physical memory which then leads to pages being loaded very choppy (Black squares). Issue might be only on my side but its definitely has something to do with uBlock Origin because when it happens and the page doesn't fully load, disabling uBlock makes firefox to complete loading the page and then re enabling the plugin again works fine after that. It is only at the startup of the browser.

**Comment by uBlock-user** [comment]
@TOW87 Do what that guy in this [comment](https://github.com/uBlockOrigin/uBlock-issues/issues/416#issuecomment-478593091) and report back if its working for you.

**Comment by uBlock-user** [comment]
@TOW87 Do what that guy did in this [comment](https://github.com/uBlockOrigin/uBlock-issues/issues/416#issuecomment-478593091) and report back if its working for you.

**Comment by gorhill** [comment]
I thought about adding a timeout to release the pending promises at launch, but I feel this would have the bad side effect of hiding issues like the one here (assuming the idea works in the first place). The issue here seems to be a Firefox one, uBO is not designed to care about the number of processes, that information is outside it's knowledge, so this suggests a Firefox issue but I haven't had the time to better narrow down.

**Comment by gwarser** [comment]
I cannot trigger this even on this ancient laptop I have.
Pentium M 32bit, 0,5GB of RAM, Watt OS Linux, Firefox stable 66.0.1, uBO dev channel 1.18.13b0.
I have `browser.tabs.remote.autostart` set to false and tried some other pseudo-optimizations. All works sloow, but no other issues.

***

And I CAN reproduce now by setting `suspendTabsUntilReady` to `false`. This was `yes` because setting were imported from backup. I switched it to test if uBO handles switching from old boolean to string. And I cannot recover from this until `browser.tabs.remote.autostart` is switched back.

![image](https://user-images.githubusercontent.com/886325/55490092-76534400-5633-11e9-80b5-f9e303077331.png)

Reproduced on desktop pc with Firefox stable, but not with beta.

**Comment by gorhill** [comment]
In your console output, it says `fetched` is `undefined`. I do not see how this is possible, because uBO passes default value, so I expect that `fetched` will always be present with at least default value. So maybe it's a Firefox-specific behavior here, whereas if an error occurs, not even the default values are returned.

> by setting `suspendTabsUntilReady` to `false`

You would probably get the same result with `unset`, uBO compares against `no` in Firefox. Anyway, I will now try to reproduce on my side (with a _slightly_ better laptop, 32-bit 1GB...)

**Comment by gorhill** [comment]
Ok I reproduced, so @gwarser you quite probably nailed the cause of the mysterious hang-at-start. Fix is somewhat trivial, but I will published a dev build for now and I will publish an emergency fix tonight on AMO if no regression reported meanwhile.

**Comment by gorhill** [comment]
Hmm I can fix the hang, but uBO is still broken because the root failure is that uBO is unable to read the user settings. Unless someone uses all default settings. any customization will be ignored at launch time because reading user settings fails -- and this part of the issue is squarely on Firefox's side.

**Comment by gorhill** [comment]
Hmm I can fix the hang, but uBO is still broken because the root failure is that uBO is unable to read the user settings. Unless someone uses all default settings. any customization will be ignored at launch time because reading user settings fails -- and this part of the issue is squarely on Firefox's side.

**Comment by gwarser** [comment]
No one wanted to do this...

https://bugzilla.mozilla.org/show_bug.cgi?id=1543880

**Comment by Crandel** [comment]
Default settings `Disable pre-fetching (to prevent any connection for blocked network requests)` and
`Disable hyperlink auditing` cause this freezes, so as a temporary solution can you disable it for Firefox browser? Otherwise I will forced to remove this extension, because it stops my fork in internet completely

**Comment by gwarser** [comment]
If you have solid steps to reproduce, create new issue. I was asked yesterday to check my STR on bugzilla and I cannot reproduce anymore. First time I spent few hours testing various settings without success, and then when finally happened I was able to reproduce again and again on two computers triggering it by changing uBO advanced setting that should not have any effect.
