### ISSUE TITLE
Element picker doesnt work in Kiwi Browser (on Android)

### ISSUE THREAD

**Issue by tawissus** [uBlockOrigin/uBlock-issues#529]
Hello,

Since today the Kiwi Browser for Android supports Chrome extensions. uBlock works great, but the ad picker doesn't work.  I hope that it will soon be able to select ads with the picker.

Guido

**Comment by uBlock-user** [comment]
Kiwi Browser is not officially supported either, also fill the template and don't just bypass it like this.

**Comment by gorhill** [comment]
Given that the same code works on Firefox for Android, unless proven otherwise the default assumption is that there is an issue with the browser -- especially as it looks like the support for extensions is recent: <https://github.com/kiwibrowser/android/issues/35>.

Please next time provide more details as requested in the template, asking us to use a search engine to find out what you are referring to can be tedious.

**Comment by tophf** [comment]
That's because Kiwi is opening the extension's popup in a tab. Most of extensions are broken since they query the active tab so instead of the original page they get their own popup in Kiwi. I hope it's temporary and later it'll be implemented properly by Kiwi's developer, like for example in Yandex browser on Android.

**Comment by kiwibrowser** [comment]
Hi @tophf 
I'm working on a workaround that makes the tabs.query API to return the originator tab as active if the current page is a chrome-extension:// window.
The update is expected to come in one day.

About the element picker, it seems to be more tricky in general that there is no real mouse-over event on mobile, but I'll think about a solution to simulate events in another way.

**Comment by kiwibrowser** [comment]
![Screenshot_20190419-183344](https://user-images.githubusercontent.com/40272275/56431436-58900b00-62d2-11e9-83e4-c5dd64c152b7.jpg)

I have now resolved the element picker + zapper with Nano Adblocker (very similar to uBlock), it will go live in the update of tomorrow.

**Comment by tawissus** [comment]
@kiwibrowser 
Wow. You are really fast!
Thank you!
