### ISSUE TITLE
How can i add my filter list to the regions filter lists.?

### ISSUE THREAD

**Issue by mboveiri** [uBlockOrigin/uBlock-issues#533]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi.
How i can do that? 
cause the Pull Requests was limited to the  to users who have contributed on the repository.

**Comment by gorhill** [comment]
There is already "Adblock Iran", you could contribute your filters to it: <https://github.com/farrokhi/adblock-iran>?

The purpose of the stock lists area in uBO is not to list all available lists, see [front page of the project](https://github.com/uBlockOrigin/uBlock-issues):

> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

The problem is that everyone wants their list added to uBO, this is not realistic -- hence why the rule had to be put in place.

Lists are added after debate among contributors, and many criteria are taken into account:

- since how long is the list maintained
- is the list well-focused and of good quality
- does it have good support, a track record of maintainer(s) being responsive
- is it redundant to what is already in uBO
- is it key to have the list enabled by default for the specific region
- etc.

**Comment by mboveiri** [comment]
as you can see i start my Project since "2015" that one year before Mr farrokhi create his filter list, since near date that you create Ublock0.
but until now my list was in the alpha state.
then my filter list is older than and  i cant't contribute to new list. focused on your "since how long is the list maintained" rule.
Best Regard.
