### ISSUE TITLE
Adding support for currently unsupported list syntaxes

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#576]
uBlock Origin's syntax support is second-to-none compared to just about any other web extension known to man, including uBO/AdGuard/ABP lists, domains lists, hosts files, and in certain cases IP lists. That being said, my extensive work on FilterLists.com in the past 12 months have taught me about many unusual list syntaxes that to the best of my knowledge are not currently supported by uBO, so I'm hereby suggesting that such support could be made. Most of the syntaxes are rarely applied outside of enthusiast or business circles, but indeed they are in use by some people out there.

My suggestions along with the easiest possible conversion approaches:

* *hosts.deny* files ([Example list](https://zeustracker.abuse.ch/blocklist.php?download=hostsdeny)): Make `ALL: example.com` equivalent to `example.com`
* *Unbound* lists ([Example list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=unbound&showintro=1&mimetype=plaintext)): Make `local-zone: "example.com" redirect` equivalent to `example.com`, while discarding `local-data: "example.com A 127.0.0.1"`
* *dnsmasq* lists ([Example list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=dnsmasq&showintro=1&mimetype=plaintext)): Make `address=/example.com/127.0.0.1` equivalent to `127.0.0.1 example.com` or to `example.com`
* *BIND* lists ([Example list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=bindconfig&showintro=1&mimetype=plaintext)): Make `zone "example.com" { type master; notify no; file "null.zone.file"; };` equivalent to `example.com`
* *RPZ* lists ([Example list](https://hblock.molinero.dev/hosts_rpz.txt)): Make `example.com CNAME .` equivalent to `example.com`
* Internet Explorer *Tracking Protection List* lists ([Inoptimally made example list](https://easylist-downloads.adblockplus.org/easylist_noelemhide.tpl)):

If I understand https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/hh273399(v=vs.85) correctly, then the following conversions may potentially be used:

* `-d example.com` → `||example.com`
* `-d example.com file` → `||example.com/file^` or `||example.com/*/file^`
* `- file` → `*/file/`
* `+d example.com` → `@@||example.com`
* `: expires =` → `# Expires: `

I've however chosen to not suggest compatibility conversion for Privoxy lists ([Example list](https://pgl.yoyo.org/as/serverlist.php?hostformat=junkbuster;showintro=1&mimetype=plaintext)), because `.example.com` may have legitimate unique uses in uBO as-is; whereas *Little Snitch* lists have too many parameters to easily ensure successful conversions, with each of the 5 such lists on FilterLists.com using different entry structures.

You are welcome to add support for whichever ones of these that you want to; I am in no way trying or intending to pressure you to add all of them.

**Comment by gorhill** [comment]
- First example: list is available as [plain domain list](https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist)
- Second example: PGL's list, already in use in uBO as a plain domain list
- Third example: PGL's list, already in use in uBO as a plain domain list
- Fourth example: PGL's list, already in use in uBO as a plain domain list
- Fifth example: list available as [plain domain list](https://hblock.molinero.dev/hosts_domains.txt)

Declined because it's making an issue of a non-issue, asking someone _else_ to pointlessly invest efforts and time, and further suggesting to add complexity to the code base with no real benefit for end users given that all the lists given as examples are available in a format which can already be parsed by uBO.
