### ISSUE TITLE
Parse search string as plaintext to avoid doubling `\`

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#658]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Filters that contains `\` (e.g. `google.*###center_col > #\5f Emc` in uBlock FIlters) can't be found w\o replacing `\` with `\\` in search field.

### Steps to Reproduce

1. Open `uBlock filters` in Dashboard
2. Search `google.*###center_col > #\5f Emc` - 0 matches
3. Search `google.*###center_col > #\\5f Emc` - 1 match, line 16

### Your environment

* uBlock Origin version: 1.20.3b4
* Browser Name and version: Chromium 75.0.3770.100 x64
* Operating System and version: Windows 10 v1607 x64

**Comment by gorhill** [comment]
Related: https://github.com/codemirror/CodeMirror/issues/5428

**Comment by gorhill** [comment]
Related commit: <https://github.com/codemirror/CodeMirror/commit/eb0ef20e96b4dfc821eb693982510af60ab6ac45>. Reading through the related issue, I am not too sure to understand why this was designed to way it is. In any case since I have [borrowed and modified content of CodeMirror's `search.js`](https://github.com/gorhill/uBlock/blob/eef76c49aebe539cb572f5aa704e56a9c2e7845e/src/js/codemirror/search.js), I can fix on uBO's side without having to ask for a change on CodeMirror's side.
