### ISSUE TITLE
when midnight lizard addon is added ublock's zapper is not working

### ISSUE THREAD

**Issue by rubysm** [uBlockOrigin/uBlock-issues#659]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [Yes] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When midnight lizard addon is added ublock's zapper and element picker not working as the problem may arise from midnight lizard bug or ublocks bug and i think a fix for this will resolve the issues or tell this issue to midnight liz addon developer to fix this. Hope the fix will resolve the issues.

### Your environment

* uBlock Origin version: latest version
* Browser Name and version: firefox latest
* Operating System and version: windows latest

**Comment by uBlock-user** [comment]
Incompatibility is not  a uBlock issue and neither something to fix.

**Comment by gorhill** [comment]
I would have investigated if there had been detailed repro steps. I at least installed the addon (after having to search for it and guess which browser), and zapping was working fine. So the issue is invalid because of poor issue report not providing the requested information.

**Comment by uBlock-user** [comment]
Zapper gets stuck for me on Chromium and doesn't move with the mouse

**Comment by uBlock-user** [comment]
STR --

Install midnight lizard on browser of your choice.
Browse to google.com, open context menu via right click and select Block Element..
Notice how its gets stuck on the first element and won't move any further.

**Comment by gorhill** [comment]
I tried on <https://news.ycombinator.com/> originally.

I can reproduce on `google.com`. On `google.com`, the extension is installing a whole page overlay in uBO's own picker frame which prevents uBO from receiving mouse events.

On top of this, that extension is a huge performance issue, I could tell already with the CPU fan, and this is confirmed when loading a page from the Guardian, bottom is with the extension, x scale is 4.5 second -- so it added extra seconds to a page which normally takes ~1 second to load.

![a](https://user-images.githubusercontent.com/585534/60755017-ce457200-9fb7-11e9-9e03-84546829749f.png)

So I consider the issue lies with the other extension, modifying the DOM the way it does is bound to create issue in not just uBO, and that is beside the serious performance issues
