### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by annadane** [uBlockOrigin/uBlock-issues#812]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock Origin seems to become "disabled", and I have to re-update the filters. I'm not sure what the trigger for this is, but it seems to happen after I close Firefox and open it again. When I click the orange button to update the filters, it doesn't take immediately, and I need to do it again. This is very weird behavior and I'm surprised to see it not reported. I can't be the only one having this problem? OS is Debian 10, happens on both Firefox 71 and Firefox ESR

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by annadane** [comment]
It tends to happen when I close Firefox and then reopen it?

**Comment by uBlock-user** [comment]
Storage issue ? https://firefox-storage-test.glitch.me/

Post results here.

**Comment by annadane** [comment]
Overview:
Storage is working. This is your first visit or all storage was automatically cleared.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

Debug Info:

{
  "v": 1,
  "curVersion": 71,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 71
  },
  "idb": {
    "persistentCreatedIn": 71,
    "persistentLastOpenedIn": 71,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 71,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 71
  }
}

**Comment by annadane** [comment]
I wonder if it's my .mozilla folder getting corrupted, or something... I don't know why it would break on closing/reopening the browser. It seems to only be that.

**Comment by uBlock-user** [comment]
any `about:config` changes ? FPI ? RFP ? Delete cookies and site data when Nightly is closed ?

**Comment by Espionage724** [comment]
Can confirm a similar experience, and it doesn't seem specific to uBlock (Cookie Auto Delete extension wasn't saving a few settings either)

- Fedora Workstation 31
- Firefox 71
- uBlock Origin 1.24.2
- Not loading any domains from any new filter lists I add or select (no number  are reported even after updating)
- Happens on a fresh profile (deleted `~/.mozilla`, opened Firefox, immediately downloaded uBlock Origin from FF's addon site)
- Storage test site linked above reports success on everything

**Comment by vnctdj** [comment]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO can't save its settings reliably.

Result of https://firefox-storage-test.glitch.me/ is exactly the same as @annadane's one.

@uBlock-user: no about:config changes, no FPI, no RFP, no delete cookies and site data when Firefox is closed: I deleted my whole profile folder before my tests.

### A specific URL where the issue occurs

The issue can be seen in uBO's dashboard.

### Steps to Reproduce

1. Open uBO's dashboard.
2. Go to "My filters" and write something, a comment is enough.
3. Apply the changes: it works.
4. Edit what you write at step 2.
5. Apply the changes: it won't work.

### Expected behavior:

uBO's settings must be saved without any problem.

### Actual behavior:

The behavior explained in "Steps to Reproduce" is just an example, checked checkboxes in the "Settings" tab, enabled filter lists, etc won't be saved reliably either.

The issue happens regardless of uBO's version.
The issue appeared since I upgraded to Firefox 71.

I can reproduce in Debian stable, Debian testing, but not in Windows.
This seems Linux-specific, as I get the same behavior as @Espionage724.

### Your environment

* uBlock Origin version: latest stable or latest beta, it doesn't matter
* Browser Name and version: Firefox 71
* Operating System and version: Debian testing or Debian stable, it doesn't matter

**Comment by vnctdj** [comment]
@gorhill: Using `about:debugging`, I can see uBO writes the following message in the console:

```
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:812
    method chrome://extensions/content/child/ext-storage.js:273
    InterpretGeneratorResume self-hosted:1159
    AsyncFunctionThrow self-hosted:695
Error: An unexpected error occurred ExtensionUtils.jsm
```

**Comment by gwarser** [comment]
Two examples on Windows 10:

- https://www.reddit.com/r/uBlockOrigin/comments/e6lr3x/ublock_origin_no_filter_lists_appear/faafsj5/
- https://www.reddit.com/r/firefox/comments/e8t6dg/addons_broken_after_updating_to_ff70/

**Comment by uBlock-user** [comment]
Is `dom.storage.next_gen` set to `false` ? If so set it to `true` and see if that helps.

**Comment by vnctdj** [comment]
`dom.storage.next_gen` is indeed set to `false` by default.
Setting it to `true` then restarting doesn't help.

**Comment by uBlock-user** [comment]
doesn't help as in ? Are you still seeing the issue ?

**Comment by DonQuixoteI** [comment]
The issue was fixed in Debian unstable (ver. 71.0-2). Changelog:
```
  * dom/indexedDB/ActorsParent.cpp: Work around lack of support for
    http://eel.is/c++draft/class.temporary#6.7 in compilers. bz#1601707 ...
```
uBlock works well again.
