### ISSUE TITLE
Popup User Interface difficult to understand

### ISSUE THREAD

**Issue by missmatsuko** [uBlockOrigin/uBlock-issues#867]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Apologies if this is a repeat. I couldn't find an existing issue, but 'popup user interface' is not a very unique search term.

<img width="206" alt="Screen Shot 2020-01-21 at 6 17 32 PM" src="https://user-images.githubusercontent.com/17884198/72860017-741dad00-3c7a-11ea-90d8-039d4c5da363.png">

[The wiki describes the popup interface's functionality](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), but I think it should be redesigned altogether.

I find the whole popup interface very difficult to understand, especially since I don't use it frequently so coming back to it after a while is disorienting. 

The giant power button I find ugly and also the controls are not intuitive (clicking once to disable for the site, ctrl + click to disable for a page). I would have expected it to turn off the extension entirely, until I turned it back on again.

The icons aren't clearly related to what the button actually does. Even though there's a tooltip on hover, I think the actions should be easier to understand without hovering on it for a few seconds (which is not possible with keyboard navigation, AFAIK).

- The lightning bolt icon temporarily removes elements. I would have no idea what to expect from the icon. It reminds me of a camera flash. If anything, I think a gun scope icon would make more sense (clicking something kills/removes it).
- The dropper icon permanently removes elements. Dropper icon usually copies content, like the color dropper tool in Photoshop copies color. I would've expected it to copy an element's selector maybe (which could be used in a rule), not permanently remove it from a page.
- The logger and dashboard icons seem like they could be mixed up. Usually a logger icon has a console starting symbol like `>`, but this one has multiple lines so it kind of looks like an options menu.
- The 2 papers icon looks like an icon commonly used to copy things. It actually blocks all popups on the site. I think it would make more sense to have a new window with a circle and diagonal bar over it.
- The film strip icon blocks media on the site. I think it would make more sense to have a video icon with a circle and diagonal bar over it.
- Eye with a cross over it disables cosmetic filtering. I don't really know what that does, but it looks like what it should do is make something invisible (no eye, can't see).
- The A icon blocks remote fonts. That's better I guess. I think it would make more sense to have a fancy letter (like a custom remote font) with a circle and diagonal bar over it.
- The `</>` icon blocks JavaScript. Well then why does it looks like an empty HTML element? If the diagonal line is actually crossing something out like the diagonal line over the eye icon... I still don't get why the triangle braces since it still looks more like HTML than JavaScript?

It also wasn't clear to me why some icon buttons are at the top and some are at the bottom. It would help if there were a label to say one set is tools and the other is specific to the current site.

To me, the requests blocked and domains connected stats are not that useful and distract from the tasks I most often want to do (usually want to go to settings to disable something or add a rule). Are there a lot of people that use this information? If it's going to be there, I think you should be able to click it to see the details about the requests and domains and to possible enable/disable them. It just doesn't seem very useful otherwise. I also don't think showing the number of requests blocked as a number on the extension toolbar icon is that useful, and might be distracting from other extensions that are actually counting notifications or something else useful.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce
1. Open the popup UI and try to figure out what everything does just by looking at it. If you find it intuitive, ask someone that's never used it before to give it a try.

### Expected behavior:
The popup UI should be less cluttered and easier to understand.

### Actual behavior:
The popup UI seems to have a lot of unnecessary details, and is difficult to understand.

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
>  It would help if there were a label to say one set is tools and the other is specific to the current site.

Every tool has a tooltip associated with it, hover the mouse over and it will appear.

**Comment by missmatsuko** [comment]
I know:
> Even though there's a tooltip on hover, I think the actions should be easier to understand without hovering on it for a few seconds (which is not possible with keyboard navigation, AFAIK).

**Comment by gorhill** [comment]
>  I think it should  ... I find ...  I don't use it frequently ... To me ...

Best is that your fork and make it what is best for you. uBO is used by tens of millions of users and status quo to preserve familiarity trumps changing everything to suit someone's subjectivity.

**Comment by missmatsuko** [comment]
You'd rather have an unintuitive UI instead of an improved one that is
easier for all users, new and old?

Do you think no software with a large user base should ever change because
it's existing users would yet confused? I guess I should go tell all the
big tech companies to stop changing their UIs forever, even if it's an
improvement. 😂

**Comment by gorhill** [comment]
This is a *personal* hobby project which purpose is to express my *own* software crafting inspirations and urges, not the product of "big tech company". There is also the fact that I rather spend my free time the way I wish and being told to re-write everything is incompatible with this. I make changes incrementally as I see fit over time, and the record shows that I am open to pointed, specific and well argued incremental improvements. Your request amount to "re-write the whole thing according to my opinions" and I am not open to this sort of request. The license allows whoever to fork it and make it whatever they want according to their own inspiration when they feel they can do better.

**Comment by missmatsuko** [comment]
I did give details, especially about each icon: what it looks like and why
it doesn't relate to its function, and some suggestions for an icon that
would be more related to what it actually does.

Even swapping out the icon images could make a big improvement with minimal
code change.

Why do you just shut down the whole issue instead of asking for help on
this? I would not mind making some new icons if you'd asked.

**Comment by gorhill** [comment]
I disagree that changing the icons is useful, this is entirely subjective. There are tooltips to assist in finding out their meaning, I find this sufficient. Once one is accustomed as to what they do, the tooltips are no longer needed when memory muscle takes over. Changing them would affect negatively all the existing users, I would be the one dealing with the onslaught, and I am satisfied with how they look, so to reiterate, declined.

**Comment by missmatsuko** [comment]
I disagree that what I wrote about the icons is just subjective. Using
icons commonly used on other apps for other purposes can be confusing, and
using icons that don't look like what they do is also confusing.

If the existing users can use the functionality by muscle memory, it
shouldn't matter if the icons are swapped out and you won't have an
onslaught of users complaining. 🙂

**Comment by gwarser** [comment]
How long you are using uBO? You don't even seem to be aware of what these buttons do, and want to invert the meaning. Your desire to change the icons just a tiny bit to make them *your way* and *better from your point of view* looks like just very subtle trolling.

**Comment by kulfoon** [comment]
I don't see trolling there...

I have to admit that a couple icons could be replaced with more suitable equivalents:

1. the "popups" icon: the actual icon "The 2 papers" icon doesn't resemble anything associated with pop-ups, it resembles a copy function commonly used in most apps, so it should be replaced with a real "popups" icon like:   <img src="http://cdn.onlinewebfonts.com/svg/img_522812.png" width="25" height="25"> 

2. the "remove elements" icon: the actual icon "lightning bolt" icon doesn't resemble anything associated with removing things, it resembles just doing something quickly, which enforces an user to guess what it is actually doing or hovering a mouse cursor to see a tolltip description, I guess the intention here was to be an opposite to the "element picker" icon which is used to select things more carefully (cherry-picking) and thus slower before removing them, I must admit that as an long-time advanced user I got used to the current lightning bolt icon because it reminds me to "quickly remove an element" always when I want to quickly remove an element...with emphasis on "quickly"...but if we focus at "removing" rather than at "removing quickly" a typical rubber icon would fit better: <img src="http://cdn.onlinewebfonts.com/svg/img_562687.png" width="25" height="25"> <br> or perhaps the tolltip description of the lightning bolt should be changed from "removing element" to "removing element quickly".

3. the "JavaScript" icon: the actual "**</>**" icon resembles more an html element rather than a script element, it seems an "**{;}**" or "**JS**" would be more suitable or the the best of the both worlds: <img src="http://poldas.pl/wp-content/uploads/2014/09/js-icon.png" width="30" height="30"> <br> or "**{JS}**"

4. the "logger" icon:  might be confused with a [hamburger menu icon](https://www.google.pl/search?q=hamburger+menu+icon&source=lnms&tbm=isch) , (at least not with the Firefox's one as the Firefox's one lacks a border and dots)

5. the "open control panel" icon: it seems both: the actual dashboard icon:  <img src="https://cdn.onlinewebfonts.com/svg/img_508590.png" width="25" height="25">  and an gearwheel icon: <img src="https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/32x32/plain/gearwheel.png" width="25" height="25">  ( or <img src="https://cdn3.iconfinder.com/data/icons/elegant-1/32/Cog_cogwheel_gear_gearwheel_settings_icon-01-512.png" width="25" height="25">) are equally commonly used in apps for "setting things" thus any of them is acceptable.

**Comment by nyanpasu64** [comment]
I've used the old ublock0 PC interface for several years, and recently discovered it was replaced by a redesigned one with bigger icons. For a long time, I didn't understand what the icons meant. (I won't comment over whether the icons are good or would benefit from changing.)

I think that uBlock Origin's popup interface would be significantly more intuitive if each icon was labeled, not just relying on tooltips. I feel the new uBlock Origin UI with padding *may have* enough room for abbreviated labels in a small font, or longer labels if the buttons are enlarged.

I'm not a UX designer, but there is some research indicating that unlabeled icons are confusing and don't convey meaning well: https://www.nngroup.com/articles/icon-usability/, https://uxdesign.cc/do-icons-need-labels-6cb4f4282c00.

KDE apps label their toolbars by default and I find myself liking that. The tradeoff is that labels with icons take up significantly more space, reducing the number of buttons you can fit. (Personally I feel that toolbars with 20+ icons are too dense and cluttered and undiscoverable.)

**Comment by Efreak** [comment]
Related: on Android there isn't any popup tooltips, so the only way to find out what something does (or how to do something) is to go to the wiki; since there's no immediately obvious link to the wiki, that means searching for it. The wiki itself doesn't make it easy to figure out what a specific icon does, as it doesn't describe the icons and thus I can't simply search the wiki for filmstrip, eye, lightning bolt (*flash* is not a good term).

I'd be happy to help with some of this, however only if I know said changes would be welcome (I'm not interested in wasting time making wiki edits that will just be reverted), and it would have to wait for me to be on PC instead of mobile (and also remember that I want to do this--on PC I have no such problems, and I'm the type to only remember things when I'm frustrated with them)

**Comment by gwarser** [comment]
@Efreak 

> Related: on Android there isn't any popup tooltips, so the only way to find out what something does (or how to do something) is to go to the wiki;

One comment above:

>the mobile interface has labeled buttons, and you can easily discover the functionality of all buttons in a few seconds.

Hmmmm...

>The wiki itself doesn't make it easy to figure out what a specific icon does, as it doesn't describe the icons and thus I can't simply search the wiki for filmstrip, eye, lightning bolt (flash is not a good term).

Go and improve it?

**Comment by Efreak** [comment]
I'm on mobile, I see no labels. I see the layout shown at the top screenshot, not the one nyanpasu64 showed. I'm also on firefox stable, not preview, so that may be part of the reason (I won't be moving entirely to preview until at least tampermonkey and preferably also xstyles are working).

**Comment by gwarser** [comment]
Hmmm, tablet mode. @gorhill? You can enable lables by setting `uiPopupConfig` in advanced settigns to `+captions`.

**Comment by gorhill** [comment]
I don't understand what I am seeing. It looks to me he is using Firefox desktop version but the popup panel is opened in a tab?

**Comment by nyanpasu64** [comment]
As a user of Firefox Preview, I switched away from it because it's too buggy. Pages turn white and Firefox crashes more often than before (same in Firefox Focus), some links aren't clickable, the browser sometimes shows a white screen and "pull to refresh" when purged from RAM and you switch back to it, etc.

**Comment by Efreak** [comment]
@gwarser thank you so much. I had actually left advanced features disabled and ignored that page because I assumed it was unnecessary. The `popupFontSize` is also useful; I tried to override the `uiStyles` to make the captions larger, but `uiStyles` doesn't work (doesn't appear in list, disappears after applying if added manually) on 1.27.10, despite wiki saying it's available on 1.27.5b1 and later. (I'd like to enlarge the captions, but that's a minor consideration)

Enabling captions should probably add labels to the refresh/lock/erase icons that show up when you make a change. These are easy to remember, but not intuitive--I expected the refresh icon to reload the page.

**Comment by gwarser** [comment]
> but `uiStyles` doesn't work (doesn't appear in list, disappears after applying if added manually) on 1.27.10, despite wiki saying it's available on 1.27.5b1 and later.

It work on 1.28. 1.27.10 was bugfix release.

>-I expected the refresh icon to reload the page.

This is what it does.

**Comment by gorhill** [comment]
Locking this issue which was closed a long time ago. Questions/support is at <https://www.reddit.com/r/uBlockOrigin/>.
