### ISSUE TITLE
uBlock Origin for Edge

### ISSUE THREAD

**Issue by gdata1** [uBlockOrigin/uBlock-issues#890]
Hello. why are there no updates for Microsoft edge? In the store edge addons version 1.23. I wrote to the official addon development page for Edge but received no response.

**Comment by uBlock-user** [comment]
cc @nikrolls

**Comment by uBlock-user** [comment]
https://github.com/nikrolls/uBlock-Edge/issues/133#issuecomment-581249110

**Comment by mapx-** [comment]
if it's about 1.23 => edge chromium version and not the outdated nikrolls's version for old edge

**Comment by uBlock-user** [comment]
Old Edge has already been deprecated since last year, so this is about the Chromium fork with Edge branding in MS Store.

**Comment by gorhill** [comment]
I think he needs to install directly from Chrome store -- Microsoft used to pull the extension from the Chrome store but they stopped doing this and have been asking for maintainers to now take over publishing in the Edge store. I can't publish in the Microsoft store.

**Comment by gdata1** [comment]
@gorhill why can't you publish? as far as I know there can be published as for chrome unchanged.

**Comment by gorhill** [comment]
I don't have Windows (so I can't test uBO in Edge), and I don't have a developer account with Microsoft.

**Comment by gdata1** [comment]
I have a developer account. if you want I can give you it for publication. I can try to publish the latest version myself.

**Comment by gorhill** [comment]
Given the issues with the current publication, I rather no longer rely on someone else publishing for me. So for now it's install from Chrome store, or wait until the day I published myself in the Microsoft store.

**Comment by gdata1** [comment]
@gorhill Thank you. I think at this stage I will install from the store chrome. but in the future, I'd like you to publish an extension in the edge store.

**Comment by RespectIsEverything** [comment]
> 
> 
> I don't have Windows (so I can't test uBO in Edge), and I don't have a developer account with Microsoft.

Edge Chromium is also presently available on MacOS. Linux distributions on the horizon.

Nik Rolls isn't actively maintaining the port. It's also unknown what steps would have to be taken in order to reclaim the name. 

Looking forward to the day you do decide to publish in the Microsoft Store. Thanks!

**Comment by RespectIsEverything** [comment]
> I don't have Windows (so I can't test uBO in Edge), and I don't have a developer account with Microsoft.

Edgium is on Mac too. So can be tested there. Linux port also on the way.

If it's a financial issue, Microsoft would likely give you a free account and licenses especially given the popularity of uBO.

Twitter: @MSEdgeDev

**Comment by rishavs** [comment]
@gorhill , can you not test this on macOS itself?

**Comment by Hrxn** [comment]
Seems to have the latest stable for me...

https://microsoftedge.microsoft.com/addons/detail/odfafepnkmbhccpbejgmiehpchacaeak

Does this mean the extension is pulled automatically again?

**Comment by gorhill** [comment]
Link added to <https://github.com/gorhill/uBlock/releases/tag/1.26.0>.

**Comment by gwarser** [comment]
>This is kept up-to-date with the latest version on the Chrome Web Store.

@nikrolls are you doing this manually? Or MS is again pulling extensions from Chrome Store?

**Comment by gwarser** [comment]
@gorhill readme should be fixed https://github.com/gorhill/uBlock#microsoft-edge

Link to MS store corrected, and note about issues removed.

**Comment by nikrolls** [comment]
@gwarser I'm doing this manually. I have looked into automating it but it may be challenging with the (understandable) security measures on Microsoft's partner portal to write some kind of browser automation. Ideally they would release an API like Chrome's store but that doesn't exist yet.

I do understand people's doubts considering my track record of life getting in the way of keeping things up to date. The good news is that the process is now super easy: login, drag & drop the same package already built for Chromium, and submit. It takes 5 minutes max, versus the very time consuming merge, test, debug, package, flight, submit process for the previous Edge. I've also got notifications set up for every release so I don't miss anything.

I am also not intending to hijack or keep ownership of anything. I'm continuing to do this because it maintains the discoverability for Edge users and keeps users who have already installed uBlock from the Microsoft Store up to date, but I have no ego involved in being the one who maintains it. If @gorhill prefers to take this over, considering that this new browser is identical in terms of compatibility and can also be tested on Mac (and soon Linux), I would totally understand and do everything possible to facilitate that. We would just need to talk to Microsoft about how to move the extension to a different account, as this is not a common process for them.

**Comment by kq01526** [comment]
Hi @gorhill ,

Are there any news on this one?

Looks like @nikrolls mentioned he would be willing to hand over the MS Store entry (see previous post).

MS Edge has now also been made available for Linux and macOS in the meantime.

It would be good if the MS Store version would be maintained by the upstream dev.

**Comment by gwarser** [comment]
Version on Edge Add-ons is regularly updated https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak

**Comment by kq01526** [comment]
@gwarser But not by the original developer of uBlock Origin ( which would be @gorhill ).

Instead, the version on the MS Edge Store is being updated by @nikrolls (who is not the original developer of uBlock Origin as far as it seems).

**Comment by nikrolls** [comment]
@kq01526 The code is identical. The Chromium package is automatically downloaded from the GitHub release and uploaded to Microsoft completely opaquely.

Currently there is no API for Microsoft like I understand is used for the Chrome store submission. An API is in progress with Microsoft. I suspect this may be a preference for taking over store submission from me, to fit in with existing automation.

Then there is the technical issue of moving the ownership of the Store listing between developers. Historically this wasn't possible with Microsoft, and I can't see any documentation for it now (though it may or may not be available on request).

**Comment by kq01526** [comment]
Hi @nikrolls ,

Thanks for chiming in on this, this is appreciated.

Assuming a direct transfer of the ownership is not possible, then:

What would happen if you would delete the extension from the MS Edge Store so that @gorhill can re-create it?

There is a Microsoft contact email address listed in the following blog post:

* https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/

Maybe they can help with the transfer?

PS: It's not meant to downplay your current efforts, it's just meant to be a constructive discussion about how to get the ownership of the MS Edge Store version aligned (also considering that you also seem to think that handing it over to @gorhill would make sense).

**Comment by nikrolls** [comment]
If we were to delete the listing, then the hundreds of thousands of users who have it installed will be stranded on that last version and will likely not even know they need to uninstall and switch to the new one (and would have to do a manual data transfer).

I have contacts in Microsoft and the Edge team who I can reach out to for checking feasibility of ownership transfer if @gorhill is at a point where he'd like to do this. No strong feelings on my end either way 🙂

**Comment by gwarser** [comment]
@nicole-ashley ping! 1.43.0 not released after three weeks.

**Comment by nicole-ashley** [comment]
Apologies - busiest couple of months in a long time for me.

There seems to be an issue with the Store at the moment. I tried this morning and this evening. I'll try again tomorrow and file a case with them if it's not working.
![image](https://user-images.githubusercontent.com/2626677/177111595-a46341ad-adb0-4815-be6a-e4950cde41c1.png)

It also appears that the API for submitting extension updates is now available. Hard to tell for sure based on the wording in the documentation if it's fully functional, but I'll have a play and if it's usable then it should be trivial to fully automate this release process with an Azure function.

**Comment by nicole-ashley** [comment]
@gwarser OK, everything is now fully automated. Within an hour of a new Chromium release going public (ie, a release with a `chromium` asset having the `prerelease` flag turned off), the package will be automatically uploaded to the Edge Addons Store and submitted for review. If a newer release comes out before review has started, the package for review will be replaced with this newest version. If there are any errors in this automation I'll be notified directly on my phone.

This latest submission has been made entirely through this automation and was successful (ie, successfully in review phase).

**Comment by gwarser** [comment]
@nicole-ashley something stuck on 1.47.2

**Comment by gorhill** [comment]
@nicole-ashley I've enrolled as a Microsoft Partner and I got accepted as a "Microsoft Edge extension developer", so I guess I am all setup be able to publish extension?

I can now test uBO in Microsoft Edge since it is now available on linux, so if you still want to transfer ownership of uBlock Origin, I guess I am now ready for this.

Currently I think there is an issue with uBO in MSEdge store, and it's probably my fault, as I mistakenly create a stable release of uBO with the wrong version number, I had to delete the published release shortly after I realized the mistake, and maybe this broke the script copying from GitHub.

**Comment by nicole-ashley** [comment]
@gorhill I'll see what I can do. I think there were restrictions regarding republishing the same version number, but it's been a while and that may have changed by now. I can also contact Microsoft about transferring ownership.

**Comment by gwarser** [comment]
Stuck again on Version 1.57.2.

**Comment by marcussacana** [comment]
> Stuck again on Version 1.57.2.

I think may be due manifest v2

**Comment by gwarser** [comment]
Jumped straight to 1.59.0 yesterday.

**Comment by stephenhawk8054** [comment]
Currently stuck on 1.62.0

**Comment by u-RraaLL** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/update/transfer-ownership

**Comment by Verity-Freedom** [comment]
@nicole-ashley
