### ISSUE TITLE
uBO 1.16 crashes on Chromium 66

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [uBlockOrigin/uBlock-issues#9]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin 1.16 (1.16.0 from the Chrome Store and 1.16.1rc1 from GitHub) immediately crashes on Chromium 66.
Tested on a clean system without any leftover Chromium profiles.
uBO 1.15.24 works fine.

### A specific URL where the issue occurs

chrome://newtab

### Steps to Reproduce

1. Install Chromium 66: https://github.com/henrypp/chromium/releases/download/v66.0.3359.117-r540276-win64/chromium-nosync.zip (current stable build without WebRTC)
2. Install uBlock Origin 1.16

### Expected behavior:

uBO should work.

### Actual behavior:

uBO crashes indefinitely, restarting uBO and/or Chromium doesn't help.

### Your environment

* uBlock Origin version: 1.16.0 and 1.16.1rc1
* Browser Name and version: Chromium 66.0.3359.117 x64 (no WebRTC)
* Operating System and version: Windows 8.1 x64

**Comment by gorhill** [comment]
What is the user agent string reported for that browser?

**Comment by nbmrjuhneibkr** [comment]
`Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36`

**Comment by nbmrjuhneibkr** [comment]
According to [this comment](https://www.reddit.com/r/uBlockOrigin/comments/8dxkcr/ublock_origin_116_crashes_on_chrome/dxqwvfz/), this issue only affects the Chromium builds _without WebRTC_ (I haven't tested this yet).

**Comment by gorhill** [comment]
> `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36`

That's the issue. I was expecting that Chromium builds would have a user agent string with `Chromium` in it.

**Comment by gorhill** [comment]
Fix is in 1.16.1rc2, however I can't upload it to the Chrome store, version 1.16.1rc0 is still "pending review" status. You will have to download and install from the Releases section. Please confirm that the issue is fixed, it's not something I can test on my side.

**Comment by HitomiTenshi** [comment]
I just had the same problem, `1.16.1rc2` fixes it for me. Would be great if this could make it into a stable release soon, as I am usually on the stable chrome store version.

**Comment by jspenguin2017** [comment]
> version 1.16.1rc0 is still "pending review" 

If you publish from command line then it goes through review instantly. I publish both of my extensions from command line and they were never stuck in review queue. 

I don't think you can use controlled rollout from command line though, might be a problem with stable version.

**Comment by gorhill** [comment]
This issue demonstrates that not enough people are willing to contribute by using uBO's dev build, otherwise this issue would have been found before release of 1.16.0.

**Comment by Qemics** [comment]
How do you install uBlock0.chromium.zip?

**Comment by gorhill** [comment]
You focus too much on the number itself: it's the release candidate, essentially it became 1.16.0 with no change, there was no point to create a 1.16.1.100 version unless there were changes in it. In the end, issues such as the current one is the price paid for not contributing back, I can't possibly be asked to catch everything myself (and anyways in the current case it requires a special Chromium/Windows build which I am not equipped to test)

**Comment by gorhill** [comment]
@jspenguin2017 

> I publish both of my extensions from command line and they were never stuck in review queue.

Do you have a script to share for this? I started to look into this back when I wrote the AMO one, both after trying to get all the info for the sequence of commands needed to do this I ran out of steam and didn't come back to complete this. Having the exact sequence of commands would be very helpful.

**Comment by HitomiTenshi** [comment]
@gorhill I didn't know that the dev version is up to date, even though the dev version number is lower than the stable version number. I'm just an outsider, I don't actually know how you develop uBO and I'm not here to tell you how to do your thing.

All I can say is that the version disparity made me think that the dev version is outdated.

I'm not here to bash anyone, I like uBO and I really appreciate all the work you put into it. I'll install the dev version when I'm home.

**Comment by uBlock-user** [comment]
Chromium builds with WebRTC disabled are prone to crashes and other unexpected things this is enable_webrtc flag has been deprecated by the Chromium project maintainers. So this bug is actually a bad Chromium itself and uBlock Origin is not causing the crash. 

This is why @RobRich999 recently stopped compiling builds with WebRTC disabled.

**Comment by gorhill** [comment]
I pretty much always push the latest dev build version to the Chrome store entry as soon as I publish a new beta/rc -- I really want people to have the latest so that all potential regressions/issues are caught before I publish a stable release.

The only thing out of my control is when the extension is "pending review", that is up to the Chrome store. Currently 1.16.1rc0 is still pending review -- I suppose there is no reviewer during the week-end -- I pushed it to the store late Friday:

![a](https://user-images.githubusercontent.com/585534/39124531-c9a9b604-46c9-11e8-8496-1210077ed71d.png)

The highest level of anxiety I each with this project is when I publish a stable release in the Chrome store, I really want to be seamless and not want to break anything for anybody, and the best tool for me to avoid this is that dev build.

**Comment by uBlock-user** [comment]
Tested With version `1.16.0` on SYNC builds(WebRTC • Widevine) from [nik's repo](https://github.com/henrypp/chromium/tree/v68.0.3399.0-r551264-win64), loads fine, nothing happens, so it was never a bug with the uBlock Origin, but rather a webrtc issue with the Chromium when disabled.

**Comment by gorhill** [comment]
Well it was a regression since uBO used to be able to deal with those Chromium packages build without WebRTC. The regression was introduced because I tried to avoid the special test used to detect non-WebRTC version for browser flavors which should not be affected by this, i.e. Firefox, Opera, Google Chrome. However it turns out those special Chromium builds are built with a user agent string causes uBO to detect them as being Google Chrome.

**Comment by uBlock-user** [comment]
But could it lead to browser crashing on boot ? Also how come SYNC builds like the ones I use are not crashing ?

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/533>.

**Comment by jspenguin2017** [comment]
@gorhill Yes, that's the correct file. 

You need a GAPI app, generate client ID (`WebStoreClient`) and client secret (`WebStoreSecret`), then give your app access to your Google account and generate a refresh token (`WebStoreAccount`).

**Comment by Eliastik** [comment]
Same issue with Chromium 66.0.3359.139 64 bits on Windows 10 (build "stable-codecs-nosync" from https://github.com/henrypp/chromium/releases ), immediate crash of ublock Origin, tried reinstalling.

**Comment by Qemics** [comment]
try version 1.16.2

https://github.com/gorhill/uBlock/releases
