### ISSUE TITLE
False positive url blocking via CNAME

### ISSUE THREAD

**Issue by HanabishiRecca** [uBlockOrigin/uBlock-issues#922]
### Description

False positive url blocking via CNAME. For example:
![image](https://user-images.githubusercontent.com/13597663/75631972-59dfd300-5c19-11ea-97d7-7d5358f1ee39.png)

Google fonts blocked at ALL sites. `||gstaticadssl.l.google.com^$3p` blocks `fonts.gstatic.com` which obviously is not intended.

Also exclusion rule `@@||fonts.gstatic.com` can't override this behavior. And this is the real problem.

Addition: there is `cnameIgnoreExceptions` option in advanced settings. It seems to be related to the problem. But switching it doesn't change anything.

### Versions

* Browser/version: Firefox 74b9 (developer)
* uBlock Origin version: 1.25.0

**Comment by gorhill** [comment]
> Also exclusion rule `@@||fonts.gstatic.com` can't override this behavior. And this is the real problem.
> ...
> This is no more than dirty workaround.
> ...
> Maybe this should've been considered before implementing doubtful feature that can't be unbreaked?
> ...
> Ya ya, 10/10 software development. Maybe we will try to resolve the issue? Pff who da hell cares

Purpose of exception filters is to override block filters. If there is no block filter in effect, there is no exception filters to apply -- exceptions apply *only* when a network request matches a block filter. Asking that `@@||fonts.gstatic.com` overrides a network request which URL does not match `||fonts.gstatic.com` makes no sense whatsoever.

The aliasing of hostnames is a server-side decision, this must never affects how uBO's filtering engine works -- something that is aliased today could be unaliased tomorrow and vice versa with no blockers having a say in this.

Bottomline is that if someone chooses to un-check _"uBlock filters -- Unbreak"_ and breakage ensues as a result, one _must_ own their choice rather than rudely shift blame onto others.
