### ISSUE TITLE
Website using WebSocket to send tracking info

### ISSUE THREAD

**Issue by smege1001** [uBlockOrigin/uBlock-issues#931]
### URL(s) where the issue occurs
`https://vlare.tv/v/IVyAvcK3`
(any video)
### Describe the issue

On every video page, when JWPlayer's `play` event gets triggered, Vlare sends a WebSocket message to the chat server that the user is currently watching a video (`!v1 [video id]`), and when `pause` or `idle` event gets triggered, Vlare sends a WebSocket message (once again) to the chat server that the user has stopped watching the video (`!v0 [video id]`)

This server can't be blocked because it can break the chat functionability.

Scriptlets are (probably) required for this, but there's no scriptlets for WebSocket at all.

### Versions

- Browser/version: Firefox Android 68.5.0
- uBlock Origin version: 1.24.2

### Settings

- Default

### Notes

- No notes yet.

**Comment by uBlock-user** [comment]
Does this require an account ? I'm not seeing any WebSocket connection request occuring when playing or pausing the video. One request does appear at the page load and once I block that, nothing else appears.

**Comment by smege1001** [comment]
No, It doesn't require an account. but that's weird, It works for me

![Screenshot_2020-03-07-12-42-49-1](https://user-images.githubusercontent.com/59537482/76143717-0b4b9200-607a-11ea-9efa-8724940710ba.png)
![Screenshot_2020-03-07-12-43-01-1](https://user-images.githubusercontent.com/59537482/76143722-14d4fa00-607a-11ea-8616-ee65e4bb5265.png)

**Comment by uBlock-user** [comment]
> No, It doesn't require an account.

I can't reproduce it then. I see one WS connection at the page load and thats it.

**Comment by gorhill** [comment]
I can see a websocket connection. However how is this a substantial privacy issue? The remote server already know that you are visiting the page, and what you are chatting if you use the chat feature.

When you connect to a remote server, assume they already get a lot of information from you. Best is that if you worry about this one trivial behavior, your best approach is to wholly block the websocket connection. It breaks chat functionality but this is a choice that you will have to make, the same way that on my side I made the choice of blocking Disqus or Gravatar and live with the broken functionality.

Declined because I do not see a convincing case made for adding such a scriptlet. Additionally, asking filter list maintainers to deal with in-websocket network traffic is to open a whole can of burden, there has to be many more convincing cases that filtering in-websocket network traffic is of substantial interests to all users.

**Comment by smege1001** [comment]
Hmmm, I guess you're right
