### ISSUE TITLE
RU AdList abuse issue

### ISSUE THREAD

**Issue by AngryPhantom** [uBlockOrigin/uBlock-issues#941]
Hello, Raymond and others.

Sorry if it doesn't really fit your issue template but the topic is a bit **resonant** on russian forums. Here is the original news: https://www.opennet.ru/opennews/art.shtml?num=52515

Here is the translation:

"RU AdList is a popular subscription in the Russian segment that contains filters for blocking ads in browser-based add-ons such as AdBlock Plus, uBlock Origin etc. Currently, members under the nicknames "Lain_13" and "dimisa" are engaged in supporting the subscription and making changes to the blocking rules. Particularly active is the second author, which can be judged by the official forum and the history of changes. Official support for the block list is provided in the corresponding [topic](http://forum.ru-board.com/topic.cgi?forum=5&bm=1&topic=50474#1) on the Ru-Board forums.

After a sluggish conflict with one of the users (NikosColev), the author (dimisa), regarding the user's messages as trolling, but not getting a response from the moderators of the Ru-Board forum, took his own measures. On March 7, a rule was added to the RU AdList public list that blocks messages from this user throughout the entire Ru-Board space. Since the RU AdList subscription is popular in Runet, the user NikosColev lost the ability to communicate in all forum topics, many users simply did not see his posts.

**After researching** the RU AdList change list, Ru-Board users **found** that **it was not the first time** that the author (dimisa) changed the block list for their own purposes. In relation to the Ru-Board, on April 19, 2018, the user mikhaelkh was already blocked, on October 9, 2018, the user MP40, on March 6, 2020, **a whole forum topic** fell under the lock.

So the question is whether filtering something other than the ad itself is acceptable in the ad block list, and how much can this list be trusted now? In response to criticism of the use of an ad blocking tool to resolve personal conflicts and pressure on users, the author (dimisa) said that in the future **he will certainly act in exactly the same way**. He explained the blocking of NikosColev by the fact that his activity can be perceived along with the **promotion of malware**. After the information was deleted by the moderators from the forum, the corresponding rule was also deleted from the filters."

I see that there was an [issue](https://github.com/uBlockOrigin/uBlock-issues/issues/749) concerning the RU AdList (and the author is also there in the comments) promoting his filter and voting for the AdGuard filter to be excluded.

Well, actually, I don't understand why you dropped [AdGuard filter](https://kb.adguard.com/en/general/adguard-ad-filters#russian). The very first thing I do after installing uBlock Origin is that I remove RU AdList and import the russian AdGuard [filter](https://filters.adtidy.org/extension/chromium/filters/1.txt). I've also haven't experienced any issue with it as you mentioned [here](https://github.com/uBlockOrigin/uBlock-issues/issues/749#issuecomment-540079805).

Btw, there are issues from other users that this RU AdList filter allowed annoying ads on some russian sites like Mail.ru (after disabling it the ads were gone...). Strange, isn't it?

Is it somehow possible to revert back to using AdGuard by default? Thank you.

**Comment by uBlock-user** [comment]
@dimisa-RUAdList what is this about ?

**Comment by dimisa-RUAdList** [comment]
Most of this information is a lie. As for the temporary rules for hiding posts of an inadequate forum user, they were added with the knowledge of the forum moderators. If not for the holidays, they would use their rights to solve this problem. And it seems to me that the current question was asked just by that very user.

**Comment by AngryPhantom** [comment]
> And it seems to me that the current question was asked just by that very user.

What? Of course, not. Well, the best tactics is to blame people who create issues to your filter, isn't it?
@gorhill, you shoud really consider this now.

**Comment by dimisa-RUAdList** [comment]
Everything is very simple - this user has a "post ban" right now: https://i.imgur.com/FaliBmk.jpg
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474

**Comment by TheFinalCut83** [comment]
The "original" news from OpenNET is submitted in a biased form and does not correspond to a neutral reflection of the situation. NikosColev - troll and was repeatedly warned for violations of the topic's rules (flood), subsequently received a ban on the post. In fact, the topicstarter perhaps NikosColev himself or a user who strongly sympathizes with him and does not understand the situation, and did not see it from the very beginning. Please note that the author of this news on OpenNET is anonymous user ("Автор новости: Аноним"), which is not usual for the resource, it may be an indication that the author is NicosColev (regular news - https://www.opennet.ru/opennews/art.shtml?num=52513, https://www.opennet.ru/opennews/art.shtml?num=52500, without specifying the author.)

**Comment by P0Rtvine** [comment]
> Btw, there are issues from other users that this RU AdList filter allowed annoying ads on some russian sites like Mail.ru (after disabling it the ads were gone...). Strange, isn't it?

Strange, isn't it? 
Yes it's strange. You lie and don't blush.
Any examples?

**Comment by serj-kzv** [comment]
@uBlock-user No metter what parts of the news is a lie. The fact is some posts of some forum were hidden deliberately by RU AdList. It a censorship. In the Internet there are a lot of bad articles and fake news but we don't hide theme just because of some forum does not have moderators.

Also you can go on the news links and check all facts yourself.

**Comment by ediowar** [comment]
> And it seems to me that the current question was asked just by that very user.
I think this is not him, he is not able to express his thoughts correctly in his native language

**Comment by AngryPhantom** [comment]
> Everything is very simple - this user has a "post ban" right now: https://i.imgur.com/FaliBmk.jpg
> http://forum.ru-board.com/topic.cgi?forum=5&topic=50474

I repeat: I totally DO NOT relate to any of your forum users (even don't have an account there). I've read this today on opennet.ru. It's again a minus to your 'crown syndrome', I guess. In advance I stop talking to you here because it's nonsense and leads to personal insults. Period.

**Comment by serj-kzv** [comment]
@uBlock-user  I see that some people set dislikes, don't be confised. The opennet is quite popular portal and I think tomorrow here will be a lot of people and all will have their own opinions. And usually people don't like censorship in any form. ;)

**Comment by P0Rtvine** [comment]
@serj-kzv 
blah blah blah 😉

**Comment by ediowar** [comment]
Here, for example, is a translation of what forum user NikosColev writes:
> Here, for example, is a translation of what that author writes: But I don’t understand, if dimisa writes AdList RU and filters start with Adblock Plus, then dimisa works in Adblock Plus = RU AdList, so what? https://forum.ru-board.com/topic.cgi?forum=2&topic=5805&start=120#19

**Comment by Ajaja** [comment]
Just create additional RuTrollList subscription. Many countries will be grateful :)

**Comment by JustOff** [comment]
If my opinion means anything to you, then I must say that although I do not really like the fact that one of the default regional filter lists was used to pacify one specific person, this troll definitely deserves this for destructive behavior, which has repeatedly confused users and interfered with the support provided by the moderator of this list.

**Comment by prius** [comment]
RU AdList is not here for solving personal conflicts. If somebody does that it is an abuse. I can't see how this behavior can be justified.

**Comment by uBlock-user** [comment]
Locked until @gorhill addresses this and before this turns into a spamfest.

**Comment by gorhill** [comment]
Right, a filter list should not be used as a way to enforce personal views not related to the primary purpose of the list.

However there are two sides here and I am not in a position to make my own judgment, I don't read Russian.

But even if I go with the assumption that the list was abused as stated here, you can't erase years of contributions by @dimisa-RUAdList and @lain566<sup>[1]</sup> just because of one single event which seemed to have been a source of stress to key contributors to the list -- these contributors have volunteered countless hours of their own time for years, it's not something that can be ignored because of one single disputed commit. So RU AdList will not be removed.

> I don't understand why you dropped AdGuard filter.

RU AdList was kept as the default RUS list on the advice of AdGuard's @ameshkov, see <https://github.com/uBlockOrigin/uBlock-issues/issues/749>.

***

[1] <https://hg.adblockplus.org/ruadlist/shortlog>, <https://hg.adblockplus.org/ruadlist/shortlog>/e8f002bd5534

**Comment by dimisa-RUAdList** [comment]
@gorhill 
As far as I can see, my actions are interpreted incorrectly. The rules for hiding troll posts were not added due to personal conflicts, vendettas or censorship. The reason was the harm done to other users, not to me. It arose because the trolls posted information, the use of which led to the incorrect operation of adblockers. And they did it not somewhere, but in the topic of support. For ordinary users, their advice was indistinguishable from competent. This was compounded by the fact that the moderation policy on this forum in most cases does not involve deleting messages, even if the user who wrote them receives a ban. Repeated warnings and rebuttals were unsuccessful and hiding posts in the filters was the only way to prevent harm to visitors to this topic.

**Comment by mikhaelkh** [comment]
@dimisa-RUAdList 
Lets discuss your actions, not the actions of others. You are hiding messanges of users in the whole 3rd-party forum in RuAdList subscription [here](https://hg.adblockplus.org/ruadlist/rev/051af9f844f6). Instead of doing that, why don't you get moderation right in that topic of the forum? If that topic cannot be moderated properly I suggest moving support to [official forum](https://forums.lanik.us/viewforum.php?f=102) where proper moderation can be done. Using adblock subscription to emulate moderation on a 3rd-party forum where you have no moderation right is abuse of power, however you might justify it does not make it acceptable.

**Comment by freehck** [comment]
@dimisa-RUAdList 
I'm one of the moderators from OpenNet.Ru where the original news was posted.

What I want to say is that your actions dramatically harmed the trust to your work. Any Ad List purpose is blocking Ads. It's not your personal playground to handle your personal conflicts. So it's good that this Issue was created. Although this time you're not banned from uBlock, I hope that after this specific Issue next time you'll think before performing such actions.

I understand that you consider your actions to be like a simple moderation. But the difference is the responsibility. Moderators are only in response of their own local forums. You're in response of Russian Ad list. For now. But even moderators are constantly blamed for censorship, and everyone consider it as a bad thing. The only reason people don't run from moderated forums is that moderation must follow forum rules. On the other hand the Ad List you contribute to. You don't have any rules about moderation. The Ad List is even an instrument with another purpose.

What you need to understand is that using the Ad List for such purpose is totally unacceptable.


@dimisa-RUAdList 
Also about insults and the reaction to them. I noted that you wrote in the very first post that "most information in that article is a **lie**". Do you really want to say that our news edition with articles pre-moderation policy isn't good enough? Why in this case didn't you come to us "to reveal the truth"? Or shall we wait for our resource to be blocked in Ad List?

We can post a rebuttal, just come to us with **facts**. Unlike @gorhill I perfectly read Russian and will be glad to assist.


@ediowar 
Although this is not a place for such ad hominem, I can note that on our forum this user seems to be adequate.

**Comment by freehck** [comment]
@gorhill 

> But even if I go with the assumption that the list was abused as stated here, you can't erase years of contributions by @dimisa-RUAdList and @lain566[1] just because of one single event which seemed to have been a source of stress to key contributors to the list -- these contributors have volunteered countless hours of their own time for years, it's not something that can be ignored because of one single disputed commit. So RU AdList will not be removed.

I mostly agree, but need to note that the contributor seems to be stressed not because of this case, but because of its publicity. It was revealed that @dimisa-RUAdList performed such actions for **years**:
https://hg.adblockplus.org/ruadlist/rev/f9efe1518417#l1.12
https://hg.adblockplus.org/ruadlist/rev/197bb994911f#l3.12
https://hg.adblockplus.org/ruadlist/rev/d83245c775dc#l1.12

> > I don't understand why you dropped AdGuard filter.
>
> RU AdList was kept as the default RUS list on the advice of AdGuard's @ameshkov, see #749.

I understand your point. But at least we shall keep tracking his activity for such incidents to not happen again. If they continue then be sure you'll see another Issue.

**Comment by freehck** [comment]
@TheFinalCut83 

> Please note that the author of this news on OpenNET is anonymous user, which is not usual for the resource

It's usual for our resource. We appreciate anonymous authors sending us their articles. Of course these articles are carefully pre-moderated and checked before posting to public space.

**Comment by TheFinalCut83** [comment]
@freehck 
Right now, in the main news section, minus the one being discussed, there is NOT A SINGLE news item authored by an anonymous person. I don't know how many years you've been moderating it , but I've been reading your resource for years and I can see perfectly well that such news is an extraordinary event.

**Comment by ediowar** [comment]
@freehck
> @ediowar
> It's not a place for such ad hominem.

What do you mean?

**Comment by NikosColev** [comment]
> Here, for example, is a translation of what forum user NikosColev writes:
> > ...I will try to make up a story for Habr.ru

Корректный перевод, спасибо. Для Хабра я сочинил как и обещал, заметка висит в Песочнице.

Если есть желание попереводить ещё, - вот лаконичное описание этих эпичных событий с пруфами и картинками:

**СТЕРЕТЬ НЕЛЬЗЯ БЛОКИРОВАТЬ** - [ссылка](https://zen.yandex.ru/media/id/5ac57043c3321bc44e25b095/steret-nelzia-blokirovat-5e6b539cbf10282bbfef6d88)

Впрочем, для чтения одной страницы знаний русского языка не требуется и, при желании разобраться, @gorhill сможет сделать это самостоятельно.

**Comment by freehck** [comment]
Pals, everyone, both sides just spam the Issue. That's not a good approach to discuss problems. I understand that the Russian community is much more toxic than international one, but please don't forget that you write it on github bug tracker.

@TheFinalCut83 
I am a moderator since 2014, i.e. 6 years already, and glad to meet our follower outside the resource. Nevertheless, we usually have up to 5 anonymous news every month, so please be careful with your statements. Here's the prooflink: https://www.opennet.ru/~Аноним

@NikosColev 
Please, this is not a Russian project. It's very impolite to speak Russian here. The problem we discuss here doesn't relate to the reasons what happened before you were put into Ru AdList, and there's no need for @gorhill to read the story about it (espesially written with the language that's not an easy challenge for on-line translators).

@gorhill 
How about to lock this thread for several more days? For a week maybe?
