### ISSUE TITLE
List author slack channel?

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#956]
Hey,

(not sure if this the correct way to bring this up)

Just a thought whether a Slack channel could be an option for list authors / friends of uBlock/ABP/other Adblock extensions. For easier interaction/collaboration between authors, this isn't replacing Github but helping 'collab between list authors.

Won't be a public slack channel, open only on invite.

Its just a thought.

**Comment by llacb47** [comment]
Check out https://github.com/DandelionSprout/adfilt/issues/63

**Comment by uBlock-user** [comment]
Just received a mod-msg on reddit that "chat-post" are now available, can be used instead of having to create yet another yet account on another platform --

<details>

A new feature has become available to your community! Your community is now able to create Chat Posts. Please read all of the details in our r/modnews post.

This feature allows you to create a post that has a chat discussion rather than a comment thread. We wanted to give communities the ability to have real time discussions.

Try it now in your community by creating a post and selecting “Live Chat” as an option!

Tips & tricks

Some of the best uses of this product we’ve seen are when mods create a chat post for:

    A daily or weekly chat thread (“Free Talk Friday”)

    A significant event like album releases, breaking news, politics, etc.

    Live events like game days, watch parties, episode discussions, etc.

You can sticky a chat post to act like a chat room. For example you can create a “lounge” for your community members to hang out and chat with each other.

Automod works for these types of posts as well - so if you have automod setup you’ll automatically be covered

</details>

**Comment by DandelionSprout** [comment]
There was also https://hub.filterlists.com/ last autumn, until we ran out of things to discuss on it.

**Comment by ryanbr** [comment]
Forums and Github has a place, a good public facing reports and followups. Having quicker interaction in a realtime chat between authors / friends of uBO/ABP/Adguard (bouncing filter suggestion ideas realtime before/or after commits).

This isn't specifically a "uBo chat" platform, but a filter authors chat, will cover many/any extensions and lists. Slack is bit more agnostic than using reddit.com chat for a specific subreddit.

**Comment by mapx-** [comment]
reddit has a pretty poor notification system.
I guess we need a real channel (like the old irc channels with mirc clients or even mibbit.com web clients) with real time notification (even email).

So, irc, slack (if has these real time features) could be used. 
@ryanbr if you create a channel and then give us the essential info to use it, we could try it.

**Comment by uBlock-user** [comment]
> I guess we need a real channel (like the old irc channels with mirc clients or even mibbit.com web clients) with real time notification (even email).

Speaking of IRCs, how about matrix or discord ? Mozilla recently moved from IRC to matrix.

**Comment by ryanbr** [comment]
Okay, since its private. If users can message me (https://forums.lanik.us/ or email, mp3geek@gmail.com) for an invite link. If @mapx- @uBlock-user @DandelionSprout @llacb47  is keen to trial it out, happy to include any others.

Matrix is using riot.im? designed for self hosting slack-type interface (can see value there).

**Comment by DandelionSprout** [comment]
You guys are technically in luck, as I made a RiotIM account just last week or so on the bidding of a friend of mine. So I guess I'll go through this whole invite and membership thing tonight or tomorrow.

**Comment by llacb47** [comment]
@ryanbr sent you a PM on forums.lanik.us.
