### ISSUE TITLE
Reverse lookup occasionally fails for static filters created via Picker 

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#968]
### Description

As above and as discussed in https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/176

### A specific URL where the issue occurs

`https://httpbin.org/`

### Steps to Reproduce

- Add `httpbin.org###operations-tag-HTTP_Methods` to "My filters"
- Open the logger
- Navigate to `https://httpbin.org/`
- Click `#operations-tag-HTTP_Methods` in the logger -- this invokes reverse-lookup code
- Add any cosmetic filter via element picker for the same page
- Force a reload of the page
- Try to reverse-lookup the newly added filter
- Result: no filter list found

### Expected behavior:

Reverse lookup doesn't fail and reveals the filterlist

### Actual behavior:

Reverse lookup fails.

### Your environment

* uBlock Origin version: 1.25.3rc0
* Browser Name and version: Firefox 76
* Operating System and version: Win 10

**Comment by gorhill** [comment]
> Reproduction may be difficult

It's not. As detailed in previous conversation, you just need to invoke the reverse-lookup code before adding a filter -- you are missing that crucial step in your STR:

1. Add `httpbin.org###operations-tag-HTTP_Methods` to _"My filters"_
1. Open the logger
1. Navigate to `https://httpbin.org/`
1. Click `#operations-tag-HTTP_Methods` in the logger -- this invokes reverse-lookup code
1. Add any cosmetic filter via element picker for the same page
1. Force a reload of the page
1. Try to reverse-lookup the newly added filter
1. Result: no filter list found

**Comment by uBlock-user** [comment]
@gorhill Simplified, anything else ?

**Comment by kangnaclub9** [comment]
[gkapook2011gmail.com]() @

### Prerequisites





- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by garry-ut99** [comment]
Perhaps you are already aware of it, but in case if not, then a hint:
Uticking and ticking back **My Filters** or **Parse and enforce cosmetic fitlers** fixes the issue
I am not saying it's a permanent solution for the issue, because it's required everytime you add a new filter, I am only giving a hint which might be helpful to investigate the issue, in case you weren't aware.

**Comment by gorhill** [comment]
> might be helpful to investigate the issue

**Comment by gorhill** [comment]
I knew what the issue was since I wrote my above comment, it's the fact that the compiled lists are loaded in the worker before the filter is created.
