### ISSUE TITLE
Malvertising list is in the wrong category of filter lists

### ISSUE THREAD

**Issue by Aeriem** [uBlockOrigin/uBlock-issues#973]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I believe the "Malvertising filter list by Disconnect" is not in the right category.
It is a combination of three other lists : an ad list, a tracking list, and a malware list.
Therefore, I think it belongs in the "Multipurpose" category.
But here are some notes:
1. The malware part of this list is actually only one domain long and it is Disconnect's own test domain. It offers no malware protection whatsoever, so its current category (and title, but that's irrelevant) is misleading.
2. The dedicated malware list is as empty as this one.
3. One domain from the dedicated ad list is not included in this list. It seems the script Disconnect uses to combine the three lists into one replaces the first line from the ad list with the only line from the malware list.

With this in mind, I would suggest two solutions:
1. Move the list to the "Multipurpose" category.
OR
2. Replace this list with its components: the ad and tracking lists (not the malware one, because it is empty, as we've seen above).

As a reminder, here are the 4 URLs to the lists:
Ad list: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
Tracking list: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
Malware list: https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
Combination of the three lists above, the one currently included in uBlock Origin: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Open uBlock Origin's dashboard
2. Navigate to "Filter lists"
3. Observe the misplacement of "Malvertising filter list by Disconnect​​​​​​​​​" in the "Malware domains" category

### Expected behavior:

1. The malvertising list is in the "Multipurpose" category.
OR
2. Its components are in the appropriate categories, and used in place of the malvertising list.

### Actual behavior:

The malvertising list is in the "Malware domains" category. This is misleading as the list offers no malware protection.

### Your environment

* uBlock Origin version: 1.25.2
* Browser Name and version: Firefox 74.0
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Declined. I will stick to the list's own name in how to classify it. If you want to argue that the list is misnamed, open an issue with Disconnect.

**Comment by Aeriem** [comment]
This is fair, however the title itself seems to indicate this is meant to be a multipurpose list: the combination of malware and advertising in one word implies that.

Also, while I completely understand your position of sticking to the title, I'm surprised you do not seem to care about the total lack of any malware domain in the list.
An extremely quick look will show this in both the malware and malvertising lists.

You've often taken a pro-user stance, and this seems like a time where users are unintentionally mislead.
Having to manually check a list to be sure it actually corresponds to its title isn't very user-friendly to less tech-savvy people.

Lastly, replacing the Malvertising list with its components wouldn't remove any filter and would solve the misnaming issue.

I'd love to submit a PR in order to save you some time, should you agree to my previous comments.
Thank you for taking the time to read this issue, whatever you decide. 😄

**Comment by gorhill** [comment]
I looked into this more this morning.

The tracking list contains only 34 entries, of which 23 are used by uBO with default filter lists. There are so few entries in this list that it feels as being unmaintained -- and I doubt Disconnect is really using such a small list to protect its users against tracking.

The ad list contains 2,701 entries, if which 749 are used by uBO with default filter lists.

I strongly suspect those lists are no longer maintained for years now, since Disconnect stopped being open source. Because of this, I rather lean toward removing the list from uBO's stock lists -- also keeping in mind that Firefox Tracking Protection is using (probably more up to date) Disconnect's lists.

I would like to see the lists used by Firefox Tracking Protection.

**Comment by gwarser** [comment]
Firefox version is hosted here: https://github.com/mozilla-services/shavar-prod-lists

I tried searching domains from commits to https://github.com/disconnectme/disconnect-tracking-protection/ in Disconnect list, and I think it was last updated in 2017.

**Comment by Aeriem** [comment]
I tried searching too. It seems one of those two 2016 commits is the last to be included in Malvertising.
[6f8da2528636ccee0f57a715402025c3d8f9ceb2](https://github.com/disconnectme/disconnect-tracking-protection/commit/6f8da2528636ccee0f57a715402025c3d8f9ceb2) (This one does not indicate which new trackers were added, making it difficult to know whether it is included in the list or not.)
[8a8b711810f15d021b99d539d8c20c9ce13b41d6](https://github.com/disconnectme/disconnect-tracking-protection/commit/8a8b711810f15d021b99d539d8c20c9ce13b41d6)

Thanks for looking into it more!

**Comment by gorhill** [comment]
After looking how the list evolved over time at <https://web.archive.org/web/*/https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt>, I decide that I will remove the list.

The list has consistently shrunk in size since 2016. Especially in recent years, there has been very few additions, if any, while a lot of removal occurred -- possibly as a result of an automated script pruning dead servers.

It does seem that a few years ago the list did contain malware-related sites, but these have been removed since then.

So mainly this has become an unmaintained list and should be deemed unreliable and not suitable as a stock filter list in uBO.

**Comment by Aeriem** [comment]
Using the Internet Archive was a good idea!
Thanks for checking all of this out, I think your decision is the right one.
