### ISSUE TITLE
suggested filter list addition

### ISSUE THREAD

**Issue by Icekiss69** [uBlockOrigin/uBlock-issues#975]
Suggested filter list addition NoCoin adblock list for uBlock Origin
https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by uBlock-user** [comment]
> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

**Comment by gwarser** [comment]
Also duplicate: https://github.com/gorhill/uBlock/issues?q=is%3Aissue+sort%3Aupdated-desc+NoCoin+is%3Aclosed+in%3Atitle

uBO have its own "uBlock filters – Resource abuse​​​​​" list.

**Comment by Icekiss69** [comment]
when i add the no coin list 
https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt&title=NoCoin%20Filter%20List
after i already add everything in uBlock Origin it says
NoCoin Filter List​​​​​1,230 used out of 1,230​​​

this means the other filters do not cover anything nocoin does right?
does anyone test anything or look at anything or just speaking out of there asses?

**Comment by Icekiss69** [comment]
when i add the no coin list
https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt&title=NoCoin%20Filter%20List
after i already add everything in uBlock Origin it says
NoCoin Filter List​​​​​1,230 used out of 1,230​​​

this means the default filters in uBlock Origin do not cover anything nocoin does right?

**Comment by mapx-** [comment]
Easyprivacy contains 99% of those nocoin list

**Comment by gorhill** [comment]
> after i already add everything in uBlock Origin it says NoCoin Filter List​​​​​1,230 used out of 1,230​​​

The order lists are loaded is undefined, so if NoCoin loads before any other list, all its filters will be loaded. You have to compare the total number of filters. When doing so, it shows that with NoCoin there is an extra 707 network filters in memory. Still, two functionally similar filters may not be detected as duplicate by uBO (i.e. `||example.org^$3p` and `||example.org^`).

Including the list in uBO's stock filter lists has been declined in the past because it used to be too coarse, i.e. it was blocking whole domains, which would lead to site breakage, forcing a user to disable uBO, which is a worse outcome for the users. It seems the list has involved now to use EasyList syntax and even uBO's specific syntax.

If you find cases of coin mining not being blocked, as with any other filter issue report at <https://github.com/uBlockOrigin/uAssets/issues>. If enough of such issues are reported and found to be already fixed in NoCoin with a filter solution which satisfies uBO's filter list maintainers (no-breakage, optimal filters), then whether to include NoCoin in stock filter list will be reconsidered.
