### ISSUE TITLE
requestAnimationFrame-if and prefixed parameter

### ISSUE THREAD

**Issue by slavaleleka** [uBlockOrigin/uBlock-issues#981]
logic of **requestAnimationFrame-if** and **no-setInterval-if** are different — 
prefix `!` is needed for **mathing** in first case and **NOT matching** in second 

for what reason it has been done? and is there any chance to make a behaviour of the prefix `!` equal for raf-if.js, nosiif.js/nostif.js?

(as for me, it's better to use `!` for not matching)

**Comment by gorhill** [comment]
I should change `requestAnimationFrame-if` to match `no-setInterval-if`, if I remember correctly, `no-setInterval-if` was changed because most case require the blacklist approach, but `requestAnimationFrame-if` was not revisited.

I can't find instance of `requestAnimationFrame-if` in uBO's lists, so it should be a safe change.

**Comment by uBlock-user** [comment]
There's one filter in uBO Annoyances list for `bloomberg.com`

**Comment by slavaleleka** [comment]
@gorhill so you are going to revise it soon? or not soon?

**Comment by gorhill** [comment]
For sure for next release, but I need to think of how to make the change while keeping compatibility for the currently used version since it turns out it's being used after all.
